//This weaponClass object is generated by scripts which I moved to the r2MeleeParser repository. All that stuff was hyperspecific to the melee parsing endeavor and it just didn't need to be in this repo.
//I've also trimmed out most things that related to the game files themselves for now, since I can't guarantee 100% accuracy without help from a GFG dev. We'll go off of recorded values for now, and it sucks.

const evadeDuration = {
    //Not strictly guaranteed to be correct, on either of these, once again we're going off of generalized recorded values.
    "medium": 0.4,
    "flop": 1.266667
}

const standardMeleeDamageTags = {
    "basicAttack": {
        "Damage": ["AllDamage","MeleeDamage"],
        "CritChance": ["AllCritChance","MeleeCritChance"],
        "CritDamage": ["AllCritDamage","MeleeCritDamage"],
        "WeakSpot": ["AllWeakspot","MeleeWeakspot"],
		"Speed": ["AttackSpeed"],
    },
    "chargeAttack": {
        "Damage": ["AllDamage","MeleeDamage","ChargeDamage"],
        "CritChance": ["AllCritChance","MeleeCritChance","ChargeCritChance"],
        "CritDamage": ["AllCritDamage","MeleeCritDamage","ChargeCritDamage"],
        "WeakSpot": ["AllWeakspot","MeleeWeakspot"],
		"Speed": ["AttackSpeed"],
    },
    "backstep": {
        "Damage": ["AllDamage","MeleeDamage","BackstepDamage"],
        "CritChance": ["AllCritChance","MeleeCritChance"],
        "CritDamage": ["AllCritDamage","MeleeCritDamage"],
        "WeakSpot": ["AllWeakspot","MeleeWeakspot"],
		"Speed": ["AttackSpeed","EvadeSpeed"],
    },
    "backstepCharge": {
        "Damage": ["AllDamage","MeleeDamage","ChargeDamage","BackstepDamage"],
        "CritChance": ["AllCritChance","MeleeCritChance","ChargeCritChance"],
        "CritDamage": ["AllCritDamage","MeleeCritDamage","ChargeCritDamage"],
        "WeakSpot": ["AllWeakspot","MeleeWeakspot"],
		"Speed": ["AttackSpeed","EvadeSpeed"],
    }
}

weaponClass = {
	"Hammer": {//2M MATCH - cEvade
		"basicAttack": {
			"mv": [1,1],
			"attackType": ["Attack_Melee_01_Release","Attack_Melee_02_Release","Attack_Melee_03_Release"],//the third attack is used for sprints, not basics
			"attackName": ["AnimSequence'Player_M_2M_Atk_Hammer_01_Quick'","AnimSequence'Player_M_2M_Atk_Hammer_02_Quick'","AnimSequence'Player_M_2M_Atk_Hammer_03_Quick'"],
			"expectedDuration": 1.40,//confirmed lowest time
            "damageTags": standardMeleeDamageTags.basicAttack,
			"cost": [],
		},
		"chargeAttack": {
			"mv": [2.3,2.3],
			"attackType": ["Attack_Melee_01_Hold","Attack_Melee_02_Hold","Attack_Melee_03_Hold"],
			"attackName": ["AnimSequence'Player_M_2M_Atk_Hammer_Sprint_01'","AnimSequence'Player_M_2M_Atk_Hammer_02_Power'","AnimSequence'Player_M_2M_Atk_Hammer_Evade_Power'"],
			"windupType": ["Attack_Melee_01_Base","Attack_Melee_02_Base","Attack_Melee_03_Base"],
			"windupName": ["AnimSequence'Player_M_2M_Atk_Hammer_01_Charge'","AnimSequence'Player_M_2M_Atk_Hammer_02_Charge'","AnimSequence'Player_M_2M_Atk_Hammer_03_Charge'"],
			"expectedDuration": 2.6,//confirmed lowest time
            "damageTags": standardMeleeDamageTags.chargeAttack,
			"cost": [],
		},
		"backstep": {
			"mv": [1],
			"attackType": ["Attack_Special_Evade_Release"],
			"attackName": ["AnimSequence'Player_M_2M_Atk_Hammer_01_Quick'"],
			"expectedDuration": 1.1,//confirmed lowest time
			"expectedDurationFlop": 2,
            "damageTags": standardMeleeDamageTags.backstep,
			"cost": [],
		},
		"backstepCharge": {
			"mv": [2.8],
			"attackType": ["Attack_Special_Evade_Hold"],
			"attackName": ["AnimSequence'Player_M_2M_Atk_Hammer_03_Power'"],
			"windupType": ["Attack_Special_Evade_Base"],
			"windupName": ["AnimSequence'Player_M_2M_Atk_Hammer_Evade_Charge'"],
			"expectedDuration": 1.833333333,//confirmed lowest time
			"expectedDurationFlop": 2.7,
            "damageTags": standardMeleeDamageTags.backstepCharge,
			"cost": [],
		}
	},
	"Greatsword": {//2S
		"basicAttack": {
			"mv": [1,1.05,1.1],
			"attackType": ["Attack_Melee_01_Release","Attack_Melee_02_Release","Attack_Melee_03_Release"],
			"attackName": ["AnimSequence'Player_M_2S_Atk_BroadSword_Combo_01'","AnimSequence'Player_M_2S_Atk_BroadSword_Combo_02'","AnimSequence'Player_M_2S_Atk_BroadSword_Combo_03'"],
			"expectedDuration": 2.5666666666,//confirmed
            "damageTags": standardMeleeDamageTags.basicAttack,
			"cost": [],
		},
		"chargeAttack": {
			"mv": [1.7,1.8,1.9],
			"attackType": ["Attack_Melee_01_Hold","Attack_Melee_02_Hold","Attack_Melee_03_Hold"],
			"attackName": ["AnimSequence'Player_M_2S_Atk_BroadSword_Power_01'","AnimSequence'Player_M_2S_Atk_BroadSword_Power_02'","AnimSequence'Player_M_2S_Atk_BroadSword_Power_03'"],
			"windupType": ["Attack_Melee_01_Base","Attack_Melee_02_Base","Attack_Melee_03_Base"],
			"windupName": ["AnimSequence'Player_M_2S_Atk_BroadSword_Combo_01_Charge'","AnimSequence'Player_M_2S_Atk_BroadSword_Combo_02_Charge'","AnimSequence'Player_M_2S_Atk_BroadSword_Combo_03_Charge'"],
			"expectedDuration": 3.63333333333,//confirmed
            "damageTags": standardMeleeDamageTags.chargeAttack,
			"cost": [],
		},
		"backstep": {
			"mv": [1.5],
			"attackType": ["Attack_Special_Evade_Release"],
			"attackName": ["AnimSequence'Player_M_2S_Atk_BroadSword_Evade_B'"],
			"expectedDuration": 1.5833333333,//confirmed
            "damageTags": standardMeleeDamageTags.backstep,
			"cost": [],
		},
		"backstepCharge": {
			"mv": [2.35],
			"attackType": ["Attack_Special_Evade_Hold"],
			"attackName": ["AnimSequence'Player_M_2S_Atk_BroadSword_Evade_B_Power'"],
			"windupType": ["Attack_Special_Evade_Base"],
			"windupName": ["AnimSequence'Player_M_2S_Atk_BroadSword_Evade_B_Charge'"],
			"expectedDuration": 2.0333333333,//confirmed
            "damageTags": standardMeleeDamageTags.backstepCharge,
			"cost": [],
		}
	},
	"Sword": {//1M
		"basicAttack": { //
			"mv": [1,1.05,1.15],
			"attackType": ["Attack_Melee_01_Release","Attack_Melee_02_Release","Attack_Melee_03_Release"],
			"attackName": ["AnimSequence'Player_M_1M_Atk_Sword_01_Quick'","AnimSequence'Player_M_1M_Atk_Sword_02_Quick'","AnimSequence'Player_M_1M_Atk_Sword_03_Quick'"],
			"expectedDuration": 1.75,//confirmed
            "damageTags": standardMeleeDamageTags.basicAttack,
			//female 1.7
			"cost": [],
		},
		"chargeAttack": { //
			"mv": [2.2,2.2,2.25],
			"attackType": ["Attack_Melee_01_Hold","Attack_Melee_02_Hold","Attack_Melee_03_Hold"],
			"attackName": ["AnimSequence'Player_M_1M_Atk_Sword_01_Power'","AnimSequence'Player_M_1M_Atk_Sword_02_Power'","AnimSequence'Player_M_1M_Atk_Sword_03_Power'"],
			"windupType": ["Attack_Melee_01_Base","Attack_Melee_02_Base","Attack_Melee_03_Base"],
			"windupName": ["AnimSequence'Player_M_1M_Atk_Sword_01_Charge'","AnimSequence'Player_M_1M_Atk_Sword_02_Charge'","AnimSequence'Player_M_1M_Atk_Sword_03_Charge'"],
			"expectedDuration": 2.9166666666666,//confirmed
            "damageTags": standardMeleeDamageTags.chargeAttack,
			"cost": [],
		},
		"backstep": {//
			"mv": [1.05],
			"attackType": ["Attack_Special_Evade_Release"],
			"attackName": ["AnimSequence'Player_M_1M_Atk_Sword_Evade_Quick'"],
			"expectedDuration": 1.1,//confirmed
            "damageTags": standardMeleeDamageTags.backstep,
			"cost": [],
		},
		"backstepCharge": {//
			"mv": [2.25],
			"attackType": ["Attack_Special_Evade_Hold"],
			"attackName": ["AnimSequence'Player_M_1M_Atk_Sword_Evade_Power'"],
			"windupType": ["Attack_Special_Evade_Base"],
			"windupName": ["AnimSequence'Player_M_1M_Atk_Sword_Evade_Charge'"],
			"expectedDuration": 1.383333333333,//confirmed
            "damageTags": standardMeleeDamageTags.backstepCharge,
			"cost": [],
		}
	},
	"Claw": {//UN MATCH ALL
		"basicAttack": { //
			"mv": [1,1.1,1.2],
			"attackType": ["Attack_Melee_01_Release","Attack_Melee_02_Release","Attack_Melee_03_Release"],
			"attackName": ["AnimSequence'Player_M_UN_Atk_Combo_02_Quick_Claw'","AnimSequence'Player_M_UN_Atk_Combo_01_Quick_Claw'","AnimSequence'Player_M_UN_Atk_Combo_03_Quick_Claw'"],
			"expectedDuration": 1.8,//confirmed
            "damageTags": standardMeleeDamageTags.basicAttack,
			"cost": [],
		},
		"chargeAttack": { //
			"mv": [1.85,1.9,2.35],
			"attackType": ["Attack_Melee_01_Hold","Attack_Melee_02_Hold","Attack_Melee_03_Hold"],
			"attackName": ["AnimSequence'Player_M_UN_Atk_Combo_02_Power_Claw'","AnimSequence'Player_M_UN_Atk_Combo_01_Power_Claw'","AnimSequence'Player_M_UN_Atk_Combo_03_Power_Claw'"],
			"windupType": ["Attack_Melee_01_Base","Attack_Melee_02_Base","Attack_Melee_03_Base"],
			"windupName": ["AnimSequence'Player_M_UN_Atk_Combo_02_Charge_Claw'","AnimSequence'Player_M_UN_Atk_Combo_01_Charge_Claw'","AnimSequence'Player_M_UN_Atk_Combo_03_Charge_Claw'"],
			"expectedDuration": 2.733333333,//confirmed
            "damageTags": standardMeleeDamageTags.chargeAttack,
			"cost": [],
		},
		"backstep": {//
			"mv": [1.4],
			"attackType": ["Attack_Special_Evade_Release"],
			"attackName": ["AnimSequence'Player_M_UN_Atk_Evade_Quick_Claw'"],
			"expectedDuration": 1.0333333333,//confirmed
            "damageTags": standardMeleeDamageTags.backstep,
			"cost": [],
		},
		"backstepCharge": {//
			"mv": [[2,2]],
			"attackType": ["Attack_Special_Evade_Hold"],
			"attackName": ["AnimSequence'Player_M_UN_Atk_Evade_Power_Claw'"],
			"windupType": ["Attack_Special_Evade_Base"],
			"windupName": ["AnimSequence'Player_M_UN_Atk_Evade_Charge_Claw'"],
			"expectedDuration": 1.75,//confirmed
            "damageTags": standardMeleeDamageTags.backstepCharge,
			"cost": [],
		}
	},
	"Scythe": {//1M
		"basicAttack": {//I AM SKIPPING THE FIRST ATTACK IT IS SKIPPED ON COMBO CHAINS AFTER THE FIRST ITERATION
			"mv": [1.1,1.15,1.255],
			"attackType": ["Attack_Melee_02_Release","Attack_Melee_03_Release","Attack_Melee_04_Release"],//"Attack_Melee_01_Release",
			"attackName": ["AnimSequence'Player_M_1M_Atk_Scythe_02_Quick'","AnimSequence'Player_M_1M_Atk_Scythe_Evade_Quick_Copy'","AnimSequence'Player_M_1M_Atk_Scythe_04_Quick'"],//"AnimSequence'Player_M_1M_Atk_Scythe_03_Quick'",
			"expectedDuration": 1.9,//confirmed
            "damageTags": standardMeleeDamageTags.basicAttack,
			"cost": [],
		},
		"chargeAttack": {
			"mv": [[1.1,1.1,1.1],[1.25,1.25,1.25],[1.35,1.35,1.35],[2.65,2.7]],
			"attackType": ["Attack_Melee_01_Hold","Attack_Melee_02_Hold","Attack_Melee_03_Hold","Attack_Melee_04_Hold"],
			"attackName": ["AnimSequence'Player_M_1M_Atk_Scythe_01_Power'","AnimSequence'Player_M_1M_Atk_Scythe_02_Power'","AnimSequence'Player_M_1M_Atk_Scythe_Evade_Power_Copy'","AnimSequence'Player_M_1M_Atk_Scythe_04_Power'"],
			"windupType": ["Attack_Melee_01_Base","Attack_Melee_02_Base","Attack_Melee_03_Base","Attack_Melee_04_Base"],//There was a third statewindow on charge4 for 0.3s ? WUT?
			"windupName": ["AnimSequence'Player_M_1M_Atk_Scythe_03_Charge'","AnimSequence'Player_M_1M_Atk_Scythe_02_Charge'","AnimSequence'Player_M_1M_Atk_Scythe_03_Charge'","AnimSequence'Player_M_1M_Atk_Scythe_04_Charge'"],
			"expectedDuration": 6.0666666666,//male? 6.16666666666666666666666666666667
            "damageTags": standardMeleeDamageTags.chargeAttack,
			"cost": [],
		},
		"backstep": {
			"mv": [1.15],
			"attackType": ["Attack_Special_Evade_Release"],
			"attackName": ["AnimSequence'Player_M_1M_Atk_Scythe_Evade_Quick_Copy'"],
			"expectedDuration": 0.8666666666,//.9
            "damageTags": standardMeleeDamageTags.backstep,
			"cost": [],
		},
		"backstepCharge": {
			"mv": [[1.35,1.35,1.35]],
			"attackType": ["Attack_Special_Evade_Hold"],
			"attackName": ["AnimSequence'Player_M_1M_Atk_Scythe_Evade_Power_Copy'"],
			"windupType": ["Attack_Special_Evade_Base"],
			"windupName": ["AnimSequence'Player_M_1M_Atk_Scythe_Evade_Charge'"],
			"expectedDuration": 2.13333333,
            "damageTags": standardMeleeDamageTags.backstepCharge,
			"cost": [],
		}
	},
	"Fist": {//UN MATCH - cEvade //Fists uses custom damage tags in order to add unarmed/fist dmg
		"basicAttack": { //
			"mv": [1,1],
			"attackType": ["Attack_Melee_01_Release","Attack_Melee_02_Release","Attack_Melee_03_Release"],
			"attackName": ["AnimSequence'Player_M_UN_Atk_Hook_Combo_01'","AnimSequence'Player_M_UN_Atk_Hook_Combo_02'","AnimSequence'Player_M_UN_Atk_Combo_03_Quick'"],
			"expectedDuration": 0.9666666666666666,//confirmed
            "damageTags": {
				"Damage": [...standardMeleeDamageTags.basicAttack.Damage,"FistDamage"],
				"CritChance": [...standardMeleeDamageTags.basicAttack.CritChance],
				"CritDamage": [...standardMeleeDamageTags.basicAttack.CritDamage],
				"WeakSpot": [...standardMeleeDamageTags.basicAttack.WeakSpot],
				"Speed": [...standardMeleeDamageTags.basicAttack.Speed],
			},
			"cost": [],
		},
		"chargeAttack": { //
			"mv": [2.5,2.5],
			"attackType": ["Attack_Melee_01_Hold","Attack_Melee_02_Hold","Attack_Melee_03_Hold"],
			"attackName": ["AnimSequence'Player_M_UN_Atk_Hook_Combo_01_Power'","AnimSequence'Player_M_UN_Atk_Hook_Combo_02_Power'","AnimSequence'Player_M_UN_Atk_Combo_03_Power'"],
			"windupType": ["Attack_Melee_01_Base","Attack_Melee_02_Base","Attack_Melee_03_Base"],
			"windupName": ["AnimSequence'Player_M_UN_Atk_Combo_01_Charge'","AnimSequence'Player_M_UN_Atk_Combo_02_Charge'","AnimSequence'Player_M_UN_Atk_Combo_03_Charge'"],
			"expectedDuration": 1.966666666666666,
            "damageTags": {
				"Damage": [...standardMeleeDamageTags.chargeAttack.Damage,"FistDamage"],
				"CritChance": [...standardMeleeDamageTags.chargeAttack.CritChance],
				"CritDamage": [...standardMeleeDamageTags.chargeAttack.CritDamage],
				"WeakSpot": [...standardMeleeDamageTags.chargeAttack.WeakSpot],
				"Speed": [...standardMeleeDamageTags.chargeAttack.Speed],
			},
			"cost": [],
		},
		"backstep": {//
			"mv": [1.7],
			"attackType": ["Attack_Special_Evade_Release"],
			"attackName": ["AnimSequence'Player_M_UN_Atk_Combo_03'"],
			"expectedDuration": 1.25,//Had some weird super fast 1.16 rarely
            "damageTags": {
				"Damage": [...standardMeleeDamageTags.backstep.Damage,"FistDamage"],
				"CritChance": [...standardMeleeDamageTags.backstep.CritChance],
				"CritDamage": [...standardMeleeDamageTags.backstep.CritDamage],
				"WeakSpot": [...standardMeleeDamageTags.backstep.WeakSpot],
				"Speed": [...standardMeleeDamageTags.backstep.Speed],
			},
			"cost": [],
		},
		"backstepCharge": {//
			"mv": [4.1],
			"attackType": ["Attack_Special_Evade_Hold"],
			"attackName": ["AnimSequence'Player_M_UN_Atk_Combo_03_Power'"],
			"windupType": ["Attack_Special_Evade_Base"],
			"windupName": ["AnimSequence'Player_M_UN_Atk_Evade_Charge'"],
			"expectedDuration": 1.5666666666,
            "damageTags": {
				"Damage": [...standardMeleeDamageTags.backstepCharge.Damage,"FistDamage"],
				"CritChance": [...standardMeleeDamageTags.backstepCharge.CritChance],
				"CritDamage": [...standardMeleeDamageTags.backstepCharge.CritDamage],
				"WeakSpot": [...standardMeleeDamageTags.backstepCharge.WeakSpot],
				"Speed": [...standardMeleeDamageTags.backstepCharge.Speed],
			},
			"cost": [],
		}
	},
	"Flail": {
		//We're completely skipping the actual charge MV's on flails, bc who tf uses a flail for anything but helicopter
		// 	"windUpCost": 15,
		// 	"spinPerSecondCost": 35,
		// 	"ExitCost": 5,
		// },
		"basicAttack": { //
			"mv": [1,1.2,1.45],
			"attackType": ["Attack_Melee_01_Release","Attack_Melee_02_Release","Attack_Melee_03_Release"],
			"attackName": ["AnimSequence'Player_M_1M_Atk_Mace_01_Quick'","AnimSequence'Player_M_1M_Atk_Mace_02_Quick'","AnimSequence'Player_M_1M_Atk_Mace_03_Quick'"],
			"duration": [],
			"dilation": [[],[]],
			"dilationDuration": [],
			"windup": [],
			"windupAdjustment": [],
			"expectedDuration": 0,
            "damageTags": standardMeleeDamageTags.basicAttack,
			"cost": [],
		},
		"chargeAttack": { //
			"mv": [1],
			"mvNote": "This is the looping spin-attack. Cannot be modified by speed factors.<br>(the wind-up/down can, not the loop itself)",
			"attackType": ["Attack_Melee_01_Hold","Attack_Melee_02_Hold","Attack_Melee_03_Hold"],
			"attackName": ["AnimSequence'Player_M_1M_Atk_Flail_ChargeUp'","AnimSequence'Player_M_1M_Atk_Mace_02_Power'","AnimSequence'Player_M_1M_Atk_Mace_03_Power'"],
			"windupType": ["Attack_Melee_01_Base","Attack_Melee_02_Base","Attack_Melee_03_Base"],
			"windupName": ["AnimSequence'Player_M_1M_Atk_Mace_01_Charge'","AnimSequence'Player_M_1M_Atk_Mace_02_Charge'","AnimSequence'Player_M_1M_Atk_Mace_03_Charge'"],
			"duration": [],
			"dilation": [[],[]],
			"dilationDuration": [],
			"windup": [],
			"windupAdjustment": [],
			"expectedDuration": 0.5,
            "damageTags": {
				"Damage": [...standardMeleeDamageTags.chargeAttack.Damage],
				"CritChance": [...standardMeleeDamageTags.chargeAttack.CritChance],
				"CritDamage": [...standardMeleeDamageTags.chargeAttack.CritDamage],
				"WeakSpot": [...standardMeleeDamageTags.chargeAttack.WeakSpot],
				"Speed": [],//spin speed cannot be modified. Windup/down can, but the loop itself cannot.
			},
			"cost": [],
		},
		"backstep": {//
			"mv": [1.3],
			"attackType": ["Attack_Special_Evade_Release"],
			"attackName": ["AnimSequence'Player_M_1M_Atk_Mace_Evade_Quick'"],
			"duration": [],
			"dilation": [[]],
			"dilationDuration": [],
			"windup": [],
			"windupAdjustment": [],
			"expectedDuration": 0,
            "damageTags": standardMeleeDamageTags.backstep,
			"cost": [],
		},
		"backstepCharge": {//
			"mv": [2.3],
			"attackType": ["Attack_Special_Evade_Hold"],
			"attackName": ["AnimSequence'Player_M_1M_Atk_Mace_Evade_Power'"],
			"windupType": ["Attack_Special_Evade_Base"],
			"windupName": ["AnimSequence'Player_M_1M_Atk_Mace_Evade_Charge'"],
			"duration": [],
			"dilation": [[]],
			"dilationDuration": [],
			"windup": [],
			"windupAdjustment": [],
			"expectedDuration": 0,
            "damageTags": standardMeleeDamageTags.backstepCharge,
			"cost": [],
		}
	},
	"Spear": {//2M
		"basicAttack": { //
			"mv": [1,1,1.1],
			"attackType": ["Attack_Melee_01_Release","Attack_Melee_02_Release","Attack_Melee_03_Release"],
			"attackName": ["AnimSequence'Player_M_2M_Atk_Spear_01_Quick'","AnimSequence'Player_M_2M_Atk_Spear_02_Quick'","AnimSequence'Player_M_2M_Atk_Spear_03_Quick'"],
			"expectedDuration": 1.7666666666,
            "damageTags": standardMeleeDamageTags.basicAttack,
			"cost": [],
		},
		"chargeAttack": { //
			"mv": [1.9,2,2.25],
			"attackType": ["Attack_Melee_01_Hold","Attack_Melee_02_Hold","Attack_Melee_03_Hold"],
			"attackName": ["AnimSequence'Player_M_2M_Atk_Spear_01_Power'","AnimSequence'Player_M_2M_Atk_Spear_02_Power'","AnimSequence'Player_M_2M_Atk_Spear_03_Power'"],
			"windupType": ["Attack_Melee_01_Base","Attack_Melee_02_Base","Attack_Melee_03_Base"],
			"windupName": ["AnimSequence'Player_M_2M_Atk_Spear_01_Charge'","AnimSequence'Player_M_2M_Atk_Spear_02_Charge'","AnimSequence'Player_M_2M_Atk_Spear_03_Charge'"],
			"expectedDuration": 3.033333333333,
            "damageTags": standardMeleeDamageTags.chargeAttack,
			"cost": [],
		},
		"backstep": {//
			"mv": [1.15],
			"attackType": ["Attack_Special_Evade_Release"],
			"attackName": ["AnimSequence'Player_M_2M_Atk_Spear_Evade_Quick'"],
			"expectedDuration": 1.066666666666,
            "damageTags": standardMeleeDamageTags.backstep,
			"cost": [],
		},
		"backstepCharge": {//
			"mv": [2],
			"attackType": ["Attack_Special_Evade_Hold"],
			"attackName": ["AnimSequence'Player_M_2M_Atk_Spear_Evade_Power'"],
			"windupType": ["Attack_Special_Evade_Base"],
			"windupName": ["AnimSequence'Player_M_2M_Atk_Spear_Evade_Charge'"],
			"expectedDuration": 1.5666666666,
            "damageTags": standardMeleeDamageTags.backstepCharge,
			"cost": [],
		}
	},
	"Katana": {//2S
		"basicAttack": { //
			"mv": [1,1.1,1.2],
			"attackType": ["Attack_Melee_01_Release","Attack_Melee_02_Release","Attack_Melee_03_Release"],
			"attackName": ["AnimSequence'Player_M_2S_Atk_Katana_Combo_01_Power_Quick'","AnimSequence'Player_M_2S_Atk_Katana_Combo_02'","AnimSequence'Player_M_2S_Atk_Katana_Combo_03'"],
			"expectedDuration": 1.816666666,
            "damageTags": standardMeleeDamageTags.basicAttack,
			"cost": [],
		},
		"chargeAttack": { //
			"mv": [1.8,1.9,2.1],
			"attackType": ["Attack_Melee_01_Hold","Attack_Melee_02_Hold","Attack_Melee_03_Hold"],
			"attackName": ["AnimSequence'Player_M_2S_Atk_Katana_Combo_01_Power'","AnimSequence'Player_M_2S_Atk_Katana_Combo_02_Power'","AnimSequence'Player_M_2S_Atk_Katana_Combo_03_Power_Updated'"],
			"windupType": ["Attack_Melee_01_Base","Attack_Melee_02_Base","Attack_Melee_03_Base"],
			"windupName": ["AnimSequence'Player_M_2S_Atk_Katana_Combo_01_Charge'","AnimSequence'Player_M_2S_Atk_Katana_Combo_02_Charge'","AnimSequence'Player_M_2S_Atk_Katana_Combo_03_Charge'"],
			"expectedDuration": 2.56666666666,
            "damageTags": standardMeleeDamageTags.chargeAttack,
			"cost": [],
		},
		"backstep": {//
			"mv": [1.05],
			"attackType": ["Attack_Special_Evade_Release"],
			"attackName": ["AnimSequence'Player_M_2S_Atk_Katana_Combo_01'"],
			"expectedDuration": 0.7833333333,//up to 0.866666
            "damageTags": standardMeleeDamageTags.backstep,
			"cost": [],
		},
		"backstepCharge": {//
			"mv": [[0.9,0.9]],
			"attackType": ["Attack_Special_Evade_Hold"],
			"attackName": ["AnimSequence'Player_M_2S_Atk_Katana_Evade_B_01'"],
			"windupType": ["Attack_Special_Evade_Base"],
			"windupName": ["AnimSequence'Player_M_2S_Atk_Katana_Evade_B_01_Charge'"],
			"expectedDuration": 1.65,
            "damageTags": standardMeleeDamageTags.backstepCharge,
			"cost": [],
		}
	},
	"Staff": {//2M
		"basicAttack": { //
			"mv": [1,1.1,1.2],
			"attackType": ["Attack_Melee_01_Release","Attack_Melee_02_Release","Attack_Melee_03_Release"],
			"attackName": ["AnimSequence'Player_M_2M_Atk_Staff_Combo_01'","AnimSequence'Player_M_2M_Atk_Staff_Combo_02'","AnimSequence'Player_M_2M_Atk_Staff_Combo_03'"],
			"duration": [],
			"dilation": [[],[]],
			"dilationDuration": [],
			"windup": [],
			"windupAdjustment": [],
			"expectedDuration": 2.21666666666,//confirmed
            "damageTags": standardMeleeDamageTags.basicAttack,
			"cost": [],
		},
		"chargeAttack": { //
			"mv": [[1.5,1.15]],
			"attackType": ["Attack_Melee_01_Hold","Attack_Melee_02_Hold","Attack_Melee_03_Hold"],
			"attackName": ["AnimSequence'Player_M_2M_Atk_Staff_Slam_01'","AnimSequence'Player_M_2M_Atk_Staff_Slam_02'","AnimSequence'Player_M_2M_Atk_Staff_Slam_03'"],
			"windupType": ["Attack_Melee_01_Base","Attack_Melee_02_Base","Attack_Melee_03_Base"],
			"windupName": ["AnimSequence'Player_M_2M_Atk_Staff_Combo_01_Charge'","AnimSequence'Player_M_2M_Atk_Staff_Combo_02_Charge'","AnimSequence'Player_M_2M_Atk_Staff_Combo_03_Charge'"],
			"duration": [],
			"dilation": [[],[]],
			"dilationDuration": [],
			"windup": [],
			"windupAdjustment": [],
			"expectedDuration": 1.4,
            "damageTags": standardMeleeDamageTags.chargeAttack,
			"cost": [],
		},
		"backstep": {//
			"mv": [[1,0.9]],
			"attackType": ["Attack_Special_Evade_Release"],
			"attackName": ["AnimSequence'Player_M_2M_Atk_Staff_Evade'"],
			"duration": [],
			"dilation": [[]],
			"dilationDuration": [],
			"windup": [],
			"windupAdjustment": [],
			"expectedDuration": 1.41666666666,//up to 1.5
			"expectedDurationFlop": 0,
            "damageTags": standardMeleeDamageTags.backstep,
			"cost": [],
		},
		"backstepCharge": {//
			"mv": [[2,2]],
			"attackType": ["Attack_Special_Evade_Hold"],
			"attackName": ["AnimSequence'Player_M_2M_Atk_Staff_Evade_Power'"],
			"windupType": ["Attack_Special_Evade_Base"],
			"windupName": ["AnimSequence'Player_M_2M_Atk_Staff_Evade_Charge'"],
			"duration": [],
			"dilation": [[]],
			"dilationDuration": [],
			"windup": [],
			"windupAdjustment": [],
			"expectedDuration": 2.21666666666,
			"expectedDurationFlop": 0,
            "damageTags": standardMeleeDamageTags.backstepCharge,
			"cost": [],
		}
	},
	"Axe": {//1M MATCH ALL
		"basicAttack": {//quick2 quick3
			"mv": [1,1],
			"attackType": ["Attack_Melee_01_Release","Attack_Melee_02_Release"],
			"attackName": ["AnimSequence'Player_M_1M_Atk_Axe_02_Quick'","AnimSequence'Player_M_1M_Atk_Axe_03_Quick'"],
			"expectedDuration": 1.1666666666,//confirmed
            "damageTags": standardMeleeDamageTags.basicAttack,
			"cost": [],
		},
		"chargeAttack": {//power2 power3, charge2 charge3
			"mv": [[1.4,1.4],[1.4,1.4]],
			"attackType": ["Attack_Melee_01_Hold","Attack_Melee_02_Hold"],
			"attackName": ["AnimSequence'Player_M_1M_Atk_Axe_02_Power'","AnimSequence'Player_M_1M_Atk_Axe_03_Power'"],
			"windupType": ["Attack_Melee_01_Base","Attack_Melee_02_Base"],
			"windupName": ["AnimSequence'Player_M_1M_Atk_Axe_02_Charge'","AnimSequence'Player_M_1M_Atk_Axe_03_Charge'"],
			"expectedDuration": 2.7,//confirmed
            "damageTags": standardMeleeDamageTags.chargeAttack,
			"cost": [],
			"chargeCost": 10,
		},
		"backstep": {//evadequick
			"mv": [1.3],
			"attackType": ["Attack_Special_Evade_Release"],
			"attackName": ["AnimSequence'Player_M_1M_Atk_Axe_Evade_Quick'"],
			"expectedDuration": 1.05,//confirmed
			"expectedDurationFlop": 0,
            "damageTags": standardMeleeDamageTags.backstep,
			"cost": [],
		},
		"backstepCharge": {//evadepower, evadecharge
			"mv": [[1.65,1.65]],
			"attackType": ["Attack_Special_Evade_Hold"],
			"attackName": ["AnimSequence'Player_M_1M_Atk_Axe_Evade_Power'"],
			"windupType": ["Attack_Special_Evade_Base"],
			"windupName": ["AnimSequence'Player_M_1M_Atk_Axe_Evade_Charge'"],
			"expectedDuration": 1.8333333333,
			"expectedDurationFlop": 0,
            "damageTags": standardMeleeDamageTags.backstepCharge,
			"cost": [],
			"chargeCost": 15,
		},
	},

	//death sentence is just reg melee dmg

	//SPECIAL WEAPONS---------------------------
	"AtomSplitter": {//2S
		"basicAttack": {
			"mv": [1,1.05,1.1],
			"attackType": ["Attack_Melee_01_Release","Attack_Melee_02_Release","Attack_Melee_03_Release"],
			"attackName": ["AnimSequence'Player_M_2S_Atk_BroadSword_Combo_01'","AnimSequence'Player_M_2S_Atk_BroadSword_Combo_02'","AnimSequence'Player_M_2S_Atk_BroadSword_Combo_03'"],
			"expectedDuration": 2.5666666666,//confirmed
            "damageTags": standardMeleeDamageTags.basicAttack,
			"cost": [],
		},
		"chargeAttack": {
			"mv": [1.7,1.8,1.9],
			"attackType": ["Attack_Melee_01_Hold","Attack_Melee_02_Hold","Attack_Melee_03_Hold"],
			"attackName": ["AnimSequence'Player_M_2S_Atk_BroadSword_Power_01'","AnimSequence'Player_M_2S_Atk_BroadSword_Power_02'","AnimSequence'Player_M_2S_Atk_BroadSword_Power_03'"],
			"windupType": ["Attack_Melee_01_Base","Attack_Melee_02_Base","Attack_Melee_03_Base"],
			"windupName": ["AnimSequence'Player_M_2S_Atk_BroadSword_Combo_01_Charge'","AnimSequence'Player_M_2S_Atk_BroadSword_Combo_02_Charge'","AnimSequence'Player_M_2S_Atk_BroadSword_Combo_03_Charge'"],
			"expectedDuration": 3.63333333333,//confirmed
            "damageTags": standardMeleeDamageTags.chargeAttack,
			"cost": [],
		},
		"backstep": {
			"mv": [0.35],
			"mvNote": "Backstep attacks from this weapon deal less damage in exchange for a bonus projectile effect.",
			"projectile": [1.5],
			"attackType": ["Attack_Special_Evade_Release"],
			"attackName": ["AnimSequence'Player_M_2S_Atk_BroadSword_Evade_B'"],
			"expectedDuration": 1.5833333333,//confirmed
			"expectedDurationFlop": 1,
            "damageTags": standardMeleeDamageTags.backstep,
			"projectileTags": standardMeleeDamageTags.backstep,
			"cost": [],
		},
		"backstepCharge": {
			"mv": [0.35],
			"mvNote": "Backstep attacks from this weapon deal less damage in exchange for a bonus projectile effect.<br>The charged backstep variant gets a 25% unique multiplier, which is why the projectile multi here shows 1.875x instead of 1.5x",
			"projectile": [1.875],//The charge attack gets a 1.25 unique multi, 1.25 * 1.5 = 1.875
			"attackType": ["Attack_Special_Evade_Hold"],
			"attackName": ["AnimSequence'Player_M_2S_Atk_BroadSword_Evade_B_Power'"],
			"windupType": ["Attack_Special_Evade_Base"],
			"windupName": ["AnimSequence'Player_M_2S_Atk_BroadSword_Evade_B_Charge'"],
			"expectedDuration": 2.0333333333,//confirmed
			"expectedDurationFlop": 1,
            "damageTags": standardMeleeDamageTags.backstepCharge,
			"projectileTags": standardMeleeDamageTags.backstepCharge,
			"cost": [],
		}
	},
	"CrystalStaff": {//2M
		"basicAttack": { //
			"mv": [1,1.1,1.2],
			"attackType": ["Attack_Melee_01_Release","Attack_Melee_02_Release","Attack_Melee_03_Release"],
			"attackName": ["AnimSequence'Player_M_2M_Atk_Staff_Combo_01'","AnimSequence'Player_M_2M_Atk_Staff_Combo_02'","AnimSequence'Player_M_2M_Atk_Staff_Combo_03'"],
			"duration": [],
			"dilation": [[],[]],
			"dilationDuration": [],
			"windup": [],
			"windupAdjustment": [],
			"expectedDuration": 2.21666666666,//confirmed
            "damageTags": standardMeleeDamageTags.basicAttack,
			"cost": [],
		},
		"chargeAttack": { //
			//technically the last MV in the chain here is shock dmg, and that won't be factored as we have it now, only the projectiles will get the shock/elemental bonuses
			"mv": [0,1,1.1,1.2,1,1.1,1.2,[1.5,1.7857]],//final MV here is 225/126, which is the slam AOE turned into an MV so we can apply it via this method
			"mvNote": "Not strictly a charged attack, this is a composite combo of one Empower, six Basic Attacks(two full combos), then one Empowered Slam. Projectiles count as shock damage. Slam Projectiles count as SHOCK and Charged Melee.",
			"projectile": [0,1,1,1,1,1,1,0],//the end slam always has one more projectile than attacks done, due to the initial charge creating one stack.
			"projectileNote": "This is the shock projectile from each of the six basic attacks after empowering",
			"projectileChargeRelease": [0,0,0,0,0,0,0,[1,1,1,1,1,1,1]],//This is for the final charge slam release, these are charged attack projectiles. I hate this weapon from a calc perspective lmao.
			"projectileChargeReleaseNote": "This is the final charge attack in a combo, releasing six charge-variant shock projectiles. Unlike normal projectiles, these count as charged melee.",
			"attackType": ["Attack_Melee_01_Hold","Attack_Melee_02_Hold","Attack_Melee_03_Hold"],
			"attackName": ["AnimSequence'Player_M_2M_Atk_Staff_Slam_01'","AnimSequence'Player_M_2M_Atk_Staff_Slam_02'","AnimSequence'Player_M_2M_Atk_Staff_Slam_03'"],
			"windupType": ["Attack_Melee_01_Base","Attack_Melee_02_Base","Attack_Melee_03_Base"],
			"windupName": ["AnimSequence'Player_M_2M_Atk_Staff_Combo_01_Charge'","AnimSequence'Player_M_2M_Atk_Staff_Combo_02_Charge'","AnimSequence'Player_M_2M_Atk_Staff_Combo_03_Charge'"],
			"duration": [],
			"dilation": [[],[]],
			"dilationDuration": [],
			"windup": [],
			"windupAdjustment": [],
			"expectedDuration": 1.4 + 2.21666666666 + 2.21666666666 + 1.4,//This is the initial charge raise, 2 basic combos, and then a final charge slam
            "damageTags": standardMeleeDamageTags.basicAttack,
			"projectileTags": {
				"Damage": [...standardMeleeDamageTags.basicAttack.Damage,"ShockDamage","ElementalDamage"],
				"CritChance": [...standardMeleeDamageTags.basicAttack.CritChance,"ElementalCritChance"],
				"CritDamage": [...standardMeleeDamageTags.basicAttack.CritDamage],
				"WeakSpot": [...standardMeleeDamageTags.basicAttack.WeakSpot],
				"Speed": [...standardMeleeDamageTags.basicAttack.Speed],
			},
			"projectileChargeReleaseTags": {//The projectiles released from the charged slam release, count as CHARGED attacks, whereas the normal projectiles do not.
				"Damage": [...standardMeleeDamageTags.chargeAttack.Damage,"ShockDamage","ElementalDamage"],
				"CritChance": [...standardMeleeDamageTags.chargeAttack.CritChance,"ElementalCritChance"],
				"CritDamage": [...standardMeleeDamageTags.chargeAttack.CritDamage],
				"WeakSpot": [...standardMeleeDamageTags.chargeAttack.WeakSpot],
				"Speed": [...standardMeleeDamageTags.chargeAttack.Speed],
			},
			"cost": [],
		},
		"backstep": {//
			"mv": [0,[1,0.9]],
			"attackType": ["Attack_Special_Evade_Release"],
			"attackName": ["AnimSequence'Player_M_2M_Atk_Staff_Evade'"],
			"duration": [],
			"dilation": [[]],
			"dilationDuration": [],
			"windup": [],
			"windupAdjustment": [],
			"expectedDuration": 1.41666666666,//up to 1.5
            "damageTags": standardMeleeDamageTags.backstep,
			"cost": [],
		},
		"backstepCharge": {//
			"mv": [0,[2,2]],
			"attackType": ["Attack_Special_Evade_Hold"],
			"attackName": ["AnimSequence'Player_M_2M_Atk_Staff_Evade_Power'"],
			"windupType": ["Attack_Special_Evade_Base"],
			"windupName": ["AnimSequence'Player_M_2M_Atk_Staff_Evade_Charge'"],
			"duration": [],
			"dilation": [[]],
			"dilationDuration": [],
			"windup": [],
			"windupAdjustment": [],
			"expectedDuration": 2.21666666666,
            "damageTags": standardMeleeDamageTags.backstepCharge,
			"cost": [],
		}
	},
	"GasGiant": {//2M MATCH - cEvade
		"basicAttack": {
			"mv": [1,1],
			"mvNote": "While infused, this attack type counts as ACID damage. Since attacking itself infuses the weapon, we assume you are always infused.",
			"attackType": ["Attack_Melee_01_Release","Attack_Melee_02_Release","Attack_Melee_03_Release"],//the third attack is used for sprints, not basics
			"attackName": ["AnimSequence'Player_M_2M_Atk_Hammer_01_Quick'","AnimSequence'Player_M_2M_Atk_Hammer_02_Quick'","AnimSequence'Player_M_2M_Atk_Hammer_03_Quick'"],
			"expectedDuration": 1.40,//confirmed lowest time
            "damageTags": {
				"Damage": [...standardMeleeDamageTags.basicAttack.Damage,"AcidDamage","ElementalDamage"],
				"CritChance": [...standardMeleeDamageTags.basicAttack.CritChance,"ElementalCritChance"],
				"CritDamage": [...standardMeleeDamageTags.basicAttack.CritDamage],
				"WeakSpot": [...standardMeleeDamageTags.basicAttack.WeakSpot],
				"Speed": [...standardMeleeDamageTags.basicAttack.Speed],
			},
			"cost": [],
		},
		"chargeAttack": {
			"mv": [2.3,2.3],
			"attackType": ["Attack_Melee_01_Hold","Attack_Melee_02_Hold","Attack_Melee_03_Hold"],
			"attackName": ["AnimSequence'Player_M_2M_Atk_Hammer_Sprint_01'","AnimSequence'Player_M_2M_Atk_Hammer_02_Power'","AnimSequence'Player_M_2M_Atk_Hammer_Evade_Power'"],
			"windupType": ["Attack_Melee_01_Base","Attack_Melee_02_Base","Attack_Melee_03_Base"],
			"windupName": ["AnimSequence'Player_M_2M_Atk_Hammer_01_Charge'","AnimSequence'Player_M_2M_Atk_Hammer_02_Charge'","AnimSequence'Player_M_2M_Atk_Hammer_03_Charge'"],
			"expectedDuration": 2.6,//confirmed lowest time
            "damageTags": standardMeleeDamageTags.chargeAttack,
			"cost": [],
		},
		"backstep": {
			"mv": [1],
			"mvNote": "While infused, this attack type counts as ACID damage. Since attacking itself infuses the weapon, we assume you are always infused.",
			"attackType": ["Attack_Special_Evade_Release"],
			"attackName": ["AnimSequence'Player_M_2M_Atk_Hammer_01_Quick'"],
			"expectedDuration": 1.1,//confirmed lowest time
			"expectedDurationFlop": 2,
            "damageTags": {
				"Damage": [...standardMeleeDamageTags.backstep.Damage,"AcidDamage","ElementalDamage"],
				"CritChance": [...standardMeleeDamageTags.backstep.CritChance,"ElementalCritChance"],
				"CritDamage": [...standardMeleeDamageTags.backstep.CritDamage],
				"WeakSpot": [...standardMeleeDamageTags.backstep.WeakSpot],
				"Speed": [...standardMeleeDamageTags.backstep.Speed],
			},
			"cost": [],
		},
		"backstepCharge": {
			"mv": [2.8],
			"attackType": ["Attack_Special_Evade_Hold"],
			"attackName": ["AnimSequence'Player_M_2M_Atk_Hammer_03_Power'"],
			"windupType": ["Attack_Special_Evade_Base"],
			"windupName": ["AnimSequence'Player_M_2M_Atk_Hammer_Evade_Charge'"],
			"expectedDuration": 1.833333333,//confirmed lowest time
			"expectedDurationFlop": 2.7,
            "damageTags": standardMeleeDamageTags.backstepCharge,
			"cost": [],
		}
	},
	"HerosSword": {//1M
		"basicAttack": { //
			"mv": [1,1.05,1.15],
			"attackType": ["Attack_Melee_01_Release","Attack_Melee_02_Release","Attack_Melee_03_Release"],
			"attackName": ["AnimSequence'Player_M_1M_Atk_Sword_01_Quick'","AnimSequence'Player_M_1M_Atk_Sword_02_Quick'","AnimSequence'Player_M_1M_Atk_Sword_03_Quick'"],
			"expectedDuration": 1.75,//confirmed
            "damageTags": standardMeleeDamageTags.basicAttack,
			"cost": [],
		},
		"chargeAttack": { //
			"mv": [0.3,0.3,0.32],
			"mvNote": "Charged attacks from this weapon deal less damage in exchange for a bonus projectile effect.",
			"projectile": [1.79,1.79,1.79],
			"attackType": ["Attack_Melee_01_Hold","Attack_Melee_02_Hold","Attack_Melee_03_Hold"],
			"attackName": ["AnimSequence'Player_M_1M_Atk_Sword_01_Power'","AnimSequence'Player_M_1M_Atk_Sword_02_Power'","AnimSequence'Player_M_1M_Atk_Sword_03_Power'"],
			"windupType": ["Attack_Melee_01_Base","Attack_Melee_02_Base","Attack_Melee_03_Base"],
			"windupName": ["AnimSequence'Player_M_1M_Atk_Sword_01_Charge'","AnimSequence'Player_M_1M_Atk_Sword_02_Charge'","AnimSequence'Player_M_1M_Atk_Sword_03_Charge'"],
			"expectedDuration": 2.9166666666666,//confirmed
            "damageTags": standardMeleeDamageTags.chargeAttack,
			"projectileTags": standardMeleeDamageTags.chargeAttack,
			"cost": [],
		},
		"backstep": {//
			"mv": [1.05],
			"attackType": ["Attack_Special_Evade_Release"],
			"attackName": ["AnimSequence'Player_M_1M_Atk_Sword_Evade_Quick'"],
			"expectedDuration": 1.1,//confirmed
            "damageTags": standardMeleeDamageTags.backstep,
			"cost": [],
		},
		"backstepCharge": {//
			"mv": [0.32],
			"mvNote": "Charged attacks from this weapon deal less damage in exchange for a bonus projectile effect.",
			"projectile": [1.79],
			"attackType": ["Attack_Special_Evade_Hold"],
			"attackName": ["AnimSequence'Player_M_1M_Atk_Sword_Evade_Power'"],
			"windupType": ["Attack_Special_Evade_Base"],
			"windupName": ["AnimSequence'Player_M_1M_Atk_Sword_Evade_Charge'"],
			"expectedDuration": 1.383333333333,//confirmed
            "damageTags": standardMeleeDamageTags.backstepCharge,
			"projectileTags": standardMeleeDamageTags.backstepCharge,
			"cost": [],
		}
	},
	"HuntressSpear": {//2M
		"basicAttack": { //
			"mv": [1,1,1.1],
			"attackType": ["Attack_Melee_01_Release","Attack_Melee_02_Release","Attack_Melee_03_Release"],
			"attackName": ["AnimSequence'Player_M_2M_Atk_Spear_01_Quick'","AnimSequence'Player_M_2M_Atk_Spear_02_Quick'","AnimSequence'Player_M_2M_Atk_Spear_03_Quick'"],
			"expectedDuration": 1.7666666666,
            "damageTags": standardMeleeDamageTags.basicAttack,
			"cost": [],
		},
		"chargeAttack": { //
			"mv": [1.72],
			"mvNote": "This is the thrown melee attack. Cannot be modified by speed factors.<br>Unlike Krell Axe, this attack is not elemental.",
			"attackType": ["Attack_Melee_01_Hold","Attack_Melee_02_Hold","Attack_Melee_03_Hold"],
			"attackName": ["AnimSequence'Player_M_2M_Atk_Spear_01_Power'","AnimSequence'Player_M_2M_Atk_Spear_02_Power'","AnimSequence'Player_M_2M_Atk_Spear_03_Power'"],
			"windupType": ["Attack_Melee_01_Base","Attack_Melee_02_Base","Attack_Melee_03_Base"],
			"windupName": ["AnimSequence'Player_M_2M_Atk_Spear_01_Charge'","AnimSequence'Player_M_2M_Atk_Spear_02_Charge'","AnimSequence'Player_M_2M_Atk_Spear_03_Charge'"],
			"expectedDuration": 1.55,
            "damageTags": {
				"Damage": [...standardMeleeDamageTags.basicAttack.Damage],//somehow this isn't inherently acid damage, but krell's throw is shock?
				"CritChance": [...standardMeleeDamageTags.basicAttack.CritChance],
				"CritDamage": [...standardMeleeDamageTags.basicAttack.CritDamage],
				"WeakSpot": [...standardMeleeDamageTags.basicAttack.WeakSpot],
				"Speed": [],//throw windup/speed cannot be modified
			},
			"cost": [],
		},
		"backstep": {//
			"mv": [1.15],
			"attackType": ["Attack_Special_Evade_Release"],
			"attackName": ["AnimSequence'Player_M_2M_Atk_Spear_Evade_Quick'"],
			"expectedDuration": 1.066666666666,
			"expectedDurationFlop": 0,
            "damageTags": standardMeleeDamageTags.backstep,
			"cost": [],
		},
		"backstepCharge": {//
			"mv": [2],
			"attackType": ["Attack_Special_Evade_Hold"],
			"attackName": ["AnimSequence'Player_M_2M_Atk_Spear_Evade_Power'"],
			"windupType": ["Attack_Special_Evade_Base"],
			"windupName": ["AnimSequence'Player_M_2M_Atk_Spear_Evade_Charge'"],
			"expectedDuration": 1.5666666666,
			"expectedDurationFlop": 0,
            "damageTags": standardMeleeDamageTags.backstepCharge,
			"cost": [],
		}
	},
	"Mirage": {
		//We're completely skipping the actual charge MV's on flails, bc who tf uses a flail for anything but helicopter
		// 	"windUpCost": 15,
		// 	"spinPerSecondCost": 35,
		// 	"ExitCost": 5,
		// },
		"basicAttack": { //
			"mv": [1,1.2,1.45],
			"attackType": ["Attack_Melee_01_Release","Attack_Melee_02_Release","Attack_Melee_03_Release"],
			"attackName": ["AnimSequence'Player_M_1M_Atk_Mace_01_Quick'","AnimSequence'Player_M_1M_Atk_Mace_02_Quick'","AnimSequence'Player_M_1M_Atk_Mace_03_Quick'"],
			"duration": [],
			"dilation": [[],[]],
			"dilationDuration": [],
			"windup": [],
			"windupAdjustment": [],
			"expectedDuration": 0,
            "damageTags": standardMeleeDamageTags.basicAttack,
			"cost": [],
		},
		"chargeAttack": { //
			"mv": [1],
			"projectile": [0.12152777], // 144/17.5
			"mvNote": "This is the looping spin-attack. Cannot be modified by speed factors.<br>(the wind-up/down can, not the loop itself)",
			"projectileNote": "This the sandstorm AOE tick from the built-in mod, Cyclone. This mod is bugged and does not scale damage to what the description says. It will always do 17.5 base damage per tick, or, a total of 35 damage per second. Cannot weakspot. Counts as melee damage, but not charged melee.",
			"attackType": ["Attack_Melee_01_Hold","Attack_Melee_02_Hold","Attack_Melee_03_Hold"],
			"attackName": ["AnimSequence'Player_M_1M_Atk_Flail_ChargeUp'","AnimSequence'Player_M_1M_Atk_Mace_02_Power'","AnimSequence'Player_M_1M_Atk_Mace_03_Power'"],
			"windupType": ["Attack_Melee_01_Base","Attack_Melee_02_Base","Attack_Melee_03_Base"],
			"windupName": ["AnimSequence'Player_M_1M_Atk_Mace_01_Charge'","AnimSequence'Player_M_1M_Atk_Mace_02_Charge'","AnimSequence'Player_M_1M_Atk_Mace_03_Charge'"],
			"duration": [],
			"dilation": [[],[]],
			"dilationDuration": [],
			"windup": [],
			"windupAdjustment": [],
			"expectedDuration": 0.5,
            "damageTags": {
				"Damage": [...standardMeleeDamageTags.chargeAttack.Damage],
				"CritChance": [...standardMeleeDamageTags.chargeAttack.CritChance],
				"CritDamage": [...standardMeleeDamageTags.chargeAttack.CritDamage],
				"WeakSpot": [...standardMeleeDamageTags.chargeAttack.WeakSpot],
				"Speed": [],//spin speed cannot be modified. Windup/down can, but the loop itself cannot.
			},
			"projectileTags": {//the cyclone ticks are considered elemental damage, but NOT charged melee, just regular.
				"Damage": [...standardMeleeDamageTags.basicAttack.Damage, "ElementalDamage"],
				"CritChance": [...standardMeleeDamageTags.basicAttack.CritChance, "ElementalCritChance"],
				"CritDamage": [...standardMeleeDamageTags.basicAttack.CritDamage],
				"WeakSpot": -1,//can't weakspot
				"Speed": [],//spin speed cannot be modified. Windup/down can, but the loop itself cannot.
			},
			"cost": [],
		},
		"backstep": {//
			"mv": [1.3],
			"attackType": ["Attack_Special_Evade_Release"],
			"attackName": ["AnimSequence'Player_M_1M_Atk_Mace_Evade_Quick'"],
			"duration": [],
			"dilation": [[]],
			"dilationDuration": [],
			"windup": [],
			"windupAdjustment": [],
			"expectedDuration": 0,
            "damageTags": standardMeleeDamageTags.backstep,
			"cost": [],
		},
		"backstepCharge": {//
			"mv": [2.3],
			"attackType": ["Attack_Special_Evade_Hold"],
			"attackName": ["AnimSequence'Player_M_1M_Atk_Mace_Evade_Power'"],
			"windupType": ["Attack_Special_Evade_Base"],
			"windupName": ["AnimSequence'Player_M_1M_Atk_Mace_Evade_Charge'"],
			"duration": [],
			"dilation": [[]],
			"dilationDuration": [],
			"windup": [],
			"windupAdjustment": [],
			"expectedDuration": 0,
            "damageTags": standardMeleeDamageTags.backstepCharge,
			"cost": [],
		}
	},
	"Shovel": {//2M MATCH - cEvade
		"basicAttack": {
			"mv": [1,1],
			"attackType": ["Attack_Melee_01_Release","Attack_Melee_02_Release","Attack_Melee_03_Release"],//the third attack is used for sprints, not basics
			"attackName": ["AnimSequence'Player_M_2M_Atk_Hammer_01_Quick'","AnimSequence'Player_M_2M_Atk_Hammer_02_Quick'","AnimSequence'Player_M_2M_Atk_Hammer_03_Quick'"],
			"expectedDuration": 1.40,//confirmed lowest time
            "damageTags": standardMeleeDamageTags.basicAttack,
			"cost": [],
		},
		"chargeAttack": {
			"mv": [0],
			"mvNote": "This weapon's charged attack is replaced with a dig function: 25% chance to dig up ammo.",
			"attackType": ["Attack_Melee_01_Hold","Attack_Melee_02_Hold","Attack_Melee_03_Hold"],
			"attackName": ["AnimSequence'Player_M_2M_Atk_Hammer_Sprint_01'","AnimSequence'Player_M_2M_Atk_Hammer_02_Power'","AnimSequence'Player_M_2M_Atk_Hammer_Evade_Power'"],
			"windupType": ["Attack_Melee_01_Base","Attack_Melee_02_Base","Attack_Melee_03_Base"],
			"windupName": ["AnimSequence'Player_M_2M_Atk_Hammer_01_Charge'","AnimSequence'Player_M_2M_Atk_Hammer_02_Charge'","AnimSequence'Player_M_2M_Atk_Hammer_03_Charge'"],
			"expectedDuration": 1,//confirmed lowest time
            "damageTags": {
				"Damage": [],
				"CritChance": [],
				"CritDamage": [],
				"WeakSpot": [],
				"Speed": [],
			},
			"cost": [],
		},
		"backstep": {
			"mv": [1],
			"attackType": ["Attack_Special_Evade_Release"],
			"attackName": ["AnimSequence'Player_M_2M_Atk_Hammer_01_Quick'"],
			"expectedDuration": 1.1,//confirmed lowest time
			"expectedDurationFlop": 2,
            "damageTags": standardMeleeDamageTags.backstep,
			"cost": [],
		},
		"backstepCharge": {
			"mv": [2.8],
			"attackType": ["Attack_Special_Evade_Hold"],
			"attackName": ["AnimSequence'Player_M_2M_Atk_Hammer_03_Power'"],
			"windupType": ["Attack_Special_Evade_Base"],
			"windupName": ["AnimSequence'Player_M_2M_Atk_Hammer_Evade_Charge'"],
			"expectedDuration": 1.833333333,//confirmed lowest time
			"expectedDurationFlop": 2.7,
            "damageTags": standardMeleeDamageTags.backstepCharge,
			"cost": [],
		}
	},
	"Smolder": {//1M
		"basicAttack": { //
			"mv": [1,1.05,1.15],
			"mvNote": "All attacks from this weapon are considered to be Fire Damage",
			"attackType": ["Attack_Melee_01_Release","Attack_Melee_02_Release","Attack_Melee_03_Release"],
			"attackName": ["AnimSequence'Player_M_1M_Atk_Sword_01_Quick'","AnimSequence'Player_M_1M_Atk_Sword_02_Quick'","AnimSequence'Player_M_1M_Atk_Sword_03_Quick'"],
			"expectedDuration": 1.75,//confirmed
            "damageTags": {
				"Damage": [...standardMeleeDamageTags.basicAttack.Damage,"FireDamage","ElementalDamage"],
				"CritChance": [...standardMeleeDamageTags.basicAttack.CritChance,"ElementalCritChance"],
				"CritDamage": [...standardMeleeDamageTags.basicAttack.CritDamage],
				"WeakSpot": [...standardMeleeDamageTags.basicAttack.WeakSpot],
				"Speed": [...standardMeleeDamageTags.basicAttack.Speed],
			},
			"cost": [],
		},
		"chargeAttack": { //
			"mv": [2.2,2.2,2.25],
			"mvNote": "All attacks from this weapon are considered to be Fire Damage",
			"attackType": ["Attack_Melee_01_Hold","Attack_Melee_02_Hold","Attack_Melee_03_Hold"],
			"attackName": ["AnimSequence'Player_M_1M_Atk_Sword_01_Power'","AnimSequence'Player_M_1M_Atk_Sword_02_Power'","AnimSequence'Player_M_1M_Atk_Sword_03_Power'"],
			"windupType": ["Attack_Melee_01_Base","Attack_Melee_02_Base","Attack_Melee_03_Base"],
			"windupName": ["AnimSequence'Player_M_1M_Atk_Sword_01_Charge'","AnimSequence'Player_M_1M_Atk_Sword_02_Charge'","AnimSequence'Player_M_1M_Atk_Sword_03_Charge'"],
			"expectedDuration": 2.9166666666666,//confirmed
            "damageTags": {
				"Damage": [...standardMeleeDamageTags.chargeAttack.Damage,"FireDamage","ElementalDamage"],
				"CritChance": [...standardMeleeDamageTags.chargeAttack.CritChance,"ElementalCritChance"],
				"CritDamage": [...standardMeleeDamageTags.chargeAttack.CritDamage],
				"WeakSpot": [...standardMeleeDamageTags.chargeAttack.WeakSpot],
				"Speed": [...standardMeleeDamageTags.chargeAttack.Speed],
			},
			"cost": [],
		},
		"backstep": {//
			"mv": [1.05],
			"mvNote": "All attacks from this weapon are considered to be Fire Damage",
			"attackType": ["Attack_Special_Evade_Release"],
			"attackName": ["AnimSequence'Player_M_1M_Atk_Sword_Evade_Quick'"],
			"expectedDuration": 1.1,//confirmed
            "damageTags": {
				"Damage": [...standardMeleeDamageTags.backstep.Damage,"FireDamage","ElementalDamage"],
				"CritChance": [...standardMeleeDamageTags.backstep.CritChance,"ElementalCritChance"],
				"CritDamage": [...standardMeleeDamageTags.backstep.CritDamage],
				"WeakSpot": [...standardMeleeDamageTags.backstep.WeakSpot],
				"Speed": [...standardMeleeDamageTags.backstep.Speed],
			},
			"cost": [],
		},
		"backstepCharge": {//
			"mv": [2.25],
			"mvNote": "All attacks from this weapon are considered to be Fire Damage",
			"attackType": ["Attack_Special_Evade_Hold"],
			"attackName": ["AnimSequence'Player_M_1M_Atk_Sword_Evade_Power'"],
			"windupType": ["Attack_Special_Evade_Base"],
			"windupName": ["AnimSequence'Player_M_1M_Atk_Sword_Evade_Charge'"],
			"expectedDuration": 1.383333333333,//confirmed
			"expectedDurationFlop": 0,
            "damageTags": {
				"Damage": [...standardMeleeDamageTags.backstepCharge.Damage,"FireDamage","ElementalDamage"],
				"CritChance": [...standardMeleeDamageTags.backstepCharge.CritChance,"ElementalCritChance"],
				"CritDamage": [...standardMeleeDamageTags.backstepCharge.CritDamage],
				"WeakSpot": [...standardMeleeDamageTags.backstepCharge.WeakSpot],
				"Speed": [...standardMeleeDamageTags.backstepCharge.Speed],
			},
			"cost": [],
		}
	},
	"SpectralBlade": {//2S
		"basicAttack": { //
			"mv": [1,1.1,1.2],
			"attackType": ["Attack_Melee_01_Release","Attack_Melee_02_Release","Attack_Melee_03_Release"],
			"attackName": ["AnimSequence'Player_M_2S_Atk_Katana_Combo_01_Power_Quick'","AnimSequence'Player_M_2S_Atk_Katana_Combo_02'","AnimSequence'Player_M_2S_Atk_Katana_Combo_03'"],
			"expectedDuration": 1.816666666,
            "damageTags": standardMeleeDamageTags.basicAttack,
			"cost": [],
		},
		"chargeAttack": { //
			"mv": [1.8,1.9,2.1],
			"attackType": ["Attack_Melee_01_Hold","Attack_Melee_02_Hold","Attack_Melee_03_Hold"],
			"attackName": ["AnimSequence'Player_M_2S_Atk_Katana_Combo_01_Power'","AnimSequence'Player_M_2S_Atk_Katana_Combo_02_Power'","AnimSequence'Player_M_2S_Atk_Katana_Combo_03_Power_Updated'"],
			"windupType": ["Attack_Melee_01_Base","Attack_Melee_02_Base","Attack_Melee_03_Base"],
			"windupName": ["AnimSequence'Player_M_2S_Atk_Katana_Combo_01_Charge'","AnimSequence'Player_M_2S_Atk_Katana_Combo_02_Charge'","AnimSequence'Player_M_2S_Atk_Katana_Combo_03_Charge'"],
			"expectedDuration": 2.56666666666,
            "damageTags": standardMeleeDamageTags.chargeAttack,
			"cost": [],
		},
		"backstep": {//
			"mv": [1.05],
			"attackType": ["Attack_Special_Evade_Release"],
			"attackName": ["AnimSequence'Player_M_2S_Atk_Katana_Combo_01'"],
			"expectedDuration": 0.7833333333,//up to 0.866666
			"expectedDurationFlop": 0,
            "damageTags": standardMeleeDamageTags.backstep,
			"cost": [],
		},
		"backstepCharge": {//
			"mv": [1.2],
			"mvNote": "Charged backstep attacks change this katana's attack to a single strike that creates an AOE slash effect as well.",
			"projectile": [1.71698],// 273/159
			"attackType": ["Attack_Special_Evade_Hold"],
			"attackName": ["Player_M_2S_Atk_Katana_Combo_Special"],
			"windupType": ["Attack_Special_Evade_Base"],
			"windupName": ["AnimSequence'Player_M_2S_Atk_Katana_Evade_B_01_Charge'"],
			"expectedDuration": 1.65,
			"expectedDurationFlop": 0,
            "damageTags": standardMeleeDamageTags.backstepCharge,
			"cost": [],
		}
	},
	"Stonebreaker": {//2S
		"basicAttack": {
			"mv": [1,1.05,1.1],
			"attackType": ["Attack_Melee_01_Release","Attack_Melee_02_Release","Attack_Melee_03_Release"],
			"attackName": ["AnimSequence'Player_M_2S_Atk_BroadSword_Combo_01'","AnimSequence'Player_M_2S_Atk_BroadSword_Combo_02'","AnimSequence'Player_M_2S_Atk_BroadSword_Combo_03'"],
			"expectedDuration": 2.5666666666,//confirmed
            "damageTags": standardMeleeDamageTags.basicAttack,
			"cost": [],
		},
		"chargeAttack": {
			"mv": [0.35,0.35,0.35],
			"mvNote": "Charged attacks from this weapon deal less damage in exchange for a bonus projectile effect.",
			"projectile": [1.05,1.05,1.05],
			"attackType": ["Attack_Melee_01_Hold","Attack_Melee_02_Hold","Attack_Melee_03_Hold"],
			"attackName": ["AnimSequence'Player_M_2S_Atk_BroadSword_Power_01'","AnimSequence'Player_M_2S_Atk_BroadSword_Power_02'","AnimSequence'Player_M_2S_Atk_BroadSword_Power_03'"],
			"windupType": ["Attack_Melee_01_Base","Attack_Melee_02_Base","Attack_Melee_03_Base"],
			"windupName": ["AnimSequence'Player_M_2S_Atk_BroadSword_Combo_01_Charge'","AnimSequence'Player_M_2S_Atk_BroadSword_Combo_02_Charge'","AnimSequence'Player_M_2S_Atk_BroadSword_Combo_03_Charge'"],
			"expectedDuration": 3.63333333333,//confirmed
            "damageTags": standardMeleeDamageTags.chargeAttack,
			"projectileTags": standardMeleeDamageTags.chargeAttack,
			"cost": [],
		},
		"backstep": {
			"mv": [1.5],
			"attackType": ["Attack_Special_Evade_Release"],
			"attackName": ["AnimSequence'Player_M_2S_Atk_BroadSword_Evade_B'"],
			"expectedDuration": 1.5833333333,//confirmed
            "damageTags": standardMeleeDamageTags.backstep,
			"cost": [],
		},
		"backstepCharge": {
			"mv": [0.35],
			"mvNote": "Charged attacks from this weapon deal less damage in exchange for a bonus projectile effect.",
			"projectile": [1.05],
			"attackType": ["Attack_Special_Evade_Hold"],
			"attackName": ["AnimSequence'Player_M_2S_Atk_BroadSword_Evade_B_Power'"],
			"windupType": ["Attack_Special_Evade_Base"],
			"windupName": ["AnimSequence'Player_M_2S_Atk_BroadSword_Evade_B_Charge'"],
			"expectedDuration": 2.0333333333,//confirmed
            "damageTags": standardMeleeDamageTags.backstepCharge,
			"projectileTags": standardMeleeDamageTags.backstepCharge,
			"cost": [],
		}
	},
	"KrellAxe": {//1M MATCH ALL
		"basicAttack": {//quick2 quick3
			"mv": [1,1],
			"attackType": ["Attack_Melee_01_Release","Attack_Melee_02_Release"],
			"attackName": ["AnimSequence'Player_M_1M_Atk_Axe_02_Quick'","AnimSequence'Player_M_1M_Atk_Axe_03_Quick'"],
			"expectedDuration": 1.1666666666,//confirmed
            "damageTags": standardMeleeDamageTags.basicAttack,
			"cost": [],
		},
		"chargeAttack": {
			"mv": [1.6],
			"mvNote": "This is the thrown melee attack. Counts as SHOCK damage. Cannot be modified by speed factors.",
			"attackType": ["Attack_Melee_01_Hold","Attack_Melee_02_Hold"],
			"attackName": ["AnimSequence'Player_M_1M_Atk_Axe_02_Power'","AnimSequence'Player_M_1M_Atk_Axe_03_Power'"],
			"windupType": ["Attack_Melee_01_Base","Attack_Melee_02_Base"],
			"windupName": ["AnimSequence'Player_M_1M_Atk_Axe_02_Charge'","AnimSequence'Player_M_1M_Atk_Axe_03_Charge'"],
			"expectedDuration": 1.3333333333,//confirmed
            "damageTags": {//the thrown axe is considered shock/elemental
				"Damage": [...standardMeleeDamageTags.chargeAttack.Damage,"ShockDamage","ElementalDamage"],
				"CritChance": [...standardMeleeDamageTags.chargeAttack.CritChance,"ElementalCritChance"],
				"CritDamage": [...standardMeleeDamageTags.chargeAttack.CritDamage],
				"WeakSpot": [...standardMeleeDamageTags.chargeAttack.WeakSpot],
				"Speed": [],//the windup/speed cannot be modified
			},
			"cost": [],
			"chargeCost": 10,
		},
		"backstep": {//evadequick
			"mv": [1.3],
			"attackType": ["Attack_Special_Evade_Release"],
			"attackName": ["AnimSequence'Player_M_1M_Atk_Axe_Evade_Quick'"],
			"expectedDuration": 1.05,//confirmed
            "damageTags": standardMeleeDamageTags.backstep,
			"cost": [],
		},
		"backstepCharge": {//evadepower, evadecharge
			"mv": [[1.65,1.65]],
			"attackType": ["Attack_Special_Evade_Hold"],
			"attackName": ["AnimSequence'Player_M_1M_Atk_Axe_Evade_Power'"],
			"windupType": ["Attack_Special_Evade_Base"],
			"windupName": ["AnimSequence'Player_M_1M_Atk_Axe_Evade_Charge'"],
			"expectedDuration": 1.8333333333,
            "damageTags": standardMeleeDamageTags.backstepCharge,
			"cost": [],
			"chargeCost": 15,
		},
	},
	"WorldsEdge": {//2S
		"basicAttack": {
			"mv": [1,1.05,1.1],
			"attackType": ["Attack_Melee_01_Release","Attack_Melee_02_Release","Attack_Melee_03_Release"],
			"attackName": ["AnimSequence'Player_M_2S_Atk_BroadSword_Combo_01'","AnimSequence'Player_M_2S_Atk_BroadSword_Combo_02'","AnimSequence'Player_M_2S_Atk_BroadSword_Combo_03'"],
			"expectedDuration": 2.5666666666,//confirmed
            "damageTags": standardMeleeDamageTags.basicAttack,
			"cost": [],
		},
		"chargeAttack": {
			"mv": [0.35,0.35,0.35],
			"mvNote": "Charged attacks from this weapon deal less damage in exchange for a bonus projectile effect.",
			"projectile": [1.05,1.05,1.05],
			"attackType": ["Attack_Melee_01_Hold","Attack_Melee_02_Hold","Attack_Melee_03_Hold"],
			"attackName": ["AnimSequence'Player_M_2S_Atk_BroadSword_Power_01'","AnimSequence'Player_M_2S_Atk_BroadSword_Power_02'","AnimSequence'Player_M_2S_Atk_BroadSword_Power_03'"],
			"windupType": ["Attack_Melee_01_Base","Attack_Melee_02_Base","Attack_Melee_03_Base"],
			"windupName": ["AnimSequence'Player_M_2S_Atk_BroadSword_Combo_01_Charge'","AnimSequence'Player_M_2S_Atk_BroadSword_Combo_02_Charge'","AnimSequence'Player_M_2S_Atk_BroadSword_Combo_03_Charge'"],
			"expectedDuration": 3.63333333333,//confirmed
            "damageTags": standardMeleeDamageTags.chargeAttack,
			"projectileTags": standardMeleeDamageTags.chargeAttack,
			"cost": [],
		},
		"backstep": {
			"mv": [1.5],
			"attackType": ["Attack_Special_Evade_Release"],
			"attackName": ["AnimSequence'Player_M_2S_Atk_BroadSword_Evade_B'"],
			"expectedDuration": 1.5833333333,//confirmed
            "damageTags": standardMeleeDamageTags.backstep,
			"cost": [],
		},
		"backstepCharge": {
			"mv": [0.35],
			"mvNote": "Charged attacks from this weapon deal less damage in exchange for a bonus projectile effect.",
			"projectile": [1.05],
			"attackType": ["Attack_Special_Evade_Hold"],
			"attackName": ["AnimSequence'Player_M_2S_Atk_BroadSword_Evade_B_Power'"],
			"windupType": ["Attack_Special_Evade_Base"],
			"windupName": ["AnimSequence'Player_M_2S_Atk_BroadSword_Evade_B_Charge'"],
			"expectedDuration": 2.0333333333,//confirmed
            "damageTags": standardMeleeDamageTags.backstepCharge,
			"projectileTags": standardMeleeDamageTags.backstepCharge,
			"cost": [],
		}
	},
}