const Vulgus = {
    "None (True Damage)": {
        "name": "None (True Damage)",
        "realName": "None (True Damage)",
        "displayName": "None (True Damage)",
        "key": "None (True Damage)",
        "difficulty": "Normal",
        "levelKeys": {
            "1": {
                "lvl": 0,
                "lvlStats": {
                "HP": 0,
                "Shield": 0,
                "DEF": 0,
                "Non-Attribute": 0,
                "Fire": 0,
                "Chill": 0,
                "Electric": 0,
                "Toxic": 0,
                "ATK": 0,
                "Fire ATK": 0,
                "HP Recovery Interval": 0,
                "HP Recovery": 0,
                "HP Recovery In Combat": 0,
                "Shield Recovery Interval": 0,
                "Shield Recovery": 0,
                "Shield Recovery In Combat": 0,
                "Max Stagger HP and Rate": 0,
                "Max Stagger HP Rate": 0,
                "Max Stagger Rate": 0,
                "Stagger Decrease Rate": 0,
                "Stagger Decrease Delay": 0,
                "Time Limit": 0,
                "Max Frenzy Rate": 0,
                "Frenzy Damage Rate": 0,
                "Frenzy Decrease Delay": 0,
                "Frenzy Decrease Rate": 0,
                "Frenzy Duration": 0,
                "Colossus Level": 0
                }
            },
            "2": {
                "lvl": 0,
                "lvlStats": {
                "HP": 0,
                "Shield": 0,
                "DEF": 0,
                "Non-Attribute": 0,
                "Fire": 0,
                "Chill": 0,
                "Electric": 0,
                "Toxic": 0,
                "ATK": 0,
                "Fire ATK": 0,
                "HP Recovery Interval": 0,
                "HP Recovery": 0,
                "HP Recovery In Combat": 0,
                "Shield Recovery Interval": 0,
                "Shield Recovery": 0,
                "Shield Recovery In Combat": 0,
                "Max Stagger HP and Rate": 0,
                "Max Stagger HP Rate": 0,
                "Max Stagger Rate": 0,
                "Stagger Decrease Rate": 0,
                "Stagger Decrease Delay": 0,
                "Time Limit": 0,
                "Max Frenzy Rate": 0,
                "Frenzy Damage Rate": 0,
                "Frenzy Decrease Delay": 0,
                "Frenzy Decrease Rate": 0,
                "Frenzy Duration": 0,
                "Colossus Level": 0
                }
            },
            "3": {
                "lvl": 0,
                "lvlStats": {
                "HP": 0,
                "Shield": 0,
                "DEF": 0,
                "Non-Attribute": 0,
                "Fire": 0,
                "Chill": 0,
                "Electric": 0,
                "Toxic": 0,
                "ATK": 0,
                "Fire ATK": 0,
                "HP Recovery Interval": 0,
                "HP Recovery": 0,
                "HP Recovery In Combat": 0,
                "Shield Recovery Interval": 0,
                "Shield Recovery": 0,
                "Shield Recovery In Combat": 0,
                "Max Stagger HP and Rate": 0,
                "Max Stagger HP Rate": 0,
                "Max Stagger Rate": 0,
                "Stagger Decrease Rate": 0,
                "Stagger Decrease Delay": 0,
                "Time Limit": 0,
                "Max Frenzy Rate": 0,
                "Frenzy Damage Rate": 0,
                "Frenzy Decrease Delay": 0,
                "Frenzy Decrease Rate": 0,
                "Frenzy Duration": 0,
                "Colossus Level": 0
                }
            },
            "4": {
                "lvl": 0,
                "lvlStats": {
                "HP": 0,
                "Shield": 0,
                "DEF": 0,
                "Non-Attribute": 0,
                "Fire": 0,
                "Chill": 0,
                "Electric": 0,
                "Toxic": 0,
                "ATK": 0,
                "Fire ATK": 0,
                "HP Recovery Interval": 0,
                "HP Recovery": 0,
                "HP Recovery In Combat": 0,
                "Shield Recovery Interval": 0,
                "Shield Recovery": 0,
                "Shield Recovery In Combat": 0,
                "Max Stagger HP and Rate": 0,
                "Max Stagger HP Rate": 0,
                "Max Stagger Rate": 0,
                "Stagger Decrease Rate": 0,
                "Stagger Decrease Delay": 0,
                "Time Limit": 0,
                "Max Frenzy Rate": 0,
                "Frenzy Damage Rate": 0,
                "Frenzy Decrease Delay": 0,
                "Frenzy Decrease Rate": 0,
                "Frenzy Duration": 0,
                "Colossus Level": 0
                }
            }
        },
        "minimumTeam": 1,
        "attackType": "",
        "bigIcon": "que",
        "smallIcon": "que",
        "stats": {
            "Movespeed": 0,
            "Aim Movespeed": 0,
            "Berserk Movespeed": 0,
            "Movement Destruction": 0,
            "Crit Chance": 0,
            "Crit Damage": 0,
            "Firearm Crit Resist": 0,
            "Skill Crit Resist": 0,
            "Penetration Resist": 0,
            "Max Rage Rate": 0,
            "Penetration": 0
        },
        "weaknessKeys": {
            "Body (None)": {"name": "Body","type": "","wpMod": 0},
                
            "Body (Crush)": {"name": "Body","type": "Crush","wpMod": 0},
            "Body (Pierce)": {"name": "Body","type": "Pierce","wpMod": 0},
            "Body (Burst)": {"name": "Body","type": "Burst","wpMod": 0},

            "Generic .25 (Crush)": {"name": "N/A","type": "Crush","wpMod": 0.25},
            "Generic .25 (Pierce)": {"name": "N/A","type": "Pierce","wpMod": 0.25},
            "Generic .25 (Burst)": {"name": "N/A","type": "Burst","wpMod": 0.25},

            "Generic .375 (Crush)": {"name": "N/A","type": "Crush","wpMod": 0.375},
            "Generic .375 (Pierce)": {"name": "N/A","type": "Pierce","wpMod": 0.375},
            "Generic .375 (Burst)": {"name": "N/A","type": "Burst","wpMod": 0.375},

            "Generic .50 (Crush)": {"name": "N/A","type": "Crush","wpMod": 0.50},
            "Generic .50 (Pierce)": {"name": "N/A","type": "Pierce","wpMod": 0.50},
            "Generic .50 (Burst)": {"name": "N/A","type": "Burst","wpMod": 0.50},
        },
        "weaknessKeyName": "",
        "enemyType": "Colossus"
    },
    "Lgn. [1] Truth": {
        "name": "Lgn. [1] Truth",
        "realName": "Lgn. [1] Truth",
        "displayName": "Lgn. [1] Truth",
        "key": "Lgn. [1] Truth",
        "difficulty": "Normal",
        "levelKeys": {
            "1": {
                "lvl": 0,
                "lvlStats": {
                "HP": 0,
                "Shield": 0,
                "DEF": 0,
                "Non-Attribute": 0,
                "Fire": 167,
                "Chill": 167,
                "Electric": 0,
                "Toxic": 250,
                "ATK": 0,
                "Fire ATK": 0,
                "HP Recovery Interval": 0,
                "HP Recovery": 0,
                "HP Recovery In Combat": 0,
                "Shield Recovery Interval": 0,
                "Shield Recovery": 0,
                "Shield Recovery In Combat": 0,
                "Max Stagger HP and Rate": 0,
                "Max Stagger HP Rate": 0,
                "Max Stagger Rate": 0,
                "Stagger Decrease Rate": 0,
                "Stagger Decrease Delay": 0,
                "Time Limit": 0,
                "Max Frenzy Rate": 0,
                "Frenzy Damage Rate": 0,
                "Frenzy Decrease Delay": 0,
                "Frenzy Decrease Rate": 0,
                "Frenzy Duration": 0,
                "Colossus Level": 0
                }
            },
            "2": {
                "lvl": 0,
                "lvlStats": {
                "HP": 0,
                "Shield": 0,
                "DEF": 0,
                "Non-Attribute": 0,
                "Fire": 167,
                "Chill": 167,
                "Electric": 0,
                "Toxic": 250,
                "ATK": 0,
                "Fire ATK": 0,
                "HP Recovery Interval": 0,
                "HP Recovery": 0,
                "HP Recovery In Combat": 0,
                "Shield Recovery Interval": 0,
                "Shield Recovery": 0,
                "Shield Recovery In Combat": 0,
                "Max Stagger HP and Rate": 0,
                "Max Stagger HP Rate": 0,
                "Max Stagger Rate": 0,
                "Stagger Decrease Rate": 0,
                "Stagger Decrease Delay": 0,
                "Time Limit": 0,
                "Max Frenzy Rate": 0,
                "Frenzy Damage Rate": 0,
                "Frenzy Decrease Delay": 0,
                "Frenzy Decrease Rate": 0,
                "Frenzy Duration": 0,
                "Colossus Level": 0
                }
            },
            "3": {
                "lvl": 0,
                "lvlStats": {
                "HP": 0,
                "Shield": 0,
                "DEF": 0,
                "Non-Attribute": 0,
                "Fire": 167,
                "Chill": 167,
                "Electric": 0,
                "Toxic": 250,
                "ATK": 0,
                "Fire ATK": 0,
                "HP Recovery Interval": 0,
                "HP Recovery": 0,
                "HP Recovery In Combat": 0,
                "Shield Recovery Interval": 0,
                "Shield Recovery": 0,
                "Shield Recovery In Combat": 0,
                "Max Stagger HP and Rate": 0,
                "Max Stagger HP Rate": 0,
                "Max Stagger Rate": 0,
                "Stagger Decrease Rate": 0,
                "Stagger Decrease Delay": 0,
                "Time Limit": 0,
                "Max Frenzy Rate": 0,
                "Frenzy Damage Rate": 0,
                "Frenzy Decrease Delay": 0,
                "Frenzy Decrease Rate": 0,
                "Frenzy Duration": 0,
                "Colossus Level": 0
                }
            },
            "4": {
                "lvl": 0,
                "lvlStats": {
                "HP": 0,
                "Shield": 0,
                "DEF": 0,
                "Non-Attribute": 0,
                "Fire": 167,
                "Chill": 167,
                "Electric": 0,
                "Toxic": 250,
                "ATK": 0,
                "Fire ATK": 0,
                "HP Recovery Interval": 0,
                "HP Recovery": 0,
                "HP Recovery In Combat": 0,
                "Shield Recovery Interval": 0,
                "Shield Recovery": 0,
                "Shield Recovery In Combat": 0,
                "Max Stagger HP and Rate": 0,
                "Max Stagger HP Rate": 0,
                "Max Stagger Rate": 0,
                "Stagger Decrease Rate": 0,
                "Stagger Decrease Delay": 0,
                "Time Limit": 0,
                "Max Frenzy Rate": 0,
                "Frenzy Damage Rate": 0,
                "Frenzy Decrease Delay": 0,
                "Frenzy Decrease Rate": 0,
                "Frenzy Duration": 0,
                "Colossus Level": 0
                }
            }
        },
        "minimumTeam": 1,
        "attackType": "",
        "bigIcon": "que",
        "smallIcon": "que",
        "stats": {
            "Movespeed": 0,
            "Aim Movespeed": 0,
            "Berserk Movespeed": 0,
            "Movement Destruction": 0,
            "Crit Chance": 0,
            "Crit Damage": 0,
            "Firearm Crit Resist": 5,
            "Skill Crit Resist": 5,
            "Penetration Resist": 0,
            "Max Rage Rate": 0,
            "Penetration": 0
        },
        "weaknessKeys": {
            "Body (None)": {"name": "Body","type": "Burst","wpMod": 0},
            "Generic .50 (Burst)": {"name": "N/A","type": "Burst","wpMod": 0.50},
        },
        "weaknessKeyName": "",
        "enemyType": "Vulgus"
    },
    "Lgn. [1] Immortality": {
        "name": "Lgn. [1] Immortality",
        "realName": "Lgn. [1] Immortality",
        "displayName": "Lgn. [1] Immortality",
        "key": "Lgn. [1] Immortality",
        "difficulty": "Normal",
        "levelKeys": {
            "1": {
                "lvl": 0,
                "lvlStats": {
                "HP": 0,
                "Shield": 0,
                "DEF": 202,
                "Non-Attribute": 202,
                "Fire": 135,
                "Chill": 135,
                "Electric": 202,
                "Toxic": 101,
                "ATK": 0,
                "Fire ATK": 0,
                "HP Recovery Interval": 0,
                "HP Recovery": 0,
                "HP Recovery In Combat": 0,
                "Shield Recovery Interval": 0,
                "Shield Recovery": 0,
                "Shield Recovery In Combat": 0,
                "Max Stagger HP and Rate": 0,
                "Max Stagger HP Rate": 0,
                "Max Stagger Rate": 0,
                "Stagger Decrease Rate": 0,
                "Stagger Decrease Delay": 0,
                "Time Limit": 0,
                "Max Frenzy Rate": 0,
                "Frenzy Damage Rate": 0,
                "Frenzy Decrease Delay": 0,
                "Frenzy Decrease Rate": 0,
                "Frenzy Duration": 0,
                "Colossus Level": 0
                }
            },
            "2": {
                "lvl": 0,
                "lvlStats": {
                "HP": 0,
                "Shield": 0,
                "DEF": 202,
                "Non-Attribute": 202,
                "Fire": 135,
                "Chill": 135,
                "Electric": 202,
                "Toxic": 101,
                "ATK": 0,
                "Fire ATK": 0,
                "HP Recovery Interval": 0,
                "HP Recovery": 0,
                "HP Recovery In Combat": 0,
                "Shield Recovery Interval": 0,
                "Shield Recovery": 0,
                "Shield Recovery In Combat": 0,
                "Max Stagger HP and Rate": 0,
                "Max Stagger HP Rate": 0,
                "Max Stagger Rate": 0,
                "Stagger Decrease Rate": 0,
                "Stagger Decrease Delay": 0,
                "Time Limit": 0,
                "Max Frenzy Rate": 0,
                "Frenzy Damage Rate": 0,
                "Frenzy Decrease Delay": 0,
                "Frenzy Decrease Rate": 0,
                "Frenzy Duration": 0,
                "Colossus Level": 0
                }
            },
            "3": {
                "lvl": 0,
                "lvlStats": {
                "HP": 0,
                "Shield": 0,
                "DEF": 202,
                "Non-Attribute": 202,
                "Fire": 135,
                "Chill": 135,
                "Electric": 202,
                "Toxic": 101,
                "ATK": 0,
                "Fire ATK": 0,
                "HP Recovery Interval": 0,
                "HP Recovery": 0,
                "HP Recovery In Combat": 0,
                "Shield Recovery Interval": 0,
                "Shield Recovery": 0,
                "Shield Recovery In Combat": 0,
                "Max Stagger HP and Rate": 0,
                "Max Stagger HP Rate": 0,
                "Max Stagger Rate": 0,
                "Stagger Decrease Rate": 0,
                "Stagger Decrease Delay": 0,
                "Time Limit": 0,
                "Max Frenzy Rate": 0,
                "Frenzy Damage Rate": 0,
                "Frenzy Decrease Delay": 0,
                "Frenzy Decrease Rate": 0,
                "Frenzy Duration": 0,
                "Colossus Level": 0
                }
            },
            "4": {
                "lvl": 0,
                "lvlStats": {
                "HP": 0,
                "Shield": 0,
                "DEF": 202,
                "Non-Attribute": 202,
                "Fire": 135,
                "Chill": 135,
                "Electric": 202,
                "Toxic": 101,
                "ATK": 0,
                "Fire ATK": 0,
                "HP Recovery Interval": 0,
                "HP Recovery": 0,
                "HP Recovery In Combat": 0,
                "Shield Recovery Interval": 0,
                "Shield Recovery": 0,
                "Shield Recovery In Combat": 0,
                "Max Stagger HP and Rate": 0,
                "Max Stagger HP Rate": 0,
                "Max Stagger Rate": 0,
                "Stagger Decrease Rate": 0,
                "Stagger Decrease Delay": 0,
                "Time Limit": 0,
                "Max Frenzy Rate": 0,
                "Frenzy Damage Rate": 0,
                "Frenzy Decrease Delay": 0,
                "Frenzy Decrease Rate": 0,
                "Frenzy Duration": 0,
                "Colossus Level": 0
                }
            }
        },
        "minimumTeam": 1,
        "attackType": "",
        "bigIcon": "que",
        "smallIcon": "que",
        "stats": {
            "Movespeed": 0,
            "Aim Movespeed": 0,
            "Berserk Movespeed": 0,
            "Movement Destruction": 0,
            "Crit Chance": 0,
            "Crit Damage": 0,
            "Firearm Crit Resist": 5,
            "Skill Crit Resist": 5,
            "Penetration Resist": 0,
            "Max Rage Rate": 0,
            "Penetration": 0
        },
        "weaknessKeys": {
            "Body (None)": {"name": "Body","type": "Crush","wpMod": 0},
            "Generic .50 (Crush)": {"name": "N/A","type": "Crush","wpMod": 0.50},
        },
        "weaknessKeyName": "",
        "enemyType": "Vulgus"
    },
    "Lgn. [1] Darkness": {
        "name": "Lgn. [1] Darkness",
        "realName": "Lgn. [1] Darkness",
        "displayName": "Lgn. [1] Darkness",
        "key": "Lgn. [1] Darkness",
        "difficulty": "Normal",
        "levelKeys": {
            "1": {
                "lvl": 0,
                "lvlStats": {
                "HP": 0,
                "Shield": 0,
                "DEF": 288,
                "Non-Attribute": 288,
                "Fire": 288,
                "Chill": 144,
                "Electric": 192,
                "Toxic": 192,
                "ATK": 0,
                "Fire ATK": 0,
                "HP Recovery Interval": 0,
                "HP Recovery": 0,
                "HP Recovery In Combat": 0,
                "Shield Recovery Interval": 0,
                "Shield Recovery": 0,
                "Shield Recovery In Combat": 0,
                "Max Stagger HP and Rate": 0,
                "Max Stagger HP Rate": 0,
                "Max Stagger Rate": 0,
                "Stagger Decrease Rate": 0,
                "Stagger Decrease Delay": 0,
                "Time Limit": 0,
                "Max Frenzy Rate": 0,
                "Frenzy Damage Rate": 0,
                "Frenzy Decrease Delay": 0,
                "Frenzy Decrease Rate": 0,
                "Frenzy Duration": 0,
                "Colossus Level": 0
                }
            },
            "2": {
                "lvl": 0,
                "lvlStats": {
                "HP": 0,
                "Shield": 0,
                "DEF": 288,
                "Non-Attribute": 288,
                "Fire": 288,
                "Chill": 144,
                "Electric": 192,
                "Toxic": 192,
                "ATK": 0,
                "Fire ATK": 0,
                "HP Recovery Interval": 0,
                "HP Recovery": 0,
                "HP Recovery In Combat": 0,
                "Shield Recovery Interval": 0,
                "Shield Recovery": 0,
                "Shield Recovery In Combat": 0,
                "Max Stagger HP and Rate": 0,
                "Max Stagger HP Rate": 0,
                "Max Stagger Rate": 0,
                "Stagger Decrease Rate": 0,
                "Stagger Decrease Delay": 0,
                "Time Limit": 0,
                "Max Frenzy Rate": 0,
                "Frenzy Damage Rate": 0,
                "Frenzy Decrease Delay": 0,
                "Frenzy Decrease Rate": 0,
                "Frenzy Duration": 0,
                "Colossus Level": 0
                }
            },
            "3": {
                "lvl": 0,
                "lvlStats": {
                "HP": 0,
                "Shield": 0,
                "DEF": 288,
                "Non-Attribute": 288,
                "Fire": 288,
                "Chill": 144,
                "Electric": 192,
                "Toxic": 192,
                "ATK": 0,
                "Fire ATK": 0,
                "HP Recovery Interval": 0,
                "HP Recovery": 0,
                "HP Recovery In Combat": 0,
                "Shield Recovery Interval": 0,
                "Shield Recovery": 0,
                "Shield Recovery In Combat": 0,
                "Max Stagger HP and Rate": 0,
                "Max Stagger HP Rate": 0,
                "Max Stagger Rate": 0,
                "Stagger Decrease Rate": 0,
                "Stagger Decrease Delay": 0,
                "Time Limit": 0,
                "Max Frenzy Rate": 0,
                "Frenzy Damage Rate": 0,
                "Frenzy Decrease Delay": 0,
                "Frenzy Decrease Rate": 0,
                "Frenzy Duration": 0,
                "Colossus Level": 0
                }
            },
            "4": {
                "lvl": 0,
                "lvlStats": {
                "HP": 0,
                "Shield": 0,
                "DEF": 288,
                "Non-Attribute": 288,
                "Fire": 288,
                "Chill": 144,
                "Electric": 192,
                "Toxic": 192,
                "ATK": 0,
                "Fire ATK": 0,
                "HP Recovery Interval": 0,
                "HP Recovery": 0,
                "HP Recovery In Combat": 0,
                "Shield Recovery Interval": 0,
                "Shield Recovery": 0,
                "Shield Recovery In Combat": 0,
                "Max Stagger HP and Rate": 0,
                "Max Stagger HP Rate": 0,
                "Max Stagger Rate": 0,
                "Stagger Decrease Rate": 0,
                "Stagger Decrease Delay": 0,
                "Time Limit": 0,
                "Max Frenzy Rate": 0,
                "Frenzy Damage Rate": 0,
                "Frenzy Decrease Delay": 0,
                "Frenzy Decrease Rate": 0,
                "Frenzy Duration": 0,
                "Colossus Level": 0
                }
            }
        },
        "minimumTeam": 1,
        "attackType": "",
        "bigIcon": "que",
        "smallIcon": "que",
        "stats": {
            "Movespeed": 0,
            "Aim Movespeed": 0,
            "Berserk Movespeed": 0,
            "Movement Destruction": 0,
            "Crit Chance": 0,
            "Crit Damage": 0,
            "Firearm Crit Resist": 5,
            "Skill Crit Resist": 5,
            "Penetration Resist": 0,
            "Max Rage Rate": 0,
            "Penetration": 0
        },
        "weaknessKeys": {
            "Body (None)": {"name": "Body","type": "Pierce","wpMod": 0},
            "Generic .50 (Pierce)": {"name": "N/A","type": "Pierce","wpMod": 0.50},
        },
        "weaknessKeyName": "",
        "enemyType": "Vulgus"
    },
    "Lgn. [260] Truth": {
        "name": "Lgn. [260] Truth",
        "realName": "Lgn. [260] Truth",
        "displayName": "Lgn. [260] Truth",
        "key": "Lgn. [260] Truth",
        "difficulty": "Normal",
        "levelKeys": {
            "1": {
                "lvl": 0,
                "lvlStats": {
                "HP": 0,
                "Shield": 0,
                "DEF": 0,
                "Non-Attribute": 0,
                "Fire": 334950,
                "Chill": 334950,
                "Electric": 0,
                "Toxic": 502425,
                "ATK": 0,
                "Fire ATK": 0,
                "HP Recovery Interval": 0,
                "HP Recovery": 0,
                "HP Recovery In Combat": 0,
                "Shield Recovery Interval": 0,
                "Shield Recovery": 0,
                "Shield Recovery In Combat": 0,
                "Max Stagger HP and Rate": 0,
                "Max Stagger HP Rate": 0,
                "Max Stagger Rate": 0,
                "Stagger Decrease Rate": 0,
                "Stagger Decrease Delay": 0,
                "Time Limit": 0,
                "Max Frenzy Rate": 0,
                "Frenzy Damage Rate": 0,
                "Frenzy Decrease Delay": 0,
                "Frenzy Decrease Rate": 0,
                "Frenzy Duration": 0,
                "Colossus Level": 0
                }
            },
            "2": {
                "lvl": 0,
                "lvlStats": {
                "HP": 0,
                "Shield": 0,
                "DEF": 0,
                "Non-Attribute": 0,
                "Fire": 334950,
                "Chill": 334950,
                "Electric": 0,
                "Toxic": 502425,
                "ATK": 0,
                "Fire ATK": 0,
                "HP Recovery Interval": 0,
                "HP Recovery": 0,
                "HP Recovery In Combat": 0,
                "Shield Recovery Interval": 0,
                "Shield Recovery": 0,
                "Shield Recovery In Combat": 0,
                "Max Stagger HP and Rate": 0,
                "Max Stagger HP Rate": 0,
                "Max Stagger Rate": 0,
                "Stagger Decrease Rate": 0,
                "Stagger Decrease Delay": 0,
                "Time Limit": 0,
                "Max Frenzy Rate": 0,
                "Frenzy Damage Rate": 0,
                "Frenzy Decrease Delay": 0,
                "Frenzy Decrease Rate": 0,
                "Frenzy Duration": 0,
                "Colossus Level": 0
                }
            },
            "3": {
                "lvl": 0,
                "lvlStats": {
                "HP": 0,
                "Shield": 0,
                "DEF": 0,
                "Non-Attribute": 0,
                "Fire": 334950,
                "Chill": 334950,
                "Electric": 0,
                "Toxic": 502425,
                "ATK": 0,
                "Fire ATK": 0,
                "HP Recovery Interval": 0,
                "HP Recovery": 0,
                "HP Recovery In Combat": 0,
                "Shield Recovery Interval": 0,
                "Shield Recovery": 0,
                "Shield Recovery In Combat": 0,
                "Max Stagger HP and Rate": 0,
                "Max Stagger HP Rate": 0,
                "Max Stagger Rate": 0,
                "Stagger Decrease Rate": 0,
                "Stagger Decrease Delay": 0,
                "Time Limit": 0,
                "Max Frenzy Rate": 0,
                "Frenzy Damage Rate": 0,
                "Frenzy Decrease Delay": 0,
                "Frenzy Decrease Rate": 0,
                "Frenzy Duration": 0,
                "Colossus Level": 0
                }
            },
            "4": {
                "lvl": 0,
                "lvlStats": {
                "HP": 0,
                "Shield": 0,
                "DEF": 0,
                "Non-Attribute": 0,
                "Fire": 334950,
                "Chill": 334950,
                "Electric": 0,
                "Toxic": 502425,
                "ATK": 0,
                "Fire ATK": 0,
                "HP Recovery Interval": 0,
                "HP Recovery": 0,
                "HP Recovery In Combat": 0,
                "Shield Recovery Interval": 0,
                "Shield Recovery": 0,
                "Shield Recovery In Combat": 0,
                "Max Stagger HP and Rate": 0,
                "Max Stagger HP Rate": 0,
                "Max Stagger Rate": 0,
                "Stagger Decrease Rate": 0,
                "Stagger Decrease Delay": 0,
                "Time Limit": 0,
                "Max Frenzy Rate": 0,
                "Frenzy Damage Rate": 0,
                "Frenzy Decrease Delay": 0,
                "Frenzy Decrease Rate": 0,
                "Frenzy Duration": 0,
                "Colossus Level": 0
                }
            }
        },
        "minimumTeam": 1,
        "attackType": "",
        "bigIcon": "que",
        "smallIcon": "que",
        "stats": {
            "Movespeed": 0,
            "Aim Movespeed": 0,
            "Berserk Movespeed": 0,
            "Movement Destruction": 0,
            "Crit Chance": 0,
            "Crit Damage": 0,
            "Firearm Crit Resist": 5,
            "Skill Crit Resist": 5,
            "Penetration Resist": 0,
            "Max Rage Rate": 0,
            "Penetration": 0
        },
        "weaknessKeys": {
            "Body (None)": {"name": "Body","type": "Burst","wpMod": 0},
            "Generic .50 (Burst)": {"name": "N/A","type": "Burst","wpMod": 0.50},
        },
        "weaknessKeyName": "",
        "enemyType": "Vulgus"
    },
    "Lgn. [260] Immortality": {
        "name": "Lgn. [260] Immortality",
        "realName": "Lgn. [260] Immortality",
        "displayName": "Lgn. [260] Immortality",
        "key": "Lgn. [260] Immortality",
        "difficulty": "Normal",
        "levelKeys": {
            "1": {
                "lvl": 0,
                "lvlStats": {
                "HP": 0,//917784
                "Shield": 0,
                "DEF": 404452,
                "Non-Attribute": 404452,
                "Fire": 269635,
                "Chill": 269635,
                "Electric": 385193,
                "Toxic": 202226,
                "ATK": 0,
                "Fire ATK": 0,
                "HP Recovery Interval": 0,
                "HP Recovery": 0,
                "HP Recovery In Combat": 0,
                "Shield Recovery Interval": 0,
                "Shield Recovery": 0,
                "Shield Recovery In Combat": 0,
                "Max Stagger HP and Rate": 0,
                "Max Stagger HP Rate": 0,
                "Max Stagger Rate": 0,
                "Stagger Decrease Rate": 0,
                "Stagger Decrease Delay": 0,
                "Time Limit": 0,
                "Max Frenzy Rate": 0,
                "Frenzy Damage Rate": 0,
                "Frenzy Decrease Delay": 0,
                "Frenzy Decrease Rate": 0,
                "Frenzy Duration": 0,
                "Colossus Level": 0
                }
            },
            "2": {
                "lvl": 0,
                "lvlStats": {
                "HP": 0,
                "Shield": 0,
                "DEF": 577789,
                "Non-Attribute": 577789,
                "Fire": 577789,
                "Chill": 288895,
                "Electric": 385193,
                "Toxic": 385193,
                "ATK": 0,
                "Fire ATK": 0,
                "HP Recovery Interval": 0,
                "HP Recovery": 0,
                "HP Recovery In Combat": 0,
                "Shield Recovery Interval": 0,
                "Shield Recovery": 0,
                "Shield Recovery In Combat": 0,
                "Max Stagger HP and Rate": 0,
                "Max Stagger HP Rate": 0,
                "Max Stagger Rate": 0,
                "Stagger Decrease Rate": 0,
                "Stagger Decrease Delay": 0,
                "Time Limit": 0,
                "Max Frenzy Rate": 0,
                "Frenzy Damage Rate": 0,
                "Frenzy Decrease Delay": 0,
                "Frenzy Decrease Rate": 0,
                "Frenzy Duration": 0,
                "Colossus Level": 0
                }
            },
            "3": {
                "lvl": 0,
                "lvlStats": {
                "HP": 0,
                "Shield": 0,
                "DEF": 577789,
                "Non-Attribute": 577789,
                "Fire": 577789,
                "Chill": 288895,
                "Electric": 385193,
                "Toxic": 385193,
                "ATK": 0,
                "Fire ATK": 0,
                "HP Recovery Interval": 0,
                "HP Recovery": 0,
                "HP Recovery In Combat": 0,
                "Shield Recovery Interval": 0,
                "Shield Recovery": 0,
                "Shield Recovery In Combat": 0,
                "Max Stagger HP and Rate": 0,
                "Max Stagger HP Rate": 0,
                "Max Stagger Rate": 0,
                "Stagger Decrease Rate": 0,
                "Stagger Decrease Delay": 0,
                "Time Limit": 0,
                "Max Frenzy Rate": 0,
                "Frenzy Damage Rate": 0,
                "Frenzy Decrease Delay": 0,
                "Frenzy Decrease Rate": 0,
                "Frenzy Duration": 0,
                "Colossus Level": 0
                }
            },
            "4": {
                "lvl": 0,
                "lvlStats": {
                "HP": 0,
                "Shield": 0,
                "DEF": 577789,
                "Non-Attribute": 577789,
                "Fire": 577789,
                "Chill": 288895,
                "Electric": 385193,
                "Toxic": 385193,
                "ATK": 0,
                "Fire ATK": 0,
                "HP Recovery Interval": 0,
                "HP Recovery": 0,
                "HP Recovery In Combat": 0,
                "Shield Recovery Interval": 0,
                "Shield Recovery": 0,
                "Shield Recovery In Combat": 0,
                "Max Stagger HP and Rate": 0,
                "Max Stagger HP Rate": 0,
                "Max Stagger Rate": 0,
                "Stagger Decrease Rate": 0,
                "Stagger Decrease Delay": 0,
                "Time Limit": 0,
                "Max Frenzy Rate": 0,
                "Frenzy Damage Rate": 0,
                "Frenzy Decrease Delay": 0,
                "Frenzy Decrease Rate": 0,
                "Frenzy Duration": 0,
                "Colossus Level": 0
                }
            }
        },
        "minimumTeam": 1,
        "attackType": "",
        "bigIcon": "que",
        "smallIcon": "que",
        "stats": {
            "Movespeed": 0,
            "Aim Movespeed": 0,
            "Berserk Movespeed": 0,
            "Movement Destruction": 0,
            "Crit Chance": 0,
            "Crit Damage": 0,
            "Firearm Crit Resist": 5,
            "Skill Crit Resist": 5,
            "Penetration Resist": 0,
            "Max Rage Rate": 0,
            "Penetration": 0
        },
        "weaknessKeys": {
            "Body (None)": {"name": "Body","type": "Crush","wpMod": 0},
            "Generic .50 (Crush)": {"name": "N/A","type": "Crush","wpMod": 0.50},
        },
        "weaknessKeyName": "",
        "enemyType": "Vulgus"
    },
    "Lgn. [260] Darkness": {
        "name": "Lgn. [260] Darkness",
        "realName": "Lgn. [260] Darkness",
        "displayName": "Lgn. [260] Darkness",
        "key": "Lgn. [260] Darkness",
        "difficulty": "Normal",
        "levelKeys": {
            "1": {
                "lvl": 0,
                "lvlStats": {
                "HP": 0,//917784
                "Shield": 0,
                "DEF": 577789,
                "Non-Attribute": 577789,
                "Fire": 577789,
                "Chill": 288895,
                "Electric": 385193,
                "Toxic": 385193,
                "ATK": 0,
                "Fire ATK": 0,
                "HP Recovery Interval": 0,
                "HP Recovery": 0,
                "HP Recovery In Combat": 0,
                "Shield Recovery Interval": 0,
                "Shield Recovery": 0,
                "Shield Recovery In Combat": 0,
                "Max Stagger HP and Rate": 0,
                "Max Stagger HP Rate": 0,
                "Max Stagger Rate": 0,
                "Stagger Decrease Rate": 0,
                "Stagger Decrease Delay": 0,
                "Time Limit": 0,
                "Max Frenzy Rate": 0,
                "Frenzy Damage Rate": 0,
                "Frenzy Decrease Delay": 0,
                "Frenzy Decrease Rate": 0,
                "Frenzy Duration": 0,
                "Colossus Level": 0
                }
            },
            "2": {
                "lvl": 0,
                "lvlStats": {
                "HP": 0,
                "Shield": 0,
                "DEF": 577789,
                "Non-Attribute": 577789,
                "Fire": 577789,
                "Chill": 288895,
                "Electric": 385193,
                "Toxic": 385193,
                "ATK": 0,
                "Fire ATK": 0,
                "HP Recovery Interval": 0,
                "HP Recovery": 0,
                "HP Recovery In Combat": 0,
                "Shield Recovery Interval": 0,
                "Shield Recovery": 0,
                "Shield Recovery In Combat": 0,
                "Max Stagger HP and Rate": 0,
                "Max Stagger HP Rate": 0,
                "Max Stagger Rate": 0,
                "Stagger Decrease Rate": 0,
                "Stagger Decrease Delay": 0,
                "Time Limit": 0,
                "Max Frenzy Rate": 0,
                "Frenzy Damage Rate": 0,
                "Frenzy Decrease Delay": 0,
                "Frenzy Decrease Rate": 0,
                "Frenzy Duration": 0,
                "Colossus Level": 0
                }
            },
            "3": {
                "lvl": 0,
                "lvlStats": {
                "HP": 0,
                "Shield": 0,
                "DEF": 577789,
                "Non-Attribute": 577789,
                "Fire": 577789,
                "Chill": 288895,
                "Electric": 385193,
                "Toxic": 385193,
                "ATK": 0,
                "Fire ATK": 0,
                "HP Recovery Interval": 0,
                "HP Recovery": 0,
                "HP Recovery In Combat": 0,
                "Shield Recovery Interval": 0,
                "Shield Recovery": 0,
                "Shield Recovery In Combat": 0,
                "Max Stagger HP and Rate": 0,
                "Max Stagger HP Rate": 0,
                "Max Stagger Rate": 0,
                "Stagger Decrease Rate": 0,
                "Stagger Decrease Delay": 0,
                "Time Limit": 0,
                "Max Frenzy Rate": 0,
                "Frenzy Damage Rate": 0,
                "Frenzy Decrease Delay": 0,
                "Frenzy Decrease Rate": 0,
                "Frenzy Duration": 0,
                "Colossus Level": 0
                }
            },
            "4": {
                "lvl": 0,
                "lvlStats": {
                "HP": 0,
                "Shield": 0,
                "DEF": 577789,
                "Non-Attribute": 577789,
                "Fire": 577789,
                "Chill": 288895,
                "Electric": 385193,
                "Toxic": 385193,
                "ATK": 0,
                "Fire ATK": 0,
                "HP Recovery Interval": 0,
                "HP Recovery": 0,
                "HP Recovery In Combat": 0,
                "Shield Recovery Interval": 0,
                "Shield Recovery": 0,
                "Shield Recovery In Combat": 0,
                "Max Stagger HP and Rate": 0,
                "Max Stagger HP Rate": 0,
                "Max Stagger Rate": 0,
                "Stagger Decrease Rate": 0,
                "Stagger Decrease Delay": 0,
                "Time Limit": 0,
                "Max Frenzy Rate": 0,
                "Frenzy Damage Rate": 0,
                "Frenzy Decrease Delay": 0,
                "Frenzy Decrease Rate": 0,
                "Frenzy Duration": 0,
                "Colossus Level": 0
                }
            }
        },
        "minimumTeam": 1,
        "attackType": "",
        "bigIcon": "que",
        "smallIcon": "que",
        "stats": {
            "Movespeed": 0,
            "Aim Movespeed": 0,
            "Berserk Movespeed": 0,
            "Movement Destruction": 0,
            "Crit Chance": 0,
            "Crit Damage": 0,
            "Firearm Crit Resist": 5,
            "Skill Crit Resist": 5,
            "Penetration Resist": 0,
            "Max Rage Rate": 0,
            "Penetration": 0
        },
        "weaknessKeys": {
            "Body (None)": {"name": "Body","type": "Pierce","wpMod": 0},
            "Generic .50 (Pierce)": {"name": "N/A","type": "Pierce","wpMod": 0.50},
        },
        "weaknessKeyName": "",
        "enemyType": "Vulgus"
    },
}