//Just copy pasted from my work on the Remnant 2 section of my site, this will have non-relevant parts in the code, just leaving it there for now

const bosses = {
    // {
    //     "name":"attackName",
    //     "description": "attackDescription",
    //     "damage": 0,
    //     "stagger": 1,
    //     "hpBased": false,
    //     "hpPercent": 0,
    //     "drBypass": false,
    //     "canBeLethal": false,
    //     "lethalCondition": "",
    //     "isBuffed": false,
    //     "attackType": "Hit",
    //     "frequency": 0,
    // },
    "None (True Damage)": {
        "image": "/TFD/TFDImages/Bosses/Icon_VoidBattle_EpicMonster_Devourer.png",
        "shortName": "NONE",
        "buffs": {},

        "skillCrit": 0,
        "gunCrit": 0,
        "note": "",

        "parts": [
            {"name": "Body","type": "Burst","wpMod": 0},
        ],

        "DEF": 0,
        "Non-Attribute": 0,
        "Fire": 0,
        "Electric": 0,
        "Chill": 0,
        "Toxic": 0,
    },
    "Executioner": {
        "image": "/TFD/TFDImages/Bosses/Icon_VoidBattle_EpicMonster_Executioner.png",
        "shortName": "Executioner",
        "buffs": {},

        "skillCrit": 0.25,
        "gunCrit": 0.26,
        "note": "",

        "parts": [
            {"name": "Body","type": "Burst","wpMod": 0},
            {"name": "Shoulder","type": "Pierce","wpMod": 0.25},
            {"name": "Core","type": "Pierce","wpMod": 0.375},
            {"name": "Balancer","type": "Pierce","wpMod": 0.375},
            {"name": "Sensor","type": "Pierce","wpMod": 0.50},
        ],

        "DEF": 146003,////was 146,074
        "Non-Attribute": 146003,//was 146,074
        "Fire": 226617.8,//was 226707
        "Electric": 372421,//was 372489
        "Chill": 146003.15,//was 146,074, //TODO check if the def and non attribute values line up with the .15 here
        "Toxic": 67282,//67226? //67225.69301

        "attacks": [
           {
                "name":"Basic 1",
                "description": "Abomination rushes you with 6 attacks. This is the first.",
                "damage": 104.187,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Basic 2",
                "description": "Abomination rushes you with 6 attacks. This is the second.",
                "damage": 104.187,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Basic 3",
                "description": "Abomination rushes you with 6 attacks. This is the third.",
                "damage": 104.187,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Heavy 1",
                "description": "Abomination rushes you with 6 attacks. This is the fourth.",
                "damage": 111.629,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": true,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Heavy 2",
                "description": "Abomination rushes you with 6 attacks. This is the fifth.",
                "damage": 111.629,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": true,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Heavy Follow-up",
                "description": "Abomination rushes you with 6 attacks. This is the sixth and last, hitting much lighter than the last two.",
                "damage": 104.187,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Sliding Charge",
                "description": "Abomination rushes you while sliding instead of rolling, booping you to the floor.",
                "damage": 223.258,
                "stagger": 3,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Leap Slam (Mid-air)",
                "description": "Abomination leaps across the arena down on top of you. This is for the damage if he connects with you mid-air, not the ground impact.",
                "damage": 327.445,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Leap Slam (AOE)",
                "description": "Abomination leaps across the arena down on top of you. This is for the damage on ground impact.",
                "damage": 148.839,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Suppressor AOE",
                "description": "Abomination generates a supression pool underneath him during various attacks. This generation of the pool itself seems to do damage, but the attack itself is a mystery. It can deal this damage with a 0.01s frequency with a shotgun type approach, or it can be spaced out. Damage is reduced only by Blight Resistance.",
                "damage": 37.21,
                "stagger": 1,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": true,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "damageType": "Blight",
                "frequency": 0,
            },
            {
                "name":"Cannister Throw (Swing)",
                "description": "Abomination Leans back and throws an explosive cannister. Deals damage once when leaning back, and once again after the throw is completed.",
                "damage": 148.839,
                "stagger": 1,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Cannister Throw (Projectile)",
                "description": "Abomination Leans back and throws an explosive cannister. This is the damage the cannister deals to you if it hits you mid-air, not the resulting explosion.",
                "damage": 74.419,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Cannister Explosion",
                "description": "The resulting explosion after Abomination throws any explosive cannisters. Note that the damage of the cannister's physical hitbox is different, this is just the explosion.",
                "damage": 96.745,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": true,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Roll",
                "description": "Abomination will begin rolling around the arena. Every time he connects with you, this damage will be dealt once.",
                "damage": 267.91,
                "stagger": 3,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Rolling Acid Toss",
                "description": "Abomination will begin rolling around the arena. Every time he connects with you, this damage will be dealt once.",
                "damage": 148.839,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": true,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Floating Toss",
                "description": "Abomination will rise into the air and throw several projectiles at you.",
                "damage": 111.629,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Floating Shockwave",
                "description": "While flying, after Abomination finishes throwing all projectiles it will charge up and release a shockwave.",
                "damage": 416.748,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Descent Slam",
                "description": "After casting the flying shockwave attack, Abomination will return to the ground with a slam.",
                "damage": 416.748,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Drzyr Zombies",
                "description": "Drzyr citizens will come to attack you at various points in the fight, this is the damage they deal per hit.",
                "damage": 148.839,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Mines",
                "description": "Throughout the arena there are various mines in place the player can shoot at to detonate. These mines count as player originated damage, and as such benefit from player ALL DAMAGE % bonuses even when the damage is dealt to the player themselves.",
                "damage": 63,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": true,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "damageType": "Player",
                "frequency": 0,
            },
        ]
    },
    "Dead Bride": {
        "image": "/TFD/TFDImages/Bosses/Icon_VoidBattle_EpicMonster_DeadBride.png",
        "shortName": "Dead Bride",
        "buffs": {},

        "skillCrit": 0.20,
        "gunCrit": 0.20,
        "note": "",

        "parts": [
            {"name": "Body","type": "Burst","wpMod": 0},
            {"name": "Shoulder","type": "Pierce","wpMod": 0.25},
            {"name": "Core","type": "Pierce","wpMod": 0.375},
            {"name": "Balancer","type": "Pierce","wpMod": 0.375},
            {"name": "Sensor","type": "Pierce","wpMod": 0.50},
        ],

        "DEF": 92413,//was 92430,
        "Non-Attribute": 92413,//was 92430
        "Fire": 39697.9,//was 39699
        "Electric": 92413.1,//was 92430 //TODO: use this an example later. 92413.1 is right but the flat values would not be correct
        "Chill": 248510.64,//was 248637, //TODO: amazing example to use, for all 3 skils, including whether the crit lines up on the Q with or without the max stack bonus
        "Toxic": 147463,//was 147564,

        "attacks": [
            {
                "name":"Basic - Flying Overhead",
                "description": "Used to initiate many combos, but can only be launched while Annihilation is flying. A flying overhead sword swing that brings him down to the ground as well.",
                "damage": 197.955,
                "stagger": 3,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Basic 1",
                "description": "First basic attack: left sword swing.",
                "damage": 197.955,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Basic 2",
                "description": "Second basic attack: Right dragging sword swing.",
                "damage": 197.955,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Forward Sword Drag",
                "description": "Annihilation drags his sword on the ground, moving straight forward before launching himself into the air in prep for a ground slam. This attack is only for the damage of the sword drag.",
                "damage": 197.955,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Slam AOE Wave",
                "description": "After dragging his sword and launching into the sky, Annihilation will charge for a moment before slamming back to the ground sending out a red AOE shockwave.",
                "damage": 217.751,
                "stagger": 3,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Root Snare",
                "description": "After doing slam attacks, Annihilation will sometimes pierce the ground with his sword and send out root snares to catch you. This attack is only for the damage of the root snare if it catches you.",
                "damage": 19.796,
                "stagger": 1,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Orbital Strikes",
                "description": "Throughout the duration of the fight, little red beacons will strike the ground, leaving a red trail into the sky where they came from. After long enough, the beacons will detonate, dealing damage within the red circle around them.",
                "damage": 110.855,
                "stagger": 1,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Orb Detonations",
                "description": "In both phase 1 and phase 2, Annihilation can summon floating spheres that when left alive long enough, will home in on the player and detonate. This is per orb.",
                "damage": 89.303,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": true,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Dive Slam 1",
                "description": "Annihilation will raise into the sky while spinning before returning to the ground to do a piercing dive slam AOE. This is part of a 2-3 hit combo.",
                "damage": 138.569,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": true,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Dive Slam 2",
                "description": "Annihilation will raise into the sky while spinning before returning to the ground to do a piercing dive slam AOE. This is part of a 2-3 hit combo.",
                "damage": 138.569,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": true,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            }, 
            {
                "name":"Dive Slam 3",
                "description": "Annihilation will raise into the sky while spinning before returning to the ground to do a piercing dive slam AOE. This is the third and final strike of the combo, and it is not guaranteed to happen. Rather, this attack is incredibly rare.",
                "damage": 138.569,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": true,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            }, 
            {
                "name":"P2: Basic - Overhead",
                "description": "Annihilation's Split form will do an overhead strike with their sword.",
                "damage": 158.364,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            }, 
            {
                "name":"P2: Halves Swipe",
                "description": "Annihilation's Split form will drag the sword from the center point of the arena, to the end of whichever half the player is standing in.",
                "damage": 158.364,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"P2: Full Swipe",
                "description": "Annihilation's Split form will drag the sword from one end of the arena, to the other end.",
                "damage": 158.364,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            }, 
            {
                "name":"P2: Cloud Slam",
                "description": "Annihilation's Split form will slam sending an instantaneous shockwave to the entire arena. At the same time, it will spawn a pestilent cloud on the player that will afflict them with Data Corruption if stood in for too long.",
                "damage": 59.387,
                "stagger": 1,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            }, 
            {
                "name":"P2: Grid Lines",
                "description": "Annihilation's Split form will create a set of grid lines in front of him before launching the grid towards the back of arena. This is per grid line, multiple can hit at once.",
                "damage": 168.262,
                "stagger": 1,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            }, 
            {
                "name":"P2: Orb Spawn Shockwave",
                "description": "Annihilation's Split form will blast the arena, pushing everyone away from him. He'll do it once more before spawning orbs. This is attack is per shockwave he emits before spawning orbs.",
                "damage": 19.796,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            }, 
            {
                "name":"P2: Roots Slap",
                "description": "Annihilation's Split will sometimes spawn roots in a grid within the arena floor. After some time, the roots will indicate which direction they will fall towards (always towards another root) before doing the attack.",
                "damage": 22.5,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            }, 
        ]
    },
    "Devourer": {
        "image": "/TFD/TFDImages/Bosses/Icon_VoidBattle_EpicMonster_Devourer.png",
        "shortName": "Devourer",
        "buffs": {},

        "skillCrit": 0.25,
        "gunCrit": 0.27,
        "note": "",

        "parts": [
            {"name": "Body","type": "Pierce","wpMod": 0},
            {"name": "Shoulder","type": "Crush","wpMod": 0.25},
            {"name": "Core","type": "Crush","wpMod": 0.25},
            {"name": "Balancer","type": "Burst","wpMod": 0.25},
            {"name": "Sensor","type": "Burst","wpMod": 0.50},
        ],

        "DEF": 162159,//was 162232
        "Non-Attribute": 162159,//was 162232
        "Fire": 162159.1,//was 162232
        "Electric": 75718.5,//was 75746
        "Chill": 250195.05,//was 250324
        "Toxic": 408925,//409149,

        "attacks": [
           {
                "name":"Basic Attack",
                "description": "The Astropath will rise up and do a wide swiping swing.",
                "damage": 148.839,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Shotgun Orb: Blast 1",
                "description": "The Astropath summon two orbs that will hover in the air for a moment before blasting out a shotgun-like pattern of projectiles. This is the damage of the first orb's blast.",
                "damage": 148.839,
                "stagger": 1,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": true,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Shotgun Orb: Blast 2",
                "description": "The Astropath summon two orbs that will hover in the air for a moment before blasting out a shotgun-like pattern of projectiles. This is the damage of the second orb's blast.",
                "damage": 223.258,
                "stagger": 1,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Spiral Orb Toss",
                "description": "The Astropath will throw out an orb projectile from either hand, that is accompanied by a spiral effect.",
                "damage": 223.258,
                "stagger": 1,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Double Arm Swing",
                "description": "The Astropath fly up to the player and swing both their arms at once in a crossing pattern.",
                "damage": 267.910,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Possession: Arena Core",
                "description": "The Astropath will fly into the ground and posses the Navigation Computer. While possessed, the Nav Computer emits a circle AOE effect in the center of the arena. This is the damage you take for standing inside of it.",
                "damage": 0,
                "stagger": 1,
                "hpBased": true,
                "hpPercent": 41.6748,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "%HP",
                "frequency": 0.5,
            },
            {
                "name":"Possession: Shockwave",
                "description": "The Astropath will fly into the ground and posses the Navigation Computer. While possessed, the Nav Computer can send out a shockwave effect, or do a rotator effect that deals damage once it stops spinning. This is the damage for the shockwave effect.",
                "damage": 238.142,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Possession: Rotator",
                "description": "The Astropath will fly into the ground and posses the Navigation Computer. While possessed, the Nav Computer can send out a shockwave effect, or do a rotator effect that deals damage once it stops spinning. This is the damage for the rotator when it stops spinning.",
                "damage": 238.142,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Ground Clone: Scream",
                "description": "The Astropath vanish and the arena will turn black in the Darkness phase. Pink clones of the Astropath will crawl out of the ground and do different attacks. This clone comes out of the ground to eye-level with the player and screams dealing damage if you are nearby.",
                "damage": 107.164,
                "stagger": 1,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": true,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Ground Clone: Orb Throw",
                "description": "The Astropath vanish and the arena will turn black in the Darkness phase. Pink clones of the Astropath will crawl out of the ground and do different attacks. This clone comes halfway out of the ground and throws an orb projectile at the player.",
                "damage": 107.164,
                "stagger": 1,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Ground Clone: Swipe",
                "description": "The Astropath vanish and the arena will turn black in the Darkness phase. Pink clones of the Astropath will crawl out of the ground and do different attacks. This clone comes halfway out of the ground and swipes at the player's feet.",
                "damage": 107.164,
                "stagger": 1,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Flying Clone: Double Arm Swing",
                "description": "The Astropath at times can split, resulting in a yellow clone entering the arena. This is the yellow clone's one and only attack, and is just a copy of the Astropath's double arm swing with less damage.",
                "damage": 107.164,
                "stagger": 1,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Rising Orbs",
                "description": "The Astropath will summon orbs that rise out of the ground, and after rising high enough they'll explode.",
                "damage": 148.839,
                "stagger": 1,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
        ]
    },
    "Pyromaniac": {
        "image": "/TFD/TFDImages/Bosses/Icon_VoidBattle_EpicMonster_Pyromaniac.png",
        "shortName": "Pyromaniac",
        "buffs": {},

        "skillCrit": 0.25,
        "gunCrit": 0.20,
        "note": "",

        "parts": [
            {"name": "Body","type": "Pierce","wpMod": 0},
            {"name": "Shoulder","type": "Burst","wpMod": 0.25},
            {"name": "Core","type": "Burst","wpMod": 0.375},
            {"name": "Balancer","type": "Crush","wpMod": 0.375},
            {"name": "Sensor","type": "Crush","wpMod": 0.50},
        ],

        "DEF": 286822,//407806,
        "Non-Attribute": 63631.39022,//was 63645
        "Fire": 180194.1,//was 180356
        "Electric": 104449.22,//was 104511 //TODO: another good example
        "Chill": 25410.25,//25424,
        "Toxic": 63634.45,//63645,

        "attacks": [
           {
                "name":"Orb: Projectiles",
                "description": "Bloat King summons up to two orbs that float around the room shooting projectiles of two different types. This is the damage of each individual standard projectile.",
                "damage": 35.721,
                "stagger": 1,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Orb: AOE Projectiles",
                "description": "Bloat King summons up to two orbs that float around the room shooting projectiles of two different types. This is the damage of the shock-explosive projectiles, which are are larger and indicated by a glowing sphere.",
                "damage": 223.258,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"King: Laser Quick/Start",
                "description": "After absorbing his orbs, Bloat King can do two types of a laser: a quick or a long version. Both lasers have the same start attack which is this attack, but the longer laser has another laser type that goes after this attack.",
                "damage": 151.815,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"King: Long Laser",
                "description": "After absorbing his orbs, Bloat King can do two types of a laser: a quick or a long version. This is the long laser that goes after the Starter laser attack.",
                "damage": 44.652,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "DOT",
                "frequency": 0.45,
                "duration": 3.15,
            },
            {
                "name":"Green Slime: Shock AOE",
                "description": "The bottom of the arena holds two types of enemies, the green and orange slimes. This is the damage of the Shock AOE from the Green Slimes.",
                "damage": 59.535,
                "stagger": 1,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "damageType": "Shock",
                "frequency": 0,
            },
            {
                "name":"Green Slime: Melee",
                "description": "The bottom of the arena holds two types of enemies, the green and orange slimes. This is the damage of the melee from the Green Slimes.",
                "damage": 119.071,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Orange Slime: Melee",
                "description": "The bottom of the arena holds two types of enemies, the green and orange slimes. This is the damage of the melee from the Orange Slimes, which do more damage than green but cannot shock you.",
                "damage": 119.071,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Overloaded",
                "description": "The Green Slimes in the bottom of the arena can apply Overloaded to you with their shock AOE attacks. Overloaded will do damage after 5 seconds, or every 5 seconds while the status is still applied.",
                "damage": 119.071,
                "stagger": 0,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "damageType": "Shock",
                "frequency": 0,
            },
        ]
    },
    "Swamp Walker": {
        "image": "/TFD/TFDImages/Bosses/Icon_VoidBattle_EpicMonster_SwampWalker.png",
        "shortName": "Swamp Walker",
        "buffs": {},
        "note": "",

        "skillCrit": 0.20,
        "gunCrit": 0.20,

        "parts": [
            {"name": "Body","type": "Pierce","wpMod": 0},
            {"name": "Shoulder","type": "Crush","wpMod": 0.25},
            {"name": "Core","type": "Pierce","wpMod": 0.25},
            {"name": "Helmet","type": "Crush","wpMod": 0.375},
            {"name": "Sensor","type": "Pierce","wpMod": 0.375},
        ],

        "DEF": 176323.5,//was 176346
        "Non-Attribute": 176323.5,//was 176346
        "Fire": 176323.6,//was 176346
        "Electric": 83140,//was 83182
        "Chill": 270651,//was 270956,
        "Toxic": 440765.5,//441218,

        "attacks": [
           {
                "name":"Impale",
                "description": "Bruin charges up his spear and leaps towards the player with a stabbing attack. If the player is at or less than 30% total HP after receiving this damage, Bruin will kill the player instantly, impaling them on his spear leaving them as a permanent object in the arena.",
                "damage": 279.072,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": true,
                "lethalCondition": "<=30%HP",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Double Swing 1",
                "description": "Bruin uses both his spears to perform a crossing swing attack. This is the first attack.",
                "damage": 119.071,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Double Swing 2",
                "description": "Bruin uses both his spears to perform a crossing swing attack. This is the second attack.",
                "damage": 119.071,
                "stagger": 1,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Basic 1 (Alt)",
                "description": "Basic attack 1: right stab. There are technically two different basic attack combos, and in one version this attack doesn't exist.",
                "damage": 119.071,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Basic 2 (Alt)",
                "description": "Basic attack 2: left stab. This attack only happens if Basic Attack 1 was initiated first.",
                "damage": 119.071,
                "stagger": 1,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Basic 2",
                "description": "Basic attack 2: left stab. This is the secondary variant that will be the first attack of the alternate basic combo. This version has more stagger than its counterpart.",
                "damage": 119.071,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Basic 3 Quick",
                "description": "Basic attack 3: right stab. This attack and the following attack are incredibly fast, and used in both basic attack combo variants.",
                "damage": 119.071,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Basic 4 Quick",
                "description": "Basic attack 4: left stab. This attack is incredibly fast, and used in both basic attack combo variants.",
                "damage": 119.071,
                "stagger": 1,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Quick Stab",
                "description": "This is a variant of Basic Attack 2, that can occur on its own outside of any combos.",
                "damage": 119.071,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Barrage: Throw",
                "description": "Bruin while in his Barrage phase, will throw spears. No matter when he throws them(individual or clusters), the spears will always do this amount of damage.",
                "damage": 74.419,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Barrage: Explosion",
                "description": "Bruin while in the latter half of his Barrage phase, will throw spears and recall them after they explode. This is the damage of the resulting explosions, per explosion. It is extremely easy to be hit by far more than one explosion at a time, making this quite deadly.",
                "damage": 178.606,
                "stagger": 1,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Barrage: Recall",
                "description": "Bruin while in the latter half of his Barrage phase, will throw spears and recall them after they explode. This is the damage of a spear if it hits you while heading back to him.",
                "damage": 74.419,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Kick",
                "description": "Bruin will kick the player to floor, always following up with an Evade Slash. This is the damage for the kick only.",
                "damage": 29.768,
                "stagger": 3,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Evade Slash",
                "description": "Bruin will swipe with his right spear before jumping away from the player.",
                "damage": 59.535,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Leap",
                "description": "Bruin leap across the arena to the player, doing a diving slam attack with both spears.",
                "damage": 223.258,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Balcony Jump (Up)",
                "description": "Bruin leap up to a balcony on either side of the arena to enter his Barrage phase. This is the damage from the AOE he emits when he makes the leap up.",
                "damage": 7.442,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Balcony Jump (Down)",
                "description": "When done with his Barrage phase, Bruin will leap down from the balcony with a slam attack.",
                "damage": 223.258,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Fae Archers",
                "description": "When Bruin enters his Barrage phase, Fae Archers will descend into the arena and start shooting arrows at both you and Bruin. This is the damage per arrow. Arrows have a chance to apply Bleed.",
                "damage": 89.303,
                "stagger": 1,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "damageType": "Bleed",
                "frequency": 0,
            },
        ]
    },
    "Obstructer": {
        "image": "/TFD/TFDImages/Bosses/Icon_VoidBattle_EpicMonster_Obstructer.png",
        "shortName": "Obstructer",
        "buffs": {},

        "skillCrit": 0.20,
        "gunCrit": 0.23,
        "note": "",

        "parts": [
            {"name": "Body","type": "Crush","wpMod": 0},
            {"name": "Shoulder","type": "Burst","wpMod": 0.25},
            {"name": "Core","type": "Burst","wpMod": 0.375},
            {"name": "Balancer","type": "Pierce","wpMod": 0.375},
            {"name": "Sensor","type": "Pierce","wpMod": 0.50},
        ],

        "DEF": 182074,//was 182156,
        "Non-Attribute": 182074,//was 182156
        "Fire": 182074,//was 182156,
        "Electric": 86233.8,//was 86251,
        "Chill": 279234.1,//was 279427,
        "Toxic": 453914.2,//was 454297,

        "attacks": [
           {
                "name":"Basic 1 Right",
                "description": "Cancer swings his left arm, to his right.",
                "damage": 178.606,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Basic 2 Left",
                "description": "Cancer swings his right arm, to his left.",
                "damage": 178.606,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Basic 3 Head Bonk",
                "description": "Cancer leans back and then slams his head on the ground, typically spawning Roots after.",
                "damage": 214.328,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Head Bonk",
                "description": "Separate from the Head Bonk in the basic attack combo, Cancer leans back and then slams his head on the ground, typically spawning Roots after.",
                "damage": 232.188,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Roots",
                "description": "Many of Cancer's attacks will create trails along the ground that after a moment will sprout roots, if those roots sprout while the player is nearby they will deal damage. If the player walks through them after they sprout, they slow the player.",
                "damage": 148.839,
                "stagger": 1,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Glitch Strike",
                "description": "Cancer will glitch out while heading towards the player, rapidly playing through several animations including a feint attack before launching an actual attack that is a copy of either of the first two hits in the basic attack combo.",
                "damage": 178.606,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Jump Shockwave",
                "description": " Cancer will jump and slam down on another section of the map, creating and AOE ripple effect that spreads to the ends of the arena.",
                "damage": 535.819,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Leap Swipe",
                "description": "If Cancer gets too far from the player, he'll leap across the arena to the player doing a swipe attack just before he lands nearby.",
                "damage": 142.885,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Root Tendril",
                "description": "Cancer while creating paths for roots to spawn, can sometimes spawn or relocate a Root Tendril that reaches into the sky, under the player. This is the damage of the Tendril emerging. Usually has a red circle indicator before sprouting underneath you.",
                "damage": 178.606,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
        ]
    },
    "Frost Walker": {
        "image": "/TFD/TFDImages/Bosses/Icon_VoidBattle_EpicMonster_FrostWalker.png",
        "shortName": "Frost Walker",
        "buffs": {},

        "skillCrit": 0.20,
        "gunCrit": 0.20,
        "note": "",

        "parts": [
            {"name": "Body","type": "Pierce","wpMod": 0},
            {"name": "Shoulder","type": "Burst","wpMod": 0.25},
            {"name": "Core","type": "Crush","wpMod": 0.25},
            {"name": "Helmet","type": "Burst","wpMod": 0.50},
            {"name": "Sensor","type": "Crush","wpMod": 0.375},
        ],

        "DEF": 188059,//was 188,058
        "Non-Attribute": 187862,//was 188058
        "Fire": 89381.5,//was 89384,
        "Electric": 187862,//was 188058,
        "Chill": 466944.5,//was 467512,
        "Toxic": 287831.1,//was 288011,

        "attacks": [
           {
                "name":"Crystal Barrage",
                "description": "The Forge spins up, and starts shooting a layered barrage of crystal projectiles out for several seconds. This is the damage of an individual projectile.",
                "damage": 178.606,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Sand Blasters",
                "description": "While spinning, the Forge emits three streams of sand, equidistant from the other streams. These streams continuous damage while it passes over you.",
                "damage": 151.815,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "DOT",
                "frequency": 0.303,
            },
            {
                "name":"Line Tracing (Drop)",
                "description": "The Forge summons wisps that fly above the arena. After creating a circling effect for several seconds, they drop energy onto the floor, that will then spread out and trace along the cracks in the ground. This is the damage if you get hit by the energy drop before it starts tracing.",
                "damage": 312.56,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Line Tracing (Trace)",
                "description": "The Forge summons wisps that fly above the arena. After creating a circling effect for several seconds, they drop energy onto the floor, that will then spread out and trace along the cracks in the ground. This is the damage of the trace that travels along the ground.",
                "damage": 178.606,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Arm Slam",
                "description": "The Forge rises up and creates and arm tendril that can attack the player. This is the damage of an overhead slam from the arm.",
                "damage": 178.606,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Arm Sweep",
                "description": "The Forge rises up and creates and arm tendril that can attack the player. This is the damage of a wide sweep attack from the arm.",
                "damage": 178.606,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Close/Open Slam",
                "description": "When finishing the Arm phase, the Forge will slam down shut before pulling back up to reveal the core has been exposed. This is the damage of the shockwave when closed before opening.",
                "damage": 535.819,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Pot Jr.",
                "description": "When finishing the Arm phase, the Forge will slam down shut before pulling back up to reveal the core has been exposed. When exposed, it creates three mini-pot enemies that seek out the player and explode.",
                "damage": 119.071,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Fire Ball",
                "description": "While in the Arm phase, the Forge will shoot out fireballs into the arena that explode and leave a fire puddle behind. This is the damage of the fireball explosion.",
                "damage": 17.861,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "damageType": "Fire",
                "frequency": 0,
            },
            {
                "name":"Fire Puddles",
                "description": "While in the Arm phase, the Forge will shoot out fireballs into the arena that explode and leave a fire puddle behind. This is the damage of the fire puddles left behind, separate from the Burning status effect, and is only dealt when standing within them.",
                "damage": 0.010,
                "stagger": 1,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "DOT",
                "damageType": "Fire",
                "frequency": 1,
            },
            {
                "name":"Burning",
                "description": "This is the damage of the Burning status effect applied by any of the fire-based attacks during the Arm phase.",
                "damage": 5.000,
                "stagger": 0,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "DOT",
                "damageType": "Fire",
                "frequency": 0.5,
            },
        ]
    },
    "Molten Fortress": {
        "image": "/TFD/TFDImages/Bosses/Icon_VoidBattle_EpicMonster_Moltenfortress_Info.png",
        "shortName": "Molten Fortress",
        "buffs": {},

        "skillCrit": 0.20,
        "gunCrit": 0.27,
        "note": "",

        "parts": [
            {"name": "Body","type": "Crush","wpMod": 0},
            {"name": "Armor","type": "Burst","wpMod": 0.25},
            {"name": "Core","type": "Pierce","wpMod": 0.25},
            {"name": "Helmet","type": "Burst","wpMod": 0.25},
            {"name": "Jaw","type": "Pierce","wpMod": 0.25},
            {"name": "Sensor","type": "Pierce","wpMod": 0.50},
        ],

        "DEF": 193880.7,//193880,//was 194054,
        "Non-Attribute": 193880.7,//was 194054
        "Fire": 480480.5,//was 481060,
        "Electric": 296419.5,//was 296709,
        "Chill": 92496.6,//was 92564,
        "Toxic": 193880.7,//was 194054,

        "attacks": [
           {
                "name":"Corruptor: Laser",
                "description": "Once at or below 50% HP, the Corruptor will charge up while at one of the three arena sections, before blasting that section with a laser over 2 seconds.",
                "damage": 113.117,
                "stagger": 3,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "DOT",
                "frequency": 0.5,
                "duration": 2
            },
            {
                "name":"Hand: Basic Attack",
                "description": "A hand detached from Many-Faces will do a quick spin leading their blade into the player.",
                "damage": 178.606,
                "stagger": 1,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Hand: Lightning Orb",
                "description": "A blue hand detached from Many-Faces will do a quick spin launching a lightning orb at the player that can apply Overloaded.",
                "damage": 178.606,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "damageType": "Shock",
                "frequency": 0,
            },
            {
                "name":"Hand: Lightning AOE",
                "description": "A blue hand detached from Many-Faces will stab the ground with its sword, releasing three lightning pulses over 3 seconds.",
                "damage": 169.676,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "DOT",
                "damageType": "Shock",
                "frequency": 1,
                "duration": 3,
            },
            {
                "name":"Faces: Bottom Row Spin",
                "description": "Many-Faces will bend its knees slightly and the bottom row of its arms will do an extremely fast spin with a wide range.",
                "damage": 169.676,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Faces: Whirlwind",
                "description": "Many-Faces will rotate both rows of arms in opposite directions and walk towards the player. Seemingly, standing between its legs will completely avoid this damage.",
                "damage": 169.676,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Faces: Stomp",
                "description": "Many-Faces will raise one of its legs and stomp the ground in an AOE.",
                "damage": 169.676,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Faces: Leap",
                "description": "Many-Faces will leap towards and slam the ground near the player if they get far enough away.",
                "damage": 254.514,
                "stagger": 3,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Overloaded Status",
                "description": "The Overloaded status that can be applied by Blue Hand Lightning Orb attacks. The status lasts for 5 seconds, and then deals this damage once. After which, the effect goes away.",
                "damage": 178.606,
                "stagger": 1,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "damageType": "Shock",
                "frequency": 0,
            },
        ]
    },
    "Gluttony": {
        "image": "/TFD/TFDImages/Bosses/Icon_VoidBattle_EpicMonster_Gluttony.png",
        "shortName": "Gluttony",
        "buffs": {},

        "skillCrit": 0.60,
        "gunCrit": 0.30,
        "note": "",

        "parts": [
            {"name": "Body","type": "Crush","wpMod": 0},
            {"name": "Shoulder","type": "Pierce","wpMod": 0.25},
            {"name": "Core","type": "Pierce","wpMod": 0.25},
            {"name": "Balancer","type": "Burst","wpMod": 0.25},
            {"name": "Sensor","type": "Burst","wpMod": 0.50},
        ],

        "DEF": 193880.7,//194054,
        "Non-Attribute": 193880.7,//was 194054
        "Fire": 92496.6,//was 92564, //TODO: this is another great example on why decimals are used
        "Electric": 193880.7,//was 194054,
        "Chill": 480480.5,//was 481060,
        "Toxic": 296419.5,//was 296709,

        "attacks": [
           {
                "name":"Laser Swipe Right",
                "description": "The Eye will swipe a red laser quickly across the arena from its left to its right.",
                "damage": 178.606,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Laser Swipe Left",
                "description": "The Eye will swipe a red laser quickly across the arena from its right to its left, always follows the Laser Swipe Right attack.",
                "damage": 178.606,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Blue Barrage",
                "description": "The Eye will glow blue and shoot out a barrage of energy projectiles. This is the damage per projectile, and it hits 49 times.",
                "damage": 178.606,
                "stagger": 1,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "DOT",
                "frequency": 0.2,
                "duration": 9.8,
            },
            {
                "name":"Purple Laser",
                "description": "The Eye will glow purple and emit a continuous purple beam that traces lines within the arena. The lines it draws turn into mines that explode. This is the damage of the beam itself, not the mines.",
                "damage": 89.303,
                "stagger": 1,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "DOT",
                "frequency": 0.3,
            },
            {
                "name":"Purple Laser (Mines)",
                "description": "The Eye will glow purple and emit a continuous purple beam that traces lines within the arena. The lines it draws turn into mines that explode. This is the damage of mines, not the beam.",
                "damage": 89.303,
                "stagger": 1,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": true,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "DOT",
                "frequency": 0.3,
            },
            {
                "name":"Disco Lasers",
                "description": "The Eye will raise into the sky while transforming the arena into a layered descending pit. Once raised, the eye will glow blue and emit three separate beams that will track players around the arena. This is the damage of the beam if it hits the player, but it's remarkably hard to be hit by it as the beam seems to have a physical geometry outside of the beam's visual indicator that pushes players away from it before it can hit them. I had to run into them in order to get hit.",
                "damage": 267.91,
                "stagger": 1,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "DOT",
                "frequency": 0.7,
            },
            {
                "name":"Carousel: Tri-Laser",
                "description": "The Eye will raise into the sky while transforming most of the arena into a pit. The Eye will then lower to be level with the top layer of the pit, and shoot out three red lasers that are evenly split in their directions, and begin to rotate. This is the damage if a laser hits you on the top level.",
                "damage": 357.213,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Carousel: Pit-Fall",
                "description": "The Eye will raise into the sky while transforming most of the arena into a pit. The Eye will then lower to be level with the top layer of the pit, and shoot out three red lasers that are evenly split in their directions, and begin to rotate. This is the fall damage if you are in the middle of the arena when it collapses, dealing 50% of your max HP.",
                "damage": 0,
                "stagger": 0,
                "hpBased": true,
                "hpPercent": 50,
                "drBypass": true,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "%HP",
                "damageType": "Fall",
                "frequency": 0,
            },
            {
                "name":"Carousel: Pit Tiles",
                "description": "The Eye will raise into the sky while transforming most of the arena into a pit. The Eye will then lower to be level with the top layer of the pit, and shoot out three red lasers that are evenly split in their directions, and begin to rotate. This is the fall damage the tiles in the bottom of the pit will do to you if you stand over them while they are glowing, dealing 50% of your max HP..",
                "damage": 0,
                "stagger": 2,
                "hpBased": true,
                "hpPercent": 50,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "%HP",
                "frequency": 0,
            },
            {
                "name":"Drone: Projectiles",
                "description": "The Eye can summon Drone minions throughout the fight. This is the damage the drones deal to you with their projectile attacks.",
                "damage": 89.303,
                "stagger": 1,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "damageType": "Shock",
                "frequency": 0,
            },
            {
                "name":"Drone: Fallen AOE",
                "description": "If the Eye's drone summons live long enough, the Eye will send out a blue shockwave that doesn't damage the player, but causes all drones to fall to the floor and emit a damaging blue sphere AOE, where every hit deal 5% of the player's maximum HP.",
                "damage": 0,
                "stagger": 1,
                "hpBased": true,
                "hpPercent": 5,
                "drBypass": true,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "%HP",
                "frequency": 0.5,
                "duration": 8.5
            },
        ]
    },
    "Death Stalker": {
        "image": "/TFD/TFDImages/Bosses/Icon_VoidBattle_EpicMonster_Deathstalker.png",
        "shortName": "Death Stalker",
        "buffs": {},

        "skillCrit": 0.70,
        "gunCrit": 0.30,
        "note": "",

        "parts": [
            {"name": "Body","type": "Pierce","wpMod": 0},
            {"name": "Balancer","type": "Crush","wpMod": 0.25},
            {"name": "Core","type": "Burst","wpMod": 0.375},
            {"name": "Sensor","type": "Burst","wpMod": 0.375},
            {"name": "Back","type": "Crush","wpMod": 0.50},
        ],

        "DEF": 193880.7,
        "Non-Attribute": 193880.7,
        "Fire": 193880.7,
        "Electric": 92496.6,
        "Chill": 296419.5,
        "Toxic": 480480.5,

        "attacks": [
           {
                "name":"Laser Swipe Right",
                "description": "The Eye will swipe a red laser quickly across the arena from its left to its right.",
                "damage": 178.606,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Laser Swipe Left",
                "description": "The Eye will swipe a red laser quickly across the arena from its right to its left, always follows the Laser Swipe Right attack.",
                "damage": 178.606,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Blue Barrage",
                "description": "The Eye will glow blue and shoot out a barrage of energy projectiles. This is the damage per projectile, and it hits 49 times.",
                "damage": 178.606,
                "stagger": 1,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "DOT",
                "frequency": 0.2,
                "duration": 9.8,
            },
            {
                "name":"Purple Laser",
                "description": "The Eye will glow purple and emit a continuous purple beam that traces lines within the arena. The lines it draws turn into mines that explode. This is the damage of the beam itself, not the mines.",
                "damage": 89.303,
                "stagger": 1,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "DOT",
                "frequency": 0.3,
            },
            {
                "name":"Purple Laser (Mines)",
                "description": "The Eye will glow purple and emit a continuous purple beam that traces lines within the arena. The lines it draws turn into mines that explode. This is the damage of mines, not the beam.",
                "damage": 89.303,
                "stagger": 1,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": true,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "DOT",
                "frequency": 0.3,
            },
            {
                "name":"Disco Lasers",
                "description": "The Eye will raise into the sky while transforming the arena into a layered descending pit. Once raised, the eye will glow blue and emit three separate beams that will track players around the arena. This is the damage of the beam if it hits the player, but it's remarkably hard to be hit by it as the beam seems to have a physical geometry outside of the beam's visual indicator that pushes players away from it before it can hit them. I had to run into them in order to get hit.",
                "damage": 267.91,
                "stagger": 1,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "DOT",
                "frequency": 0.7,
            },
            {
                "name":"Carousel: Tri-Laser",
                "description": "The Eye will raise into the sky while transforming most of the arena into a pit. The Eye will then lower to be level with the top layer of the pit, and shoot out three red lasers that are evenly split in their directions, and begin to rotate. This is the damage if a laser hits you on the top level.",
                "damage": 357.213,
                "stagger": 2,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Carousel: Pit-Fall",
                "description": "The Eye will raise into the sky while transforming most of the arena into a pit. The Eye will then lower to be level with the top layer of the pit, and shoot out three red lasers that are evenly split in their directions, and begin to rotate. This is the fall damage if you are in the middle of the arena when it collapses, dealing 50% of your max HP.",
                "damage": 0,
                "stagger": 0,
                "hpBased": true,
                "hpPercent": 50,
                "drBypass": true,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "%HP",
                "damageType": "Fall",
                "frequency": 0,
            },
            {
                "name":"Carousel: Pit Tiles",
                "description": "The Eye will raise into the sky while transforming most of the arena into a pit. The Eye will then lower to be level with the top layer of the pit, and shoot out three red lasers that are evenly split in their directions, and begin to rotate. This is the fall damage the tiles in the bottom of the pit will do to you if you stand over them while they are glowing, dealing 50% of your max HP..",
                "damage": 0,
                "stagger": 2,
                "hpBased": true,
                "hpPercent": 50,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "%HP",
                "frequency": 0,
            },
            {
                "name":"Drone: Projectiles",
                "description": "The Eye can summon Drone minions throughout the fight. This is the damage the drones deal to you with their projectile attacks.",
                "damage": 89.303,
                "stagger": 1,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "damageType": "Shock",
                "frequency": 0,
            },
            {
                "name":"Drone: Fallen AOE",
                "description": "If the Eye's drone summons live long enough, the Eye will send out a blue shockwave that doesn't damage the player, but causes all drones to fall to the floor and emit a damaging blue sphere AOE, where every hit deal 5% of the player's maximum HP.",
                "damage": 0,
                "stagger": 1,
                "hpBased": true,
                "hpPercent": 5,
                "drBypass": true,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "%HP",
                "frequency": 0.5,
                "duration": 8.5
            },
        ]
    },

    // "LvL 1 Vulgus": {
    //     "image": "/TFD/TFDImages/Bosses/Icon_VoidBattle_EpicMonster_Devourer.png",
    //     "shortName": "NONE",
    //     "buffs": {},

    //     "skillCrit": 0,
    //     "gunCrit": 0,
    //     "note": "",

    //     "parts": [{"name": "Body","type": "Burst","wpMod": 0},],

    //     "DEF": 0,
    //     "Non-Attribute": 0,
    //     "Fire": 0,
    //     "Electric": 0,
    //     "Chill": 0,
    //     "Toxic": 0,
    // },

}