//Just copy pasted from my work on the Remnant 2 section of my site, this will have non-relevant parts in the code, just leaving it there for now

const Vulgus = {
    "None (True Damage)": {
        "name": "None (True Damage)",
        "realName": "None (True Damage)",
        "displayName": "None (True Damage)",
        "key": "None (True Damage)",
        "difficulty": "Normal",
        "levelKeys": {
            "1": {
                "lvl": 0,
                "lvlStats": {
                "HP": 0,
                "Shield": 0,
                "DEF": 0,
                "Non-Attribute": 0,
                "Fire": 0,
                "Chill": 0,
                "Electric": 0,
                "Toxic": 0,
                "ATK": 0,
                "Fire ATK": 0,
                "HP Recovery Interval": 0,
                "HP Recovery": 0,
                "HP Recovery In Combat": 0,
                "Shield Recovery Interval": 0,
                "Shield Recovery": 0,
                "Shield Recovery In Combat": 0,
                "Max Stagger HP and Rate": 0,
                "Max Stagger HP Rate": 0,
                "Max Stagger Rate": 0,
                "Stagger Decrease Rate": 0,
                "Stagger Decrease Delay": 0,
                "Time Limit": 0,
                "Max Frenzy Rate": 0,
                "Frenzy Damage Rate": 0,
                "Frenzy Decrease Delay": 0,
                "Frenzy Decrease Rate": 0,
                "Frenzy Duration": 0,
                "Colossus Level": 0
                }
            },
            "2": {
                "lvl": 0,
                "lvlStats": {
                "HP": 0,
                "Shield": 0,
                "DEF": 0,
                "Non-Attribute": 0,
                "Fire": 0,
                "Chill": 0,
                "Electric": 0,
                "Toxic": 0,
                "ATK": 0,
                "Fire ATK": 0,
                "HP Recovery Interval": 0,
                "HP Recovery": 0,
                "HP Recovery In Combat": 0,
                "Shield Recovery Interval": 0,
                "Shield Recovery": 0,
                "Shield Recovery In Combat": 0,
                "Max Stagger HP and Rate": 0,
                "Max Stagger HP Rate": 0,
                "Max Stagger Rate": 0,
                "Stagger Decrease Rate": 0,
                "Stagger Decrease Delay": 0,
                "Time Limit": 0,
                "Max Frenzy Rate": 0,
                "Frenzy Damage Rate": 0,
                "Frenzy Decrease Delay": 0,
                "Frenzy Decrease Rate": 0,
                "Frenzy Duration": 0,
                "Colossus Level": 0
                }
            },
            "3": {
                "lvl": 0,
                "lvlStats": {
                "HP": 0,
                "Shield": 0,
                "DEF": 0,
                "Non-Attribute": 0,
                "Fire": 0,
                "Chill": 0,
                "Electric": 0,
                "Toxic": 0,
                "ATK": 0,
                "Fire ATK": 0,
                "HP Recovery Interval": 0,
                "HP Recovery": 0,
                "HP Recovery In Combat": 0,
                "Shield Recovery Interval": 0,
                "Shield Recovery": 0,
                "Shield Recovery In Combat": 0,
                "Max Stagger HP and Rate": 0,
                "Max Stagger HP Rate": 0,
                "Max Stagger Rate": 0,
                "Stagger Decrease Rate": 0,
                "Stagger Decrease Delay": 0,
                "Time Limit": 0,
                "Max Frenzy Rate": 0,
                "Frenzy Damage Rate": 0,
                "Frenzy Decrease Delay": 0,
                "Frenzy Decrease Rate": 0,
                "Frenzy Duration": 0,
                "Colossus Level": 0
                }
            },
            "4": {
                "lvl": 0,
                "lvlStats": {
                "HP": 0,
                "Shield": 0,
                "DEF": 0,
                "Non-Attribute": 0,
                "Fire": 0,
                "Chill": 0,
                "Electric": 0,
                "Toxic": 0,
                "ATK": 0,
                "Fire ATK": 0,
                "HP Recovery Interval": 0,
                "HP Recovery": 0,
                "HP Recovery In Combat": 0,
                "Shield Recovery Interval": 0,
                "Shield Recovery": 0,
                "Shield Recovery In Combat": 0,
                "Max Stagger HP and Rate": 0,
                "Max Stagger HP Rate": 0,
                "Max Stagger Rate": 0,
                "Stagger Decrease Rate": 0,
                "Stagger Decrease Delay": 0,
                "Time Limit": 0,
                "Max Frenzy Rate": 0,
                "Frenzy Damage Rate": 0,
                "Frenzy Decrease Delay": 0,
                "Frenzy Decrease Rate": 0,
                "Frenzy Duration": 0,
                "Colossus Level": 0
                }
            }
        },
        "minimumTeam": 1,
        "attackType": "",
        "bigIcon": "que",
        "smallIcon": "que",
        "stats": {
            "Movespeed": 0,
            "Aim Movespeed": 0,
            "Berserk Movespeed": 0,
            "Movement Destruction": 0,
            "Crit Chance": 0,
            "Crit Damage": 0,
            "Firearm Crit Resist": 0,
            "Skill Crit Resist": 0,
            "Penetration Resist": 0,
            "Max Rage Rate": 0,
            "Penetration": 0
        },
        "weaknessKeys": {
            "Body (None)": {"name": "Body","type": "","wpMod": 0},
                
            "Body (Crush)": {"name": "Body","type": "Crush","wpMod": 0},
            "Body (Pierce)": {"name": "Body","type": "Pierce","wpMod": 0},
            "Body (Burst)": {"name": "Body","type": "Burst","wpMod": 0},

            "Generic .25 (Crush)": {"name": "N/A","type": "Crush","wpMod": 0.25},
            "Generic .25 (Pierce)": {"name": "N/A","type": "Pierce","wpMod": 0.25},
            "Generic .25 (Burst)": {"name": "N/A","type": "Burst","wpMod": 0.25},

            "Generic .375 (Crush)": {"name": "N/A","type": "Crush","wpMod": 0.375},
            "Generic .375 (Pierce)": {"name": "N/A","type": "Pierce","wpMod": 0.375},
            "Generic .375 (Burst)": {"name": "N/A","type": "Burst","wpMod": 0.375},

            "Generic .50 (Crush)": {"name": "N/A","type": "Crush","wpMod": 0.50},
            "Generic .50 (Pierce)": {"name": "N/A","type": "Pierce","wpMod": 0.50},
            "Generic .50 (Burst)": {"name": "N/A","type": "Burst","wpMod": 0.50},
        },
        "weaknessKeyName": "",
        "enemyType": "Colossus"
    },

    "LvL 1 Order of Truth": {
        "name": "LvL 1 Order of Truth",
        "realName": "LvL 1 Order of Truth",
        "displayName": "LvL 1 Order of Truth",
        "key": "LvL 1 Order of Truth",
        "difficulty": "Normal",
        "levelKeys": {
        "1": {
            "lvl": 0,
            "lvlStats": {
            "HP": 0,
            "Shield": 0,
            "DEF": 0,
            "Non-Attribute": 0,
            "Fire": 167,
            "Chill": 167,
            "Electric": 0,
            "Toxic": 250,
            "ATK": 0,
            "Fire ATK": 0,
            "HP Recovery Interval": 0,
            "HP Recovery": 0,
            "HP Recovery In Combat": 0,
            "Shield Recovery Interval": 0,
            "Shield Recovery": 0,
            "Shield Recovery In Combat": 0,
            "Max Stagger HP and Rate": 0,
            "Max Stagger HP Rate": 0,
            "Max Stagger Rate": 0,
            "Stagger Decrease Rate": 0,
            "Stagger Decrease Delay": 0,
            "Time Limit": 0,
            "Max Frenzy Rate": 0,
            "Frenzy Damage Rate": 0,
            "Frenzy Decrease Delay": 0,
            "Frenzy Decrease Rate": 0,
            "Frenzy Duration": 0,
            "Colossus Level": 0
            }
        },
        "2": {
            "lvl": 0,
            "lvlStats": {
            "HP": 0,
            "Shield": 0,
            "DEF": 0,
            "Non-Attribute": 0,
            "Fire": 167,
            "Chill": 167,
            "Electric": 0,
            "Toxic": 250,
            "ATK": 0,
            "Fire ATK": 0,
            "HP Recovery Interval": 0,
            "HP Recovery": 0,
            "HP Recovery In Combat": 0,
            "Shield Recovery Interval": 0,
            "Shield Recovery": 0,
            "Shield Recovery In Combat": 0,
            "Max Stagger HP and Rate": 0,
            "Max Stagger HP Rate": 0,
            "Max Stagger Rate": 0,
            "Stagger Decrease Rate": 0,
            "Stagger Decrease Delay": 0,
            "Time Limit": 0,
            "Max Frenzy Rate": 0,
            "Frenzy Damage Rate": 0,
            "Frenzy Decrease Delay": 0,
            "Frenzy Decrease Rate": 0,
            "Frenzy Duration": 0,
            "Colossus Level": 0
            }
        },
        "3": {
            "lvl": 0,
            "lvlStats": {
            "HP": 0,
            "Shield": 0,
            "DEF": 0,
            "Non-Attribute": 0,
            "Fire": 167,
            "Chill": 167,
            "Electric": 0,
            "Toxic": 250,
            "ATK": 0,
            "Fire ATK": 0,
            "HP Recovery Interval": 0,
            "HP Recovery": 0,
            "HP Recovery In Combat": 0,
            "Shield Recovery Interval": 0,
            "Shield Recovery": 0,
            "Shield Recovery In Combat": 0,
            "Max Stagger HP and Rate": 0,
            "Max Stagger HP Rate": 0,
            "Max Stagger Rate": 0,
            "Stagger Decrease Rate": 0,
            "Stagger Decrease Delay": 0,
            "Time Limit": 0,
            "Max Frenzy Rate": 0,
            "Frenzy Damage Rate": 0,
            "Frenzy Decrease Delay": 0,
            "Frenzy Decrease Rate": 0,
            "Frenzy Duration": 0,
            "Colossus Level": 0
            }
        },
        "4": {
            "lvl": 0,
            "lvlStats": {
            "HP": 0,
            "Shield": 0,
            "DEF": 0,
            "Non-Attribute": 0,
            "Fire": 167,
            "Chill": 167,
            "Electric": 0,
            "Toxic": 250,
            "ATK": 0,
            "Fire ATK": 0,
            "HP Recovery Interval": 0,
            "HP Recovery": 0,
            "HP Recovery In Combat": 0,
            "Shield Recovery Interval": 0,
            "Shield Recovery": 0,
            "Shield Recovery In Combat": 0,
            "Max Stagger HP and Rate": 0,
            "Max Stagger HP Rate": 0,
            "Max Stagger Rate": 0,
            "Stagger Decrease Rate": 0,
            "Stagger Decrease Delay": 0,
            "Time Limit": 0,
            "Max Frenzy Rate": 0,
            "Frenzy Damage Rate": 0,
            "Frenzy Decrease Delay": 0,
            "Frenzy Decrease Rate": 0,
            "Frenzy Duration": 0,
            "Colossus Level": 0
            }
        }
        },
        "minimumTeam": 1,
        "attackType": "",
        "bigIcon": "que",
        "smallIcon": "que",
        "stats": {
            "Movespeed": 0,
            "Aim Movespeed": 0,
            "Berserk Movespeed": 0,
            "Movement Destruction": 0,
            "Crit Chance": 0,
            "Crit Damage": 0,
            "Firearm Crit Resist": 5,
            "Skill Crit Resist": 5,
            "Penetration Resist": 0,
            "Max Rage Rate": 0,
            "Penetration": 0
        },
        "weaknessKeys": {
            "Body (None)": {"name": "Body","type": "Burst","wpMod": 0},
            "Generic .50 (Burst)": {"name": "N/A","type": "Burst","wpMod": 0.50},
        },
        "weaknessKeyName": "",
        "enemyType": "Vulgus"
    },
    "LvL 1 Legion of Immortality": {
        "name": "LvL 1 Legion of Immortality",
        "realName": "LvL 1 Legion of Immortality",
        "displayName": "LvL 1 Legion of Immortality",
        "key": "LvL 1 Legion of Immortality",
        "difficulty": "Normal",
        "levelKeys": {
            "1": {
                "lvl": 0,
                "lvlStats": {
                "HP": 0,
                "Shield": 0,
                "DEF": 202,
                "Non-Attribute": 202,
                "Fire": 135,
                "Chill": 135,
                "Electric": 202,
                "Toxic": 101,
                "ATK": 0,
                "Fire ATK": 0,
                "HP Recovery Interval": 0,
                "HP Recovery": 0,
                "HP Recovery In Combat": 0,
                "Shield Recovery Interval": 0,
                "Shield Recovery": 0,
                "Shield Recovery In Combat": 0,
                "Max Stagger HP and Rate": 0,
                "Max Stagger HP Rate": 0,
                "Max Stagger Rate": 0,
                "Stagger Decrease Rate": 0,
                "Stagger Decrease Delay": 0,
                "Time Limit": 0,
                "Max Frenzy Rate": 0,
                "Frenzy Damage Rate": 0,
                "Frenzy Decrease Delay": 0,
                "Frenzy Decrease Rate": 0,
                "Frenzy Duration": 0,
                "Colossus Level": 0
                }
            },
            "2": {
                "lvl": 0,
                "lvlStats": {
                "HP": 0,
                "Shield": 0,
                "DEF": 202,
                "Non-Attribute": 202,
                "Fire": 135,
                "Chill": 135,
                "Electric": 202,
                "Toxic": 101,
                "ATK": 0,
                "Fire ATK": 0,
                "HP Recovery Interval": 0,
                "HP Recovery": 0,
                "HP Recovery In Combat": 0,
                "Shield Recovery Interval": 0,
                "Shield Recovery": 0,
                "Shield Recovery In Combat": 0,
                "Max Stagger HP and Rate": 0,
                "Max Stagger HP Rate": 0,
                "Max Stagger Rate": 0,
                "Stagger Decrease Rate": 0,
                "Stagger Decrease Delay": 0,
                "Time Limit": 0,
                "Max Frenzy Rate": 0,
                "Frenzy Damage Rate": 0,
                "Frenzy Decrease Delay": 0,
                "Frenzy Decrease Rate": 0,
                "Frenzy Duration": 0,
                "Colossus Level": 0
                }
            },
            "3": {
                "lvl": 0,
                "lvlStats": {
                "HP": 0,
                "Shield": 0,
                "DEF": 202,
                "Non-Attribute": 202,
                "Fire": 135,
                "Chill": 135,
                "Electric": 202,
                "Toxic": 101,
                "ATK": 0,
                "Fire ATK": 0,
                "HP Recovery Interval": 0,
                "HP Recovery": 0,
                "HP Recovery In Combat": 0,
                "Shield Recovery Interval": 0,
                "Shield Recovery": 0,
                "Shield Recovery In Combat": 0,
                "Max Stagger HP and Rate": 0,
                "Max Stagger HP Rate": 0,
                "Max Stagger Rate": 0,
                "Stagger Decrease Rate": 0,
                "Stagger Decrease Delay": 0,
                "Time Limit": 0,
                "Max Frenzy Rate": 0,
                "Frenzy Damage Rate": 0,
                "Frenzy Decrease Delay": 0,
                "Frenzy Decrease Rate": 0,
                "Frenzy Duration": 0,
                "Colossus Level": 0
                }
            },
            "4": {
                "lvl": 0,
                "lvlStats": {
                "HP": 0,
                "Shield": 0,
                "DEF": 202,
                "Non-Attribute": 202,
                "Fire": 135,
                "Chill": 135,
                "Electric": 202,
                "Toxic": 101,
                "ATK": 0,
                "Fire ATK": 0,
                "HP Recovery Interval": 0,
                "HP Recovery": 0,
                "HP Recovery In Combat": 0,
                "Shield Recovery Interval": 0,
                "Shield Recovery": 0,
                "Shield Recovery In Combat": 0,
                "Max Stagger HP and Rate": 0,
                "Max Stagger HP Rate": 0,
                "Max Stagger Rate": 0,
                "Stagger Decrease Rate": 0,
                "Stagger Decrease Delay": 0,
                "Time Limit": 0,
                "Max Frenzy Rate": 0,
                "Frenzy Damage Rate": 0,
                "Frenzy Decrease Delay": 0,
                "Frenzy Decrease Rate": 0,
                "Frenzy Duration": 0,
                "Colossus Level": 0
                }
            }
        },
        "minimumTeam": 1,
        "attackType": "",
        "bigIcon": "que",
        "smallIcon": "que",
        "stats": {
            "Movespeed": 0,
            "Aim Movespeed": 0,
            "Berserk Movespeed": 0,
            "Movement Destruction": 0,
            "Crit Chance": 0,
            "Crit Damage": 0,
            "Firearm Crit Resist": 5,
            "Skill Crit Resist": 5,
            "Penetration Resist": 0,
            "Max Rage Rate": 0,
            "Penetration": 0
        },
        "weaknessKeys": {
            "Body (None)": {"name": "Body","type": "Crush","wpMod": 0},
            "Generic .50 (Crush)": {"name": "N/A","type": "Crush","wpMod": 0.50},
        },
        "weaknessKeyName": "",
        "enemyType": "Vulgus"
    },
    "LvL 1 Legion of Darkness": {
        "name": "LvL 1 Legion of Darkness",
        "realName": "LvL 1 Legion of Darkness",
        "displayName": "LvL 1 Legion of Darkness",
        "key": "LvL 1 Legion of Darkness",
        "difficulty": "Normal",
        "levelKeys": {
            "1": {
                "lvl": 0,
                "lvlStats": {
                "HP": 0,
                "Shield": 0,
                "DEF": 288,
                "Non-Attribute": 288,
                "Fire": 288,
                "Chill": 144,
                "Electric": 192,
                "Toxic": 192,
                "ATK": 0,
                "Fire ATK": 0,
                "HP Recovery Interval": 0,
                "HP Recovery": 0,
                "HP Recovery In Combat": 0,
                "Shield Recovery Interval": 0,
                "Shield Recovery": 0,
                "Shield Recovery In Combat": 0,
                "Max Stagger HP and Rate": 0,
                "Max Stagger HP Rate": 0,
                "Max Stagger Rate": 0,
                "Stagger Decrease Rate": 0,
                "Stagger Decrease Delay": 0,
                "Time Limit": 0,
                "Max Frenzy Rate": 0,
                "Frenzy Damage Rate": 0,
                "Frenzy Decrease Delay": 0,
                "Frenzy Decrease Rate": 0,
                "Frenzy Duration": 0,
                "Colossus Level": 0
                }
            },
            "2": {
                "lvl": 0,
                "lvlStats": {
                "HP": 0,
                "Shield": 0,
                "DEF": 288,
                "Non-Attribute": 288,
                "Fire": 288,
                "Chill": 144,
                "Electric": 192,
                "Toxic": 192,
                "ATK": 0,
                "Fire ATK": 0,
                "HP Recovery Interval": 0,
                "HP Recovery": 0,
                "HP Recovery In Combat": 0,
                "Shield Recovery Interval": 0,
                "Shield Recovery": 0,
                "Shield Recovery In Combat": 0,
                "Max Stagger HP and Rate": 0,
                "Max Stagger HP Rate": 0,
                "Max Stagger Rate": 0,
                "Stagger Decrease Rate": 0,
                "Stagger Decrease Delay": 0,
                "Time Limit": 0,
                "Max Frenzy Rate": 0,
                "Frenzy Damage Rate": 0,
                "Frenzy Decrease Delay": 0,
                "Frenzy Decrease Rate": 0,
                "Frenzy Duration": 0,
                "Colossus Level": 0
                }
            },
            "3": {
                "lvl": 0,
                "lvlStats": {
                "HP": 0,
                "Shield": 0,
                "DEF": 288,
                "Non-Attribute": 288,
                "Fire": 288,
                "Chill": 144,
                "Electric": 192,
                "Toxic": 192,
                "ATK": 0,
                "Fire ATK": 0,
                "HP Recovery Interval": 0,
                "HP Recovery": 0,
                "HP Recovery In Combat": 0,
                "Shield Recovery Interval": 0,
                "Shield Recovery": 0,
                "Shield Recovery In Combat": 0,
                "Max Stagger HP and Rate": 0,
                "Max Stagger HP Rate": 0,
                "Max Stagger Rate": 0,
                "Stagger Decrease Rate": 0,
                "Stagger Decrease Delay": 0,
                "Time Limit": 0,
                "Max Frenzy Rate": 0,
                "Frenzy Damage Rate": 0,
                "Frenzy Decrease Delay": 0,
                "Frenzy Decrease Rate": 0,
                "Frenzy Duration": 0,
                "Colossus Level": 0
                }
            },
            "4": {
                "lvl": 0,
                "lvlStats": {
                "HP": 0,
                "Shield": 0,
                "DEF": 288,
                "Non-Attribute": 288,
                "Fire": 288,
                "Chill": 144,
                "Electric": 192,
                "Toxic": 192,
                "ATK": 0,
                "Fire ATK": 0,
                "HP Recovery Interval": 0,
                "HP Recovery": 0,
                "HP Recovery In Combat": 0,
                "Shield Recovery Interval": 0,
                "Shield Recovery": 0,
                "Shield Recovery In Combat": 0,
                "Max Stagger HP and Rate": 0,
                "Max Stagger HP Rate": 0,
                "Max Stagger Rate": 0,
                "Stagger Decrease Rate": 0,
                "Stagger Decrease Delay": 0,
                "Time Limit": 0,
                "Max Frenzy Rate": 0,
                "Frenzy Damage Rate": 0,
                "Frenzy Decrease Delay": 0,
                "Frenzy Decrease Rate": 0,
                "Frenzy Duration": 0,
                "Colossus Level": 0
                }
            }
        },
        "minimumTeam": 1,
        "attackType": "",
        "bigIcon": "que",
        "smallIcon": "que",
        "stats": {
            "Movespeed": 0,
            "Aim Movespeed": 0,
            "Berserk Movespeed": 0,
            "Movement Destruction": 0,
            "Crit Chance": 0,
            "Crit Damage": 0,
            "Firearm Crit Resist": 5,
            "Skill Crit Resist": 5,
            "Penetration Resist": 0,
            "Max Rage Rate": 0,
            "Penetration": 0
        },
        "weaknessKeys": {
            "Body (None)": {"name": "Body","type": "Pierce","wpMod": 0},
            "Generic .50 (Pierce)": {"name": "N/A","type": "Pierce","wpMod": 0.50},
        },
        "weaknessKeyName": "",
        "enemyType": "Vulgus"
    },
}