let globalRecords = {
    "URLImportCompleted": false,
    "reactor": {
        "currentAttribute": "Chill",
        "currentAttributeID": "reactorChill",
        "currentType": "Singular",
        "currentTypeID": "reactorSingular",
        "subRoll1": "Singular Power Boost",
        "subRoll1Value": 0,
        "subRoll2": "Skill ATK - Colossus",
        "subRoll2Value": 0,
        "currentAmmoType": "Impact",
        "currentAmmoTypeID": "reactorImpact",
        "weaponMatched": true,
    },
    "components": {
        "auxiliary": "Slayer",
        "auxiliarySub1": "",
        "auxiliarySub2": "",
        "auxiliarySub1Value": 0,
        "auxiliarySub2Value": 0,
        "sensor": "Slayer",
        "sensorSub1": "",
        "sensorSub2": "",
        "sensorSub1Value": 0,
        "sensorSub2Value": 0,
        "memory": "Slayer",
        "memorySub1": "",
        "memorySub2": "",
        "memorySub1Value": 0,
        "memorySub2Value": 0,
        "processor": "Slayer",
        "processorSub1": "",
        "processorSub2": "",
        "processorSub1Value": 0,
        "processorSub2Value": 0
    },
    "character": {
        "currentCharacter": "Hailey",
        "mods": ["","","","","","","","","","","",""],
        "abilityArray": [0,0,0,0,0],
        "currentAbilityBreakdown": 4,
        "currentAbilityBreakdownID": "damageAbilityIcon4",
    },
    "weapon": {
        "currentWeapon": "Afterglow Sword",
        "currentWeaponType": "Sniper",
        "mods": ["","","","","","","","","",""],
        "subRoll1": "Firearm ATK",
        "subRoll2": "Critical Hit Damage",
        "subRoll3": "Weak Point Damage",
        "subRoll4": "Bonus ATK (Colossus)",
        "subRoll1Value": 0,
        "subRoll2Value": 0,
        "subRoll3Value": 0,
        "subRoll4Value": 0,
    },
    "boss": {
        "currentBoss": "Devourer",
        "enemyType": "Colossus",
        "currentBossPart": "",
        "currentBossPartType": "",
        "currentBossPartWP": 0,
        // "DEF": 162232,
        // "Fire": 162232,
        // "Electric": 75746,
        // "Chill": 250324,
        // "Toxic": 409149,
    },
    "weaponCritCeiling": 0,
    "skillCritCeiling": 0,
    "ambushImmobileSlider": 100,
    "useWeakspots": true,
    "useCrits": true,
    "useFirearmPhysical": true,

}