let globalRecords = {
    "URLImportCompleted": false,
    "reactor": {
        "currentAttribute": "Chill",
        "currentAttributeID": "reactorChill",
        "currentType": "Singular",
        "currentTypeID": "reactorSingular",
        "subRoll1": "Singular Power Boost",
        "subRoll1Value": 0,
        "subRoll2": "Skill ATK - Colossus",
        "subRoll2Value": 0,
        "currentAmmoType": "Impact",
        "currentAmmoTypeID": "reactorImpact",
        "weaponMatched": true,
        "isUltimate": true,
        "level": 2,
    },
    "components": {
        "auxiliary": "Slayer",
        "auxiliarySub1": "",
        "auxiliarySub2": "",
        "auxiliarySub1Value": 0,
        "auxiliarySub2Value": 0,
        "sensor": "Slayer",
        "sensorSub1": "",
        "sensorSub2": "",
        "sensorSub1Value": 0,
        "sensorSub2Value": 0,
        "memory": "Slayer",
        "memorySub1": "",
        "memorySub2": "",
        "memorySub1Value": 0,
        "memorySub2Value": 0,
        "processor": "Slayer",
        "processorSub1": "",
        "processorSub2": "",
        "processorSub1Value": 0,
        "processorSub2Value": 0,
        "current2piece": "Slayer",
        "current4piece": "Slayer",
    },
    "character": {
        "currentCharacter": "Hailey",
        "mods": ["","","","","","","","","","","",""],
        "abilityArray": [0,0,0,0,0],
        "currentAbilityBreakdown": 4,
        "currentAbilityBreakdownID": "damageAbilityIcon4",
        "statTargets": {//used specifically for comparison targets
            "Max HP": "displayHealth",
            "Max Shield": "displayShield",
            "Max MP": "displayMP",
            "DEF": "displayDEF",
            "Resist - Fire": "totalFireResist",
            "Resist - Chill": "totalChillResist",
            "Resist - Toxin": "totalToxinResist",
            "Resist - Electric": "totalElectricResist",
        },
    },
    "weapon": {
        "currentWeapon": "Afterglow Sword",
        "currentWeaponType": "Sniper",
        "mods": ["","","","","","","","","",""],
        "coreArrayRecord": null,
        "subRoll1": "Firearm ATK",
        "subRoll2": "Critical Hit Damage",
        "subRoll3": "Weak Point Damage",
        "subRoll4": "Bonus ATK (Colossus)",
        "subRoll1Value": 0,
        "subRoll2Value": 0,
        "subRoll3Value": 0,
        "subRoll4Value": 0,

        "coreRoll1": "",
        "coreRoll2": "",
        "coreRoll3": "",
        "coreRoll4": "",
        "coreRoll5": "",

        "coreRoll1Value": 0,
        "coreRoll2Value": 0,
        "coreRoll3Value": 0,
        "coreRoll4Value": 0,
        "coreRoll5Value": 0,
    },
    "boss": {
        "currentBoss": "VoidBattle_Devourer_Hard",
        "enemyType": "Colossus",
        "currentBossPart": "",
        "currentBossPartType": "",
        "currentBossPartWP": 0,
    },
    "teamBuffs": {
        "stats": {},
        "tags": [],
        "Luna": {},
    },
    "currentDisplayMode": 1,
    "weaponCritCeiling": 0,
    "skillCritCeiling": 0,
    "ambushImmobileSlider": 100,
    "weakPointHitRate": 100,
    "useWeakspots": true,
    "useCrits": true,
    "useFirearmPhysical": true,
    "playerCount": 1,





    "lists": {
        "components": [],
    }

}