const vashCharProgressList = [
    //NIHILITY
    //5star
    {name: "Acheron",
        completed: true, live: false, needs80OrTraces: false, owned: true},
    {name: "Black Swan",
        completed: true, live: true, needs80OrTraces: false, owned: true},
    {name: "Cipher",
        completed: false, live: false, needs80OrTraces: false, owned: false},
    {name: "Fugue",
        completed: false, live: false, needs80OrTraces: false, owned: true},
    {name: "Hysilens",
        completed: true, live: true, needs80OrTraces: false, owned: true},
    {name: "Jiaoqiu",
        completed: false, live: false, needs80OrTraces: false, owned: true},
    {name: "Kafka",
        completed: true, live: true, needs80OrTraces: false, owned: true},
    {name: "Mortenax Blade",
        completed: true, live: true, needs80OrTraces: false, owned: true},
    {name: "Silver Wolf",
        completed: true, live: true, needs80OrTraces: false, owned: true},
    {name: "The Dahlia",
        completed: false, live: false, needs80OrTraces: false, owned: true},
    {name: "Welt",
        completed: true, live: true, needs80OrTraces: false, owned: true},
    //4star
    {name: "Guinaifen",
        completed: false, live: false, needs80OrTraces: true, owned: true},
    {name: "Luka",
        completed: false, live: false, needs80OrTraces: true, owned: true},
    {name: "Pela",
        completed: true, live: true, needs80OrTraces: false, owned: true},
    {name: "Sampo",
        completed: false, live: false, needs80OrTraces: true, owned: true},


    //ERUDITION
    {name: "Anaxa",
        completed: true, live: true, needs80OrTraces: false, owned: true},
    {name: "Argenti",
        completed: true, live: true, needs80OrTraces: false, owned: true},
    {name: "Himeko",
        completed: true, live: true, needs80OrTraces: false, owned: true},
    {name: "Jade",
        completed: false, live: false, needs80OrTraces: false, owned: false},
    {name: "Jing Yuan",
        completed: true, live: true, needs80OrTraces: false, owned: true},
    {name: "Rappa",
        completed: false, live: false, needs80OrTraces: false, owned: false},
    {name: "The Herta",
        completed: false, live: false, needs80OrTraces: false, owned: false},
    //4star
    {name: "Herta",
        completed: false, live: false, needs80OrTraces: true, owned: true},
    {name: "Qingque",
        completed: false, live: false, needs80OrTraces: true, owned: true},
    {name: "Serval",
        completed: false, live: false, needs80OrTraces: true, owned: true},


    //DESTRUCTION
    {name: "Blade",
        completed: true, live: true, needs80OrTraces: false, owned: true},
    {name: "Clara",
        completed: true, live: true, needs80OrTraces: false, owned: true},
    {name: "Dan Heng • Imbibitor Lunae",
        completed: true, live: true, needs80OrTraces: false, owned: true},
    {name: "Firefly",
        completed: true, live: true, needs80OrTraces: false, owned: true},
    {name: "Jingliu",
        completed: true, live: true, needs80OrTraces: false, owned: true},
    {name: "Mydei",
        completed: false, live: false, needs80OrTraces: false, owned: false},
    {name: "Phainon",
        completed: false, live: false, needs80OrTraces: false, owned: true},
    {name: "Saber",
        completed: true, live: true, needs80OrTraces: false, owned: true},
    {name: "Trailblazer - Destruction",
        completed: false, live: false, needs80OrTraces: true, owned: true},
    {name: "Yunli",
        completed: false, live: false, needs80OrTraces: true, owned: true},
    //4star
    {name: "Arlan",
        completed: false, live: false, needs80OrTraces: true, owned: true},
    {name: "Hook",
        completed: true, live: true, needs80OrTraces: false, owned: true},
    {name: "Misha",
        completed: false, live: false, needs80OrTraces: true, owned: true},
    {name: "Xueyi",
        completed: false, live: false, needs80OrTraces: false, owned: true},

    //THE HUNT
    {name: "Archer",
        completed: true, live: true, needs80OrTraces: false, owned: true},
    {name: "Ashveil",
        completed: false, live: false, needs80OrTraces: false, owned: false},
    {name: "Boothill",
        completed: false, live: false, needs80OrTraces: false, owned: false},
    {name: "Dr. Ratio",
        completed: true, live: true, needs80OrTraces: false, owned: true},
    {name: "Feixiao",
        completed: false, live: false, needs80OrTraces: false, owned: true},
    {name: "Seele",
        completed: true, live: true, needs80OrTraces: false, owned: true},
    {name: "Topaz & Numby",
        completed: true, live: true, needs80OrTraces: false, owned: true},
    {name: "Yanqing",
        completed: false, live: false, needs80OrTraces: true, owned: true},
    //4star
    {name: "Dan Heng",
        completed: false, live: false, needs80OrTraces: true, owned: true},
    {name: "March 7th - The Hunt",
        completed: false, live: false, needs80OrTraces: true, owned: true},
    {name: "Moze",
        completed: false, live: false, needs80OrTraces: true, owned: true},
    {name: "Sushang",
        completed: false, live: false, needs80OrTraces: true, owned: true},

    //HARMONY
    {name: "Bronya",
        completed: true, live: true, needs80OrTraces: false, owned: true},
    {name: "Cerydra",
        completed: false, live: false, needs80OrTraces: false, owned: false},
    {name: "Robin",
        completed: true, live: true, needs80OrTraces: false, owned: true},
    {name: "Ruan Mei",
        completed: true, live: true, needs80OrTraces: false, owned: true},
    {name: "Sparkle",
        completed: true, live: true, needs80OrTraces: false, owned: true},
    {name: "Sunday",
        completed: true, live: true, needs80OrTraces: false, owned: true},
    {name: "Trailblazer - Harmony",
        completed: false, live: false, needs80OrTraces: false, owned: true},
    {name: "Tribbie",
        completed: true, live: true, needs80OrTraces: false, owned: true},
    //4star
    {name: "Asta",
        completed: true, live: true, needs80OrTraces: false, owned: true},
    {name: "Hanya",
        completed: false, live: false, needs80OrTraces: false, owned: true},
    {name: "Tingyun",
        completed: true, live: true, needs80OrTraces: false, owned: true},
    {name: "Yukong",
        completed: false, live: false, needs80OrTraces: true, owned: true},

    //ABUNDANCE
    {name: "Bailu",
        completed: true, live: true, needs80OrTraces: false, owned: true},
    {name: "Huohuo",
        completed: true, live: true, needs80OrTraces: false, owned: true},
    {name: "Lingsha",
        completed: false, live: false, needs80OrTraces: false, owned: false},
    {name: "Luocha",
        completed: true, live: true, needs80OrTraces: false, owned: true},
    //4star
    {name: "Gallagher",
        completed: true, live: true, needs80OrTraces: false, owned: true},
    {name: "Lynx",
        completed: true, live: true, needs80OrTraces: false, owned: true},
    {name: "Natasha",
        completed: true, live: true, needs80OrTraces: false, owned: true},

    //PRESERVATION
    {name: "Aventurine",
        completed: true, live: true, needs80OrTraces: false, owned: true},
    {name: "Dan Heng • Permansor Terrae",
        completed: true, live: true, needs80OrTraces: false, owned: true},
    {name: "Fu Xuan",
        completed: false, live: false, needs80OrTraces: true, owned: true},
    {name: "Gepard",
        completed: false, live: false, needs80OrTraces: true, owned: true},
    {name: "Trailblazer - Preservation",
        completed: false, live: false, needs80OrTraces: true, owned: true},
    //4star
    {name: "March 7th - Preservation",
        completed: true, live: true, needs80OrTraces: false, owned: true},

    //REMEMBRANCE
    {name: "Aglaea",
        completed: true, live: true, needs80OrTraces: false, owned: true},
    {name: "Castorice",
        completed: true, live: true, needs80OrTraces: false, owned: true},
    {name: "Cyrene",
        completed: false, live: false, needs80OrTraces: false, owned: true},
    {name: "Evernight",
        completed: true, live: true, needs80OrTraces: false, owned: true},
    {name: "Hyacine",
        completed: true, live: true, needs80OrTraces: false, owned: true},
    {name: "Trailblazer - Remembrance",
        completed: true, live: true, needs80OrTraces: false, owned: true},

    //ELATION
    {name: "Yao Guang",
        completed: true, live: true, needs80OrTraces: false, owned: true},
    {name: "Sparxie",
        completed: true, live: true, needs80OrTraces: false, owned: true},
    {name: "Trailblazer - Elation",
        completed: true, live: true, needs80OrTraces: false, owned: true},
    {name: "Silver Wolf LV.999",
        completed: true, live: true, needs80OrTraces: false, owned: true},
    {name: "Evanescia",
        completed: true, live: true, needs80OrTraces: false, owned: true},
]

let vashCharProgressListPOST = [];
for (let charEntry of vashCharProgressList) {
    if (charEntry.owned && !charEntry.needs80OrTraces) {
        vashCharProgressListPOST.push(charEntry.name);
    }
}

global.calcAllowedSet = new Set(vashCharProgressListPOST);