let enemyTemplate = {
    "ATKBase": 718,
    "DEFBase": 1150,
    "SPD": 158,
    "ToughnessBase": 120,
    "EffectRES": 0.30,
    "DMGRes": 0.20,
    // "ATKBase": 718,
    // "ATKBase": 718,
}

let globalUI = {
    "currentMainMenuDisplayed": 1,
    "defaultTeam": ["Saber","Sunday","Dan Heng • Permansor Terrae","Robin"],

    "currentBattleViewDisplayType": "ActionExpand",
    "currentGraphViewDisplayType": "Summary",
    "defaultActionIndex": 0,
    "currentActionIndex": 0,

    "volumeIsOcclusion": false,
    "volumeIsLock": false,

    "buffGraphs": {
        graphBy: "AV",
        buffEntity: "Character",
        entityName: "Hysilens",
        buffName: "",
        statNameTYPE: "Regular",

        graphByStat: "AV",
        buffEntityStat: "Character",
        entityNameStat: "Hysilens",
        statName: null,
    },
    
    "currentCharacterDisplayed": 1,
    "currentCharacterMenuDisplayed": 1,

    "currentSearchOpen": null,
    "currentSearchVolume": null,

    "actionOrderFilters": {},
    "actionOrderFiltersChars": {
        "char1": true,
        "char2": true,
        "char3": true,
        "char4": true,
        "summons": true,
        "enemies": true,
    },




    "filters": {
        char1: {
            tagFilters: [],

            lightconeOcclusions: [],
            armorSetOcclusions: [],
            planarSetOcclusions: [],

            mainstatBodyOcclusions: [],
            mainstatFeetOcclusions: [],
            mainstatOrbOcclusions: [],
            mainstatRopeOcclusions: [],
            substatOcclusions: [],

            lightconeLocks: [],
            armorSetLocks2pc: [],
            armorSetLocks4pc: [],
            planarSetLocks: [],
            mainstatBodyLocks: [],
            mainstatFeetLocks: [],
            mainstatOrbLocks: [],
            mainstatRopeLocks: [],

            trashStatFilters: null,

            lightcone: false,
            armorSet: false,
            armorSetAllow2pc: false,
            planarSet: false,
            mainstatBody: false,
            mainstatFeet: false,
            mainstatOrb: false,
            mainstatRope: false,
            substat: false,

            desired1: null,
            desired2: null,
            desired3: null,
            desired4: null,

            substat1: [1,30],
            substat2: [1,30],
            substat3: [1,30],
            substat4: [1,30],
        },
        char2: {
            tagFilters: [],

            lightconeOcclusions: [],
            armorSetOcclusions: [],
            planarSetOcclusions: [],

            mainstatBodyOcclusions: [],
            mainstatFeetOcclusions: [],
            mainstatOrbOcclusions: [],
            mainstatRopeOcclusions: [],
            substatOcclusions: [],

            lightconeLocks: [],
            armorSetLocks2pc: [],
            armorSetLocks4pc: [],
            planarSetLocks: [],
            mainstatBodyLocks: [],
            mainstatFeetLocks: [],
            mainstatOrbLocks: [],
            mainstatRopeLocks: [],

            trashStatFilters: null,

            lightcone: false,
            armorSet: false,
            armorSetAllow2pc: false,
            planarSet: false,
            mainstatBody: false,
            mainstatFeet: false,
            mainstatOrb: false,
            mainstatRope: false,
            substat: false,

            desired1: null,
            desired2: null,
            desired3: null,
            desired4: null,

            substat1: [1,30],
            substat2: [1,30],
            substat3: [1,30],
            substat4: [1,30],
        },
        char3: {
            tagFilters: [],

            lightconeOcclusions: [],
            armorSetOcclusions: [],
            planarSetOcclusions: [],

            mainstatBodyOcclusions: [],
            mainstatFeetOcclusions: [],
            mainstatOrbOcclusions: [],
            mainstatRopeOcclusions: [],
            substatOcclusions: [],

            lightconeLocks: [],
            armorSetLocks2pc: [],
            armorSetLocks4pc: [],
            planarSetLocks: [],
            mainstatBodyLocks: [],
            mainstatFeetLocks: [],
            mainstatOrbLocks: [],
            mainstatRopeLocks: [],

            trashStatFilters: null,

            lightcone: false,
            armorSet: false,
            armorSetAllow2pc: false,
            planarSet: false,
            mainstatBody: false,
            mainstatFeet: false,
            mainstatOrb: false,
            mainstatRope: false,
            substat: false,

            desired1: null,
            desired2: null,
            desired3: null,
            desired4: null,

            substat1: [1,30],
            substat2: [1,30],
            substat3: [1,30],
            substat4: [1,30],
        },
        char4: {
            tagFilters: [],

            lightconeOcclusions: [],
            armorSetOcclusions: [],
            planarSetOcclusions: [],

            mainstatBodyOcclusions: [],
            mainstatFeetOcclusions: [],
            mainstatOrbOcclusions: [],
            mainstatRopeOcclusions: [],
            substatOcclusions: [],

            lightconeLocks: [],
            armorSetLocks2pc: [],
            armorSetLocks4pc: [],
            planarSetLocks: [],
            mainstatBodyLocks: [],
            mainstatFeetLocks: [],
            mainstatOrbLocks: [],
            mainstatRopeLocks: [],

            trashStatFilters: null,

            lightcone: false,
            armorSet: false,
            armorSetAllow2pc: false,
            planarSet: false,
            mainstatBody: false,
            mainstatFeet: false,
            mainstatOrb: false,
            mainstatRope: false,
            substat: false,

            desired1: null,
            desired2: null,
            desired3: null,
            desired4: null,

            substat1: [1,30],
            substat2: [1,30],
            substat3: [1,30],
            substat4: [1,30],
        },
    }
}
let globalRecords = {
    queueStorage: [],
    resultsStorage: [],
    currentWorstResult: null,
    workersRunning: 0,
    counterInt: 0,
    globalSkipCount: 0,
    "URLImportCompleted": false,

    // "cyclesToRun": 5,

    "battleSettings": {
        "enemiesArray": [
            // {entry:"GenericBoss", weaknesses: "All"},
            // {entry:"GenericBoss", weaknesses: "None"},
            // {entry:"GenericElite", weaknesses: "None"},
            // {entry:"GenericElite", weaknesses: "All"},

            //CALYX CRIMSON
            {entry:"GenericMinion", weaknesses: null,weaknessOverrides: {"Lightning": true,"Ice":true,"Quantum":true},resistantTo: {}},
            // {entry:"GenericMinion", weaknesses: null,weaknessOverrides: {"Lightning": true,"Wind":false,"Quantum":false}, resistantTo: {"Wind":true}},
            {entry:"GenericMinion2", weaknesses: null,weaknessOverrides: {"Physical": true,"Wind":true,"Ice":true,},resistantTo: {}},
            {entry:"GenericMinion2", weaknesses: null,weaknessOverrides: {"Physical": true,"Wind":true,"Ice":true,},resistantTo: {}},

            //STAGNANT SHADOW - ICE - SHAPE OF RHIME
            // {entry:"Everwinter Shadewalker", weaknesses: null,weaknessOverrides: {"Physical": true,"Fire":true,"Quantum":true,},resistantTo: {"Ice":true,}},
            // {entry:"Frigid Prowler", weaknesses: null,weaknessOverrides: {"Lightning": true,"Fire":true,"Quantum":true},resistantTo: {"Ice":true,}},
            // {entry:"Everwinter Shadewalker", weaknesses: null,weaknessOverrides: {"Physical": true,"Fire":true,"Quantum":true,},resistantTo: {"Ice":true,}},


            // //MOC6
            // {entry:"MOC6SwordBoi", weaknesses: null,weaknessOverrides: {"Ice": true,"Fire":true,"Quantum":true}, resistantTo: {"Wind":true}},
            // {entry:"MOC6SwordBoi", weaknesses: null,weaknessOverrides: {"Ice": true,"Fire":true,"Quantum":true}, resistantTo: {"Wind":true}},
            // {entry:"MOC6Fish", weaknesses: null,weaknessOverrides: {"Physical": true,"Lightning":true,"Imaginary":true},resistantTo: {}},
            // {entry:"MOC6Fish", weaknesses: null,weaknessOverrides: {"Physical": true,"Lightning":true,"Imaginary":true},resistantTo: {}},
            
        ],
        "cyclesToRun": 3,
        "cycleMode": "MOC",

        "useTechniques": true,
        "useTechniquesChar1": true,
        "useTechniquesChar2": true,
        "useTechniquesChar3": true,
        "useTechniquesChar4": true,

        "useStartToughness": true,

        "cyclesStartingEnergyCustom": 0.50,

        "totalWaves": 1,

        "waveArray1": [...vashWavePresets["Glorp-ard"][0]],//vashWavePresets.quantumDoggo[0]
        "waveArray2": [],//vashWavePresets.quantumDoggo[1]
        "waveArray3": [],
        "waveArray4": [],
        "waveArray5": [],
    },
    "querySettings": {
        "enforceBattlesWon": false,
        "searchTarget": "",
        // "allow2pcSearch": false,

        "substatRollValue": "High",
        "rollsPerRelic": 4,
        "rollsPerBundle": 2,
        "usableBaseRolls": 20,
        "failedAddedRolls": 1,
        "minimumAddedRoll": 1,

        "ignoreQueryLimit": false,


        "queries5starSuperValue": 1,
        "queries5starHertaValue": 5,
        "queries4starSuperValue": 5,
        "keepLightconeRank": false,
    },

    "character": {
        "char1": {
            "name": "Black Swan",
            "rank": 0,
            "lineup": 1,
            "lcName": "Reforged Remembrance",
            "lcRank": 1,
            "2pc": "Prisoner in Deep Confinement",
            "4pc": "Prisoner in Deep Confinement",
            "planar": "Pan-Cosmic Commercial Enterprise",
            "HeadMain": "HPFlat",
            "Head1Stat": "ATKFlat",
            "Head1Value": 16.935019,
            "Head2Stat": "SPDFlat",
            "Head2Value": 7,
            "Head3Stat": "EffectHitRate",
            "Head3Value": 0.07344,
            "Head4Stat": "EffectRES",
            "Head4Value": 0.12096,
            "HandsMain": "ATKFlat",
            "Hands1Stat": "ATK%",
            "Hands1Value": 0.0432,
            "Hands2Stat": "SPDFlat",
            "Hands2Value": 4,
            "Hands3Stat": "EffectHitRate",
            "Hands3Value": 0.12096,
            "Hands4Stat": "DamageBreak",
            "Hands4Value": 0.11016,
            "BodyMain": "ATK%",
            "Body1Stat": "DEFFlat",
            "Body1Value": 35.986912,
            "Body2Stat": "HP%",
            "Body2Value": 0.03888,
            "Body3Stat": "DEF%",
            "Body3Value": 0.054,
            "Body4Stat": "EffectHitRate",
            "Body4Value": 0.15984,
            "FeetMain": "SPDFlat",
            "Feet1Stat": "DEFFlat",
            "Feet1Value": 21.168773,
            "Feet2Stat": "ATK%",
            "Feet2Value": 0.03888,
            "Feet3Stat": "EffectHitRate",
            "Feet3Value": 0.11664,
            "Feet4Stat": "DamageBreak",
            "Feet4Value": 0.16848,
            "SphereMain": "DamageWind",
            "Sphere1Stat": "DEFFlat",
            "Sphere1Value": 59.272559,
            "Sphere2Stat": "CritRateBase",
            "Sphere2Value": 0.0324,
            "Sphere3Stat": "EffectHitRate",
            "Sphere3Value": 0.07344,
            "Sphere4Stat": "EffectRES",
            "Sphere4Value": 0.07776,
            "RopeMain": "ATK%",
            "Rope1Stat": "HPFlat",
            "Rope1Value": 110.07763,
            "Rope2Stat": "DEF%",
            "Rope2Value": 0.0972,
            "Rope3Stat": "CritDamageBase",
            "Rope3Value": 0.11664,
            "Rope4Stat": "EffectHitRate",
            "Rope4Value": 0.0864,
            "disabled": false,
            "stats": {},
            "order": [],
            "conditions": {
                "hasEnhancedState": false,
                "Skill": {
                    "type": "AND",
                    "array": []
                },
                "Ultimate": {
                    "type": "AND",
                    "array": []
                }
            }
        },
        "char2": {
            "name": "Kafka",
            "rank": 0,
            "lineup": 1,
            "lcName": "Before the Tutorial Mission Starts",
            "lcRank": 5,
            "2pc": "Eagle of Twilight Line",
            "4pc": "Eagle of Twilight Line",
            "planar": "Lushaka, the Sunken Seas",
            "HeadMain": "HPFlat",
            "Head1Stat": "ATKFlat",
            "Head1Value": 21.168773,
            "Head2Stat": "HP%",
            "Head2Value": 0.11232,
            "Head3Stat": "SPDFlat",
            "Head3Value": 7,
            "Head4Stat": "CritRateBase",
            "Head4Value": 0.06156,
            "HandsMain": "ATKFlat",
            "Hands1Stat": "HPFlat",
            "Hands1Value": 80.441345,
            "Hands2Stat": "SPDFlat",
            "Hands2Value": 7,
            "Hands3Stat": "CritDamageBase",
            "Hands3Value": 0.1296,
            "Hands4Stat": "EffectRES",
            "Hands4Value": 0.07776,
            "BodyMain": "ATK%",
            "Body1Stat": "HP%",
            "Body1Value": 0.07776,
            "Body2Stat": "DEF%",
            "Body2Value": 0.0918,
            "Body3Stat": "SPDFlat",
            "Body3Value": 8,
            "Body4Stat": "EffectRES",
            "Body4Value": 0.0432,
            "FeetMain": "SPDFlat",
            "Feet1Stat": "ATKFlat",
            "Feet1Value": 40.220666,
            "Feet2Stat": "CritRateBase",
            "Feet2Value": 0.081,
            "Feet3Stat": "EffectHitRate",
            "Feet3Value": 0.0864,
            "Feet4Stat": "DamageBreak",
            "Feet4Value": 0.0648,
            "SphereMain": "DamageLightning",
            "Sphere1Stat": "HPFlat",
            "Sphere1Value": 71.973835,
            "Sphere2Stat": "HP%",
            "Sphere2Value": 0.12096,
            "Sphere3Stat": "SPDFlat",
            "Sphere3Value": 4,
            "Sphere4Stat": "EffectHitRate",
            "Sphere4Value": 0.06912,
            "RopeMain": "EnergyRegenRate",
            "Rope1Stat": "ATK%",
            "Rope1Value": 0.03888,
            "Rope2Stat": "SPDFlat",
            "Rope2Value": 9,
            "Rope3Stat": "EffectHitRate",
            "Rope3Value": 0.07344,
            "Rope4Stat": "DamageBreak",
            "Rope4Value": 0.05184,
            "disabled": false,
            "stats": {},
            "order": [],
            "conditions": {
                "hasEnhancedState": false,
                "Skill": {
                    "type": "AND",
                    "array": []
                },
                "Ultimate": {
                    "type": "COMPARE",
                    "comparison": "<",
                    "array": [
                        {
                            "type": "Character: Special Value",
                            "target": "Self",
                            "specialValue": "fuaStacks",
                            "isBattleValue": true
                        },
                        {
                            "type": "User Value: Number",
                            "inputValue": 2
                        }
                    ]
                }
            }
        },
        "char3": {
            "name": "Dan Heng • Permansor Terrae",
            "rank": 0,
            "lineup": 1,
            "lcName": "Though Worlds Apart",
            "lcRank": 1,
            "2pc": "Self-Enshrouded Recluse",
            "4pc": "Self-Enshrouded Recluse",
            "planar": "Lushaka, the Sunken Seas",
            "HeadMain": "HPFlat",
            "Head1Stat": "ATKFlat",
            "Head1Value": 52.921928,
            "Head2Stat": "DEFFlat",
            "Head2Value": 19.051896,
            "Head3Stat": "HP%",
            "Head3Value": 0.03888,
            "Head4Stat": "SPDFlat",
            "Head4Value": 6,
            "HandsMain": "ATKFlat",
            "Hands1Stat": "HP%",
            "Hands1Value": 0.08208,
            "Hands2Stat": "SPDFlat",
            "Hands2Value": 9,
            "Hands3Stat": "EffectHitRate",
            "Hands3Value": 0.0432,
            "Hands4Stat": "DamageBreak",
            "Hands4Value": 0.05184,
            "BodyMain": "ATK%",
            "Body1Stat": "ATKFlat",
            "Body1Value": 38.103789,
            "Body2Stat": "DEF%",
            "Body2Value": 0.1026,
            "Body3Stat": "SPDFlat",
            "Body3Value": 9,
            "Body4Stat": "EffectRES",
            "Body4Value": 0.03456,
            "FeetMain": "ATK%",
            "Feet1Stat": "DEF%",
            "Feet1Value": 0.1512,
            "Feet2Stat": "SPDFlat",
            "Feet2Value": 4,
            "Feet3Stat": "EffectRES",
            "Feet3Value": 0.07344,
            "Feet4Stat": "DamageBreak",
            "Feet4Value": 0.05832,
            "SphereMain": "ATK%",
            "Sphere1Stat": "DEF%",
            "Sphere1Value": 0.054,
            "Sphere2Stat": "SPDFlat",
            "Sphere2Value": 6,
            "Sphere3Stat": "EffectRES",
            "Sphere3Value": 0.07776,
            "Sphere4Stat": "HP%",
            "Sphere4Value": 0.07344,
            "RopeMain": "ATK%",
            "Rope1Stat": "ATKFlat",
            "Rope1Value": 57.155682,
            "Rope2Stat": "CritRateBase",
            "Rope2Value": 0.07776,
            "Rope3Stat": "CritDamageBase",
            "Rope3Value": 0.05184,
            "Rope4Stat": "DamageBreak",
            "Rope4Value": 0.05184,
            "conditions": {
                "hasEnhancedState": false,
                "Skill": {
                    "type": "OR",
                    "array": [
                        {
                            "type": "Buff",
                            "target": "char1",
                            "targetType": "Character",
                            "buffName": "Bondmate [Empyreanity]",
                            "state": false
                        },
                        {
                            "type": "Sustain Checks",
                            "sustainValue": "Any Ally: Has no Shield"
                        }
                    ]
                },
                "Ultimate": {
                    "type": "AND",
                    "array": []
                }
            },
            "stats": {},
            "order": [],
            "disabled": false
        },
        "char4": {
            "name": "Hysilens",
            "rank": 0,
            "lineup": 1,
            "lcName": "Why Does the Ocean Sing",
            "lcRank": 1,
            "2pc": "Prisoner in Deep Confinement",
            "4pc": "Prisoner in Deep Confinement",
            "planar": "Revelry by the Sea",
            "HeadMain": "HPFlat",
            "Head1Stat": "ATK%",
            "Head1Value": 0.0864,
            "Head2Stat": "DEF%",
            "Head2Value": 0.0432,
            "Head3Stat": "SPDFlat",
            "Head3Value": 7,
            "Head4Stat": "EffectHitRate",
            "Head4Value": 0.0864,
            "HandsMain": "ATKFlat",
            "Hands1Stat": "ATK%",
            "Hands1Value": 0.07344,
            "Hands2Stat": "SPDFlat",
            "Hands2Value": 2,
            "Hands3Stat": "EffectHitRate",
            "Hands3Value": 0.11664,
            "Hands4Stat": "DamageBreak",
            "Hands4Value": 0.11664,
            "BodyMain": "EffectHitRate",
            "Body1Stat": "ATKFlat",
            "Body1Value": 38.103789,
            "Body2Stat": "DEFFlat",
            "Body2Value": 16.935019,
            "Body3Stat": "SPDFlat",
            "Body3Value": 6,
            "Body4Stat": "DamageBreak",
            "Body4Value": 0.18144,
            "FeetMain": "ATK%",
            "Feet1Stat": "ATKFlat",
            "Feet1Value": 38.103789,
            "Feet2Stat": "HP%",
            "Feet2Value": 0.0432,
            "Feet3Stat": "DEF%",
            "Feet3Value": 0.0432,
            "Feet4Stat": "SPDFlat",
            "Feet4Value": 9,
            "SphereMain": "DamagePhysical",
            "Sphere1Stat": "HPFlat",
            "Sphere1Value": 33.87004,
            "Sphere2Stat": "ATK%",
            "Sphere2Value": 0.11664,
            "Sphere3Stat": "SPDFlat",
            "Sphere3Value": 6,
            "Sphere4Stat": "DamageBreak",
            "Sphere4Value": 0.05832,
            "RopeMain": "EnergyRegenRate",
            "Rope1Stat": "HP%",
            "Rope1Value": 0.07776,
            "Rope2Stat": "SPDFlat",
            "Rope2Value": 6,
            "Rope3Stat": "CritDamageBase",
            "Rope3Value": 0.05184,
            "Rope4Stat": "EffectHitRate",
            "Rope4Value": 0.06912,
            "conditions": {
                "hasEnhancedState": false,
                "Skill": {
                    "type": "AND",
                    "array": []
                },
                "Ultimate": {
                    "type": "AND",
                    "array": []
                }
            },
            "disabled": false,
            "stats": {},
            "order": []
        }
    },
    // "boss": {
    //     "currentBoss": "VoidBattle_Devourer_Hard",
    //     "enemyType": "Colossus",
    //     "currentBossPart": "",
    //     "currentBossPartType": "",
    //     "currentBossPartWP": 0,
    // },
    // "teamBuffs": {
    //     "stats": {},
    //     "tags": [],
    //     "complexBonus": [],
    // },
    // "enemyBuffs": {
    //     "stats": {},
    //     "tags": [],
    // },
    // "currentDisplayMode": 1,
    // "weaponCritCeiling": 0,
    // "skillCritCeiling": 0,
    // "ambushImmobileSlider": 100,
    // "weakPointHitRate": 100,
    // "useWeakspots": true,
    // "useCrits": true,
    // "useFirearmPhysical": true,
    // "playerCount": 1,

}