let enemyTemplate = {
    "ATKBase": 718,
    "DEFBase": 1150,
    "SPD": 158,
    "ToughnessBase": 120,
    "EffectRES": 0.30,
    "DMGRes": 0.20,
    // "ATKBase": 718,
    // "ATKBase": 718,
}

let globalUI = {
    "currentMainMenuDisplayed": 1,
    "defaultTeam": ["Saber","Sunday","Dan Heng • Permansor Terrae","Robin"],

    "currentBattleViewDisplayType": "ActionExpand",
    "currentGraphViewDisplayType": "Summary",
    "defaultActionIndex": 0,
    "currentActionIndex": 0,

    "volumeIsOcclusion": false,
    "volumeIsLock": false,

    "buffGraphs": {
        graphBy: "AV",
        buffEntity: "Character",
        entityName: "Hysilens",
        buffName: "",
    },
    
    "currentCharacterDisplayed": 1,
    "currentCharacterMenuDisplayed": 1,

    "currentSearchOpen": null,
    "currentSearchVolume": null,

    "actionOrderFilters": {},
    "actionOrderFiltersChars": {
        "char1": true,
        "char2": true,
        "char3": true,
        "char4": true,
        "summons": true,
        "enemies": true,
    },




    "filters": {
        char1: {
            tagFilters: [],

            lightconeOcclusions: [],
            armorSetOcclusions: [],
            planarSetOcclusions: [],

            mainstatBodyOcclusions: [],
            mainstatFeetOcclusions: [],
            mainstatOrbOcclusions: [],
            mainstatRopeOcclusions: [],
            substatOcclusions: [],

            lightconeLocks: [],
            armorSetLocks2pc: [],
            armorSetLocks4pc: [],
            planarSetLocks: [],
            mainstatBodyLocks: [],
            mainstatFeetLocks: [],
            mainstatOrbLocks: [],
            mainstatRopeLocks: [],

            trashStatFilters: null,

            lightcone: false,
            armorSet: false,
            armorSetAllow2pc: false,
            planarSet: false,
            mainstatBody: false,
            mainstatFeet: false,
            mainstatOrb: false,
            mainstatRope: false,
            substat: false,

            desired1: null,
            desired2: null,
            desired3: null,
            desired4: null,

            substat1: [1,30],
            substat2: [1,30],
            substat3: [1,30],
            substat4: [1,30],
        },
        char2: {
            tagFilters: [],

            lightconeOcclusions: [],
            armorSetOcclusions: [],
            planarSetOcclusions: [],

            mainstatBodyOcclusions: [],
            mainstatFeetOcclusions: [],
            mainstatOrbOcclusions: [],
            mainstatRopeOcclusions: [],
            substatOcclusions: [],

            lightconeLocks: [],
            armorSetLocks2pc: [],
            armorSetLocks4pc: [],
            planarSetLocks: [],
            mainstatBodyLocks: [],
            mainstatFeetLocks: [],
            mainstatOrbLocks: [],
            mainstatRopeLocks: [],

            trashStatFilters: null,

            lightcone: false,
            armorSet: false,
            armorSetAllow2pc: false,
            planarSet: false,
            mainstatBody: false,
            mainstatFeet: false,
            mainstatOrb: false,
            mainstatRope: false,
            substat: false,

            desired1: null,
            desired2: null,
            desired3: null,
            desired4: null,

            substat1: [1,30],
            substat2: [1,30],
            substat3: [1,30],
            substat4: [1,30],
        },
        char3: {
            tagFilters: [],

            lightconeOcclusions: [],
            armorSetOcclusions: [],
            planarSetOcclusions: [],

            mainstatBodyOcclusions: [],
            mainstatFeetOcclusions: [],
            mainstatOrbOcclusions: [],
            mainstatRopeOcclusions: [],
            substatOcclusions: [],

            lightconeLocks: [],
            armorSetLocks2pc: [],
            armorSetLocks4pc: [],
            planarSetLocks: [],
            mainstatBodyLocks: [],
            mainstatFeetLocks: [],
            mainstatOrbLocks: [],
            mainstatRopeLocks: [],

            trashStatFilters: null,

            lightcone: false,
            armorSet: false,
            armorSetAllow2pc: false,
            planarSet: false,
            mainstatBody: false,
            mainstatFeet: false,
            mainstatOrb: false,
            mainstatRope: false,
            substat: false,

            desired1: null,
            desired2: null,
            desired3: null,
            desired4: null,

            substat1: [1,30],
            substat2: [1,30],
            substat3: [1,30],
            substat4: [1,30],
        },
        char4: {
            tagFilters: [],

            lightconeOcclusions: [],
            armorSetOcclusions: [],
            planarSetOcclusions: [],

            mainstatBodyOcclusions: [],
            mainstatFeetOcclusions: [],
            mainstatOrbOcclusions: [],
            mainstatRopeOcclusions: [],
            substatOcclusions: [],

            lightconeLocks: [],
            armorSetLocks2pc: [],
            armorSetLocks4pc: [],
            planarSetLocks: [],
            mainstatBodyLocks: [],
            mainstatFeetLocks: [],
            mainstatOrbLocks: [],
            mainstatRopeLocks: [],

            trashStatFilters: null,

            lightcone: false,
            armorSet: false,
            armorSetAllow2pc: false,
            planarSet: false,
            mainstatBody: false,
            mainstatFeet: false,
            mainstatOrb: false,
            mainstatRope: false,
            substat: false,

            desired1: null,
            desired2: null,
            desired3: null,
            desired4: null,

            substat1: [1,30],
            substat2: [1,30],
            substat3: [1,30],
            substat4: [1,30],
        },
    }
}
let globalRecords = {
    queueStorage: [],
    resultsStorage: [],
    currentWorstResult: null,
    workersRunning: 0,
    counterInt: 0,
    globalSkipCount: 0,
    "URLImportCompleted": false,

    // "cyclesToRun": 5,

    "battleSettings": {
        "enemiesArray": [
            // {entry:"GenericBoss", weaknesses: "All"},
            // {entry:"GenericBoss", weaknesses: "None"},
            // {entry:"GenericElite", weaknesses: "None"},
            // {entry:"GenericElite", weaknesses: "All"},

            //CALYX CRIMSON
            {entry:"GenericMinion", weaknesses: null,weaknessOverrides: {"Lightning": true,"Ice":true,"Quantum":true},resistantTo: {}},
            // {entry:"GenericMinion", weaknesses: null,weaknessOverrides: {"Lightning": true,"Wind":false,"Quantum":false}, resistantTo: {"Wind":true}},
            {entry:"GenericMinion2", weaknesses: null,weaknessOverrides: {"Physical": true,"Wind":true,"Ice":true,},resistantTo: {}},
            {entry:"GenericMinion2", weaknesses: null,weaknessOverrides: {"Physical": true,"Wind":true,"Ice":true,},resistantTo: {}},

            //STAGNANT SHADOW - ICE - SHAPE OF RHIME
            // {entry:"Everwinter Shadewalker", weaknesses: null,weaknessOverrides: {"Physical": true,"Fire":true,"Quantum":true,},resistantTo: {"Ice":true,}},
            // {entry:"Frigid Prowler", weaknesses: null,weaknessOverrides: {"Lightning": true,"Fire":true,"Quantum":true},resistantTo: {"Ice":true,}},
            // {entry:"Everwinter Shadewalker", weaknesses: null,weaknessOverrides: {"Physical": true,"Fire":true,"Quantum":true,},resistantTo: {"Ice":true,}},


            // //MOC6
            // {entry:"MOC6SwordBoi", weaknesses: null,weaknessOverrides: {"Ice": true,"Fire":true,"Quantum":true}, resistantTo: {"Wind":true}},
            // {entry:"MOC6SwordBoi", weaknesses: null,weaknessOverrides: {"Ice": true,"Fire":true,"Quantum":true}, resistantTo: {"Wind":true}},
            // {entry:"MOC6Fish", weaknesses: null,weaknessOverrides: {"Physical": true,"Lightning":true,"Imaginary":true},resistantTo: {}},
            // {entry:"MOC6Fish", weaknesses: null,weaknessOverrides: {"Physical": true,"Lightning":true,"Imaginary":true},resistantTo: {}},
            
        ],
        "cyclesToRun": 3,
        "cycleMode": "MOC",

        "useTechniques": true,
        "useTechniquesChar1": true,
        "useTechniquesChar2": true,
        "useTechniquesChar3": true,
        "useTechniquesChar4": true,

        "useStartToughness": true,

        "totalWaves": 1,

        "waveArray1": [...vashWavePresets["Glorp-ard"][0]],//vashWavePresets.quantumDoggo[0]
        "waveArray2": [],//vashWavePresets.quantumDoggo[1]
        "waveArray3": [],
        "waveArray4": [],
        "waveArray5": [],
    },
    "querySettings": {
        "enforceBattlesWon": false,
        "searchTarget": "",
        // "allow2pcSearch": false,

        "substatRollValue": "High",
        "rollsPerRelic": 4,
        "rollsPerBundle": 2,
        "usableBaseRolls": 20,
        "failedAddedRolls": 1,
        "minimumAddedRoll": 1,

        "ignoreQueryLimit": false,


        "queries5starSuperValue": 1,
        "queries5starHertaValue": 5,
        "queries4starSuperValue": 5,
        "keepLightconeRank": false,
    },

    "character": {
        "char1": {
            "name": "Saber",
            "rank": 0,
            "lineup": 1,
            "lcName": "A Thankless Coronation",
            "lcRank": 1,
            "2pc": "Scholar Lost in Erudition",
            "4pc": "Scholar Lost in Erudition",
            "planar": "The Wondrous BananAmusement Park",
            "HeadMain": "HPFlat",
            "Head1Stat": "ATKFlat",
            "Head1Value": 16.935019,
            "Head2Stat": "CritRateBase",
            "Head2Value": 0.14904,
            "Head3Stat": "CritDamageBase",
            "Head3Value": 0.05184,
            "Head4Stat": "EffectRES",
            "Head4Value": 0.07776,
            "HandsMain": "ATKFlat",
            "Hands1Stat": "ATK%",
            "Hands1Value": 0.12096,
            "Hands2Stat": "CritRateBase",
            "Hands2Value": 0.06156,
            "Hands3Stat": "CritDamageBase",
            "Hands3Value": 0.0648,
            "Hands4Stat": "DamageBreak",
            "Hands4Value": 0.17496,
            "BodyMain": "CritDamageBase",
            "Body1Stat": "HP%",
            "Body1Value": 0.12096,
            "Body2Stat": "DEF%",
            "Body2Value": 0.1026,
            "Body3Stat": "CritRateBase",
            "Body3Value": 0.05508,
            "Body4Stat": "DamageBreak",
            "Body4Value": 0.0648,
            "FeetMain": "ATK%",
            "Feet1Stat": "SPDFlat",
            "Feet1Value": 2,
            "Feet2Stat": "CritRateBase",
            "Feet2Value": 0.0648,
            "Feet3Stat": "CritDamageBase",
            "Feet3Value": 0.23328,
            "Feet4Stat": "ATKFlat",
            "Feet4Value": 19.051896,
            "SphereMain": "ATK%",
            "Sphere1Stat": "HP%",
            "Sphere1Value": 0.03888,
            "Sphere2Stat": "SPDFlat",
            "Sphere2Value": 2,
            "Sphere3Stat": "CritRateBase",
            "Sphere3Value": 0.08424,
            "Sphere4Stat": "CritDamageBase",
            "Sphere4Value": 0.18144,
            "RopeMain": "ATK%",
            "Rope1Stat": "HP%",
            "Rope1Value": 0.11232,
            "Rope2Stat": "CritRateBase",
            "Rope2Value": 0.0324,
            "Rope3Stat": "CritDamageBase",
            "Rope3Value": 0.23976,
            "Rope4Stat": "DamageBreak",
            "Rope4Value": 0.0648,
        },
        "char2": {
            "name": "Sunday",
            "rank": 0,
            "lineup": 1,
            "lcName": "A Grounded Ascent",
            "lcRank": 1,
            "2pc": "Sacerdos' Relived Ordeal",
            "4pc": "Sacerdos' Relived Ordeal",
            "planar": "Lushaka, the Sunken Seas",
            "HeadMain": "HPFlat",
            "Head1Stat": "DEFFlat",
            "Head1Value": 38.103789,
            "Head2Stat": "SPDFlat",
            "Head2Value": 6,
            "Head3Stat": "CritDamageBase",
            "Head3Value": 0.11664,
            "Head4Stat": "DamageBreak",
            "Head4Value": 0.11016,
            "HandsMain": "ATKFlat",
            "Hands1Stat": "HPFlat",
            "Hands1Value": 38.103795,
            "Hands2Stat": "ATK%",
            "Hands2Value": 0.03888,
            "Hands3Stat": "SPDFlat",
            "Hands3Value": 7,
            "Hands4Stat": "CritDamageBase",
            "Hands4Value": 0.18792,
            "BodyMain": "CritDamageBase",
            "Body1Stat": "ATKFlat",
            "Body1Value": 42.337543,
            "Body2Stat": "SPDFlat",
            "Body2Value": 7,
            "Body3Stat": "CritRateBase",
            "Body3Value": 0.06156,
            "Body4Stat": "EffectRES",
            "Body4Value": 0.03888,
            "FeetMain": "SPDFlat",
            "Feet1Stat": "HP%",
            "Feet1Value": 0.03456,
            "Feet2Stat": "ATK%",
            "Feet2Value": 0.07344,
            "Feet3Stat": "EffectHitRate",
            "Feet3Value": 0.108,
            "Feet4Stat": "DamageBreak",
            "Feet4Value": 0.12312,
            "SphereMain": "HP%",
            "Sphere1Stat": "HPFlat",
            "Sphere1Value": 71.973835,
            "Sphere2Stat": "DEFFlat",
            "Sphere2Value": 19.051896,
            "Sphere3Stat": "SPDFlat",
            "Sphere3Value": 6,
            "Sphere4Stat": "EffectHitRate",
            "Sphere4Value": 0.0864,
            "RopeMain": "EnergyRegenRate",
            "Rope1Stat": "HP%",
            "Rope1Value": 0.11664,
            "Rope2Stat": "DEF%",
            "Rope2Value": 0.0486,
            "Rope3Stat": "SPDFlat",
            "Rope3Value": 9,
            "Rope4Stat": "EffectRES",
            "Rope4Value": 0.03888
        },
        "char3": {
            "name": "Dan Heng • Permansor Terrae",
            "rank": 0,
            "lineup": 1,
            "lcName": "Though Worlds Apart",
            "lcRank": 1,
            "2pc": "Self-Enshrouded Recluse",
            "4pc": "Self-Enshrouded Recluse",
            "planar": "Lushaka, the Sunken Seas",
            "HeadMain": "HPFlat",
            "Head1Stat": "ATKFlat",
            "Head1Value": 52.921928,
            "Head2Stat": "DEFFlat",
            "Head2Value": 19.051896,
            "Head3Stat": "SPDFlat",
            "Head3Value": 8,
            "Head4Stat": "HP%",
            "Head4Value": 0.03888,
            "HandsMain": "ATKFlat",
            "Hands1Stat": "HP%",
            "Hands1Value": 0.08208,
            "Hands2Stat": "SPDFlat",
            "Hands2Value": 9,
            "Hands3Stat": "EffectHitRate",
            "Hands3Value": 0.0432,
            "Hands4Stat": "DamageBreak",
            "Hands4Value": 0.05184,
            "BodyMain": "ATK%",
            "Body1Stat": "ATKFlat",
            "Body1Value": 38.103789,
            "Body2Stat": "DEF%",
            "Body2Value": 0.1026,
            "Body3Stat": "SPDFlat",
            "Body3Value": 6,
            "Body4Stat": "EffectRES",
            "Body4Value": 0.03456,
            "FeetMain": "SPDFlat",
            "Feet1Stat": "HPFlat",
            "Feet1Value": 38.103795,
            "Feet2Stat": "ATK%",
            "Feet2Value": 0.11664,
            "Feet3Stat": "DEF%",
            "Feet3Value": 0.0864,
            "Feet4Stat": "EffectRES",
            "Feet4Value": 0.07776,
            "SphereMain": "ATK%",
            "Sphere1Stat": "DEF%",
            "Sphere1Value": 0.054,
            "Sphere2Stat": "SPDFlat",
            "Sphere2Value": 6,
            "Sphere3Stat": "EffectRES",
            "Sphere3Value": 0.07776,
            "Sphere4Stat": "HP%",
            "Sphere4Value": 0.07344,
            "RopeMain": "EnergyRegenRate",
            "Rope1Stat": "ATKFlat",
            "Rope1Value": 52.921928,
            "Rope2Stat": "DEFFlat",
            "Rope2Value": 55.038805,
            "Rope3Stat": "DEF%",
            "Rope3Value": 0.0432,
            "Rope4Stat": "SPDFlat",
            "Rope4Value": 4,
        },
        "char4": {
            "name": "Robin",
            "rank": 0,
            "lineup": 1,
            "lcName": "Flowing Nightglow",
            "lcRank": 1,
            "2pc": "Prisoner in Deep Confinement",
            "4pc": "Musketeer of Wild Wheat",
            "planar": "Fleet of the Ageless",
            "HeadMain": "HPFlat",
            "Head1Stat": "SPDFlat",
            "Head1Value": 5,
            "Head2Stat": "CritDamageBase",
            "Head2Value": 0.05832,
            "Head3Stat": "EffectHitRate",
            "Head3Value": 0.08208,
            "Head4Stat": "DamageBreak",
            "Head4Value": 0.162,
            "HandsMain": "ATKFlat",
            "Hands1Stat": "HPFlat",
            "Hands1Value": 118.54514,
            "Hands2Stat": "SPDFlat",
            "Hands2Value": 6,
            "Hands3Stat": "CritRateBase",
            "Hands3Value": 0.02592,
            "Hands4Stat": "DamageBreak",
            "Hands4Value": 0.05832,
            "BodyMain": "ATK%",
            "Body1Stat": "ATKFlat",
            "Body1Value": 33.870035,
            "Body2Stat": "DEFFlat",
            "Body2Value": 16.935019,
            "Body3Stat": "CritRateBase",
            "Body3Value": 0.02916,
            "Body4Stat": "EffectRES",
            "Body4Value": 0.1512,
            "FeetMain": "ATK%",
            "Feet1Stat": "HPFlat",
            "Feet1Value": 110.07763,
            "Feet2Stat": "HP%",
            "Feet2Value": 0.07344,
            "Feet3Stat": "SPDFlat",
            "Feet3Value": 4,
            "Feet4Stat": "EffectRES",
            "Feet4Value": 0.07776,
            "SphereMain": "ATK%",
            "Sphere1Stat": "ATKFlat",
            "Sphere1Value": 35.986912,
            "Sphere2Stat": "DEF%",
            "Sphere2Value": 0.1512,
            "Sphere3Stat": "EffectRES",
            "Sphere3Value": 0.06912,
            "Sphere4Stat": "DamageBreak",
            "Sphere4Value": 0.0648,
            "RopeMain": "EnergyRegenRate",
            "Rope1Stat": "ATKFlat",
            "Rope1Value": 35.986912,
            "Rope2Stat": "DEFFlat",
            "Rope2Value": 19.051896,
            "Rope3Stat": "EffectHitRate",
            "Rope3Value": 0.11232,
            "Rope4Stat": "DamageBreak",
            "Rope4Value": 0.17496
        }
    },
    // "boss": {
    //     "currentBoss": "VoidBattle_Devourer_Hard",
    //     "enemyType": "Colossus",
    //     "currentBossPart": "",
    //     "currentBossPartType": "",
    //     "currentBossPartWP": 0,
    // },
    // "teamBuffs": {
    //     "stats": {},
    //     "tags": [],
    //     "complexBonus": [],
    // },
    // "enemyBuffs": {
    //     "stats": {},
    //     "tags": [],
    // },
    // "currentDisplayMode": 1,
    // "weaponCritCeiling": 0,
    // "skillCritCeiling": 0,
    // "ambushImmobileSlider": 100,
    // "weakPointHitRate": 100,
    // "useWeakspots": true,
    // "useCrits": true,
    // "useFirearmPhysical": true,
    // "playerCount": 1,

}