const tooltipStorage = {
    //"elementID": "tooltip text here",

    graphTooltips: {},//cause these are gonna get deleted every time we make a new graph, would rather make em an object to clear easily, within storage


    "threadCountTooltip": "This setting will determine how many Web Workers will be created to handle the search. A general rule of thumb, is that one Worker can be created for each CPU core you have.<br><br>However, be aware that more Workers in play also means more memory will be used, so monitor your memory usage and decide a default count that is best for you.",
    "smartSkipEnable": "Smart skips will evaluate every combination as they come up, and determine whether that combo should even be checked at all or if it has no hope of ever being an optimal combination and should be skipped.<br><br>An example would be an item that grants DEF but on Kafka: since Kafka doesnt really care about DEF, there's no chance in hell that that item would be good for her, and that entire combination can be skipped.<br><br>HOWEVER, because the needs of a character are dynamic based on the gear or allies used in the team, smart skips WILL take that into account, so say a character needs ATK and Kafka is in the team, and Kafka can provide ATK from her trace but only if the ally has enough EHR - this means the ally will now look for EHR in combinations in order to achieve the ATK bonus from her.",
    "evaluatedExplainer": "Total possible combos are not the amount of combinations that will see battle in the optimizer.<br><br>This is the amount POSSIBLE, TOTAL, including skips made from smart filters, or even skips that are made due to a mainstat conflict(say you use spd boots, spd can't roll as a substat on those boots when it is also the main stat. In this case, the total possible number of combinations is reduced if spd was a desired stat for that character).",

    "queriesBattleSettingsSummaryRowExplainer": "Clicking here will take you directly to battle settings to adjust.",
    // "queryType": "Choose what type of comparision you want to do. Leave it on abilities if you want to see ability related comparisons, or switch to Stat if you want to see character related statistics like MP or Shield/HP etc.<br><br>When left blank, the default type will be Abilities.",
    "queriesExplainToughnessBattlestart": "When attack-type techniques are used, they will often reduce the toughness of an enemy that matches a weakness unless otherwise specified.<br><br><b>HOWEVER</b> If no attack-type techniques are available in the team you're searching on, then what happens is the first character in your lineup will be the one to be considered as starting the fight, at which point a 10 toughness reduction will apply to enemies that match char1's element.<br><br>This toggle decides, if no attack techniques are used, do you still want that toughness reduction.",
    "queriesExplainBattlesWon": "When enabled, battles that you failed for either not completing the battle, or having all ally character die, will be excluded from results.<br><br>Note that if you're using the search to try and measure DMG against unkillable enemies, then no results will be found when using this.",
    "queriesRollBundlingExplainer": "When looping over the possible substat combinations per character, this setting determines how many rolls will be incremented PER CHECK.<br><br>So if we have a SPD roll, when check the next value on it - are we moving up 2 rolls or 1 roll?<br><br><b><i>This setting has one of the LARGEST impacts on search speeds</i></b>, as searching by 1 EXPLODES the possible combinations, but searching by 1 roll increments might help show breakpoints more accurately. The chances of it actually mattering though, are basically nonexistent. Please do not search by 1.",
    "queries2pcMixingExplainer": "When toggled on, this will allow the search to iterate over mixed relic sets. Without this enabled, the search will ONLY look at 4pc combinations.<br><b>This has a TREMENDOUS impact on search speeds</b>, reducing the possible unfiltered combinations on a character. With proper fillters, the impact isn't as large.",
    "queriesRelicRollValueExplainer": "THIS HAS NO IMPACT ON SEARCH SPEED.<br><br>Relics, when generated in game or when rolling for a new substat value, have a randomized range with 3 possible values: low, mid, and high.<br>This setting only exists so people can dictate which value they want in the search for ALL of their substat combinations.",
    "queriesRollsPerRelicExplainer": "This will dictate whether relics used in the search will be 3-line relics or 4-line relics, changing the total possible added rolls on the relic from 4 to 5 respectively.<br><br>This means the maximum substat rolls possible on a character goes from 24 up to 30<br><b>This has an impact on search speeds</b>, by increasing the number of combinations possible.",
    "queriesUsableBaseRollExplainer": "THIS HAS NO IMPACT ON SEARCH SPEED.<br><br>This setting dictates that of 24 total base rolls(4 stats per relic, 6 relics total) how many of the BASE rolls, are usable substats.<br><br>By default, I assume that between those 24 total base stats, half of them are usable stats(each piece has at least 2) otherwise you're probably throwing those pieces away.<br><br><b>Please do not mistake this for ADDED substat rolls, this is only for rolls that you START with before ranking up.</b>",
    "queriesFailedRollExplainer": "This setting dictates of the maximum possible ADDED rolls on each individual relic, how many FAIL to get on a usable substat?<br><br>For example, say we have a 3-line relic, this means we have 4 added rolls possible on this relic.<br>If I say I have 1 failed roll per relic, that means only 3 added rolls will actually take place per relic. If this were a 4-liner, then that would mean 4 total take place instead of 5.<br><br>This setting defaults to an assumption of 1 failed added roll per relic, but you can change it if you want to greed.<br><br>Lowering this setting to 0 failed rolls will help you better understand how to greed for your character, but just understand that <b>it will increase the total number of combinations, and in turn the total time required to complete this search.</b>",
    "queriesMinimumAddedRollExplainer": "This determines of the 4 desired substats on a character, how many rolls are guaranteed to be distributed to each of them, from the end-total added roll pool.<br><br>As an example, say below your total added roll pool shows 18 rolls. When this value is 1, that means of the 18 possible added rolls, we take out 4*1=4 of them and spread them equally on the 4 desired stats, virtually reducing the added roll pool from 18 to 14.<br><b>This has a tremendous impact on search speed, drastically reducing the number of combinations.</b>",
    "queriesKeepLCSuperimpositionExplainer": "Say you got lucky and you double-pulled a 5star lightcone. Now that lightcone is at superimposition rank 2.<br><br><b>If you have that lightcone equipped on your character in the team view</b>, when that same lightcone is iterated over in the search combinations, do you want to keep that rank for that lightcone ONLY, or do you want the search to still enforce whatever 5star superimposition you set.",

    "finalBaseRollsExplainer": "This is out of 24, how many BASE substat rolls across all relics, are usable substats.<br>This amount is modified below.",
    "finalAddedRollsExplainer": "This represents how many ADDED substat rolls will land on usable substats, across all relics, using your current settings.<br><br>This value is obtained by doing the following:<br><b>(rollsPerRelic - failedPerRelic) * 6</b>",
    "finalTotalRollsExplainer": "This number is simply the final base usable rolls, added together with the final added usable rolls.<br><br><b>Why bother even showing this number?</b><br>Because for some reason, theorycrafters across reddit, google sheets, and everywhere else, have a hard-on for very specific quantities of end-total usable subs.<br>If you can't tell, I think it's a fucking stupid metric.",

    "rotationsDisableCharacterToggleExplainer": "By disabling the character here, the character will be excluded from all battle simulations other than inside the optimizer because if you are optimizing for less than 4 characters what the actual fuck is the point?<br>Obviously a larger appeal for this is for debugging purposes.<br><br>Please note that <b>Character 1 can never be disabled, even if toggled on.</b>",


};  
