const vashWavePresets = {
    "Glorp-ard": [
        [
            {"image":null,"entry":null,"name":"Glorp Elite","lvl":95,"hpBars":1,"toughnessBars":1,"stats":
                [0,95,395960000,0,0,0,718,0,0,0,1150,0,0,132,0,0,0,0,0,0,0,0,0.3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,100,0,0,0,0,0,0,0,0,0,0.2,0,0,0,0,0,0,0,0.2,0,0.2,0,0.2,0,0,0,1,0,1,0,1,0,0],"enemyTypeAttack":"Single Target","enemyType":"elite","weaknessOverrides":{"Lightning":true,"Wind":true,"Quantum":true},"resistantTo":{"Lightning":0,"Wind":0,"Quantum":0},"finalStats":{"ATKBaseFinal":718,"ATKBonusPercent":0,"ATKBonusFlat":0,"ATKFinal":718,"HPBaseFinal":395960000,"HPBonusPercent":0,"HPBonusFlat":0,"HPFinal":395960000,"DEFBaseFinal":1150,"DEFBonusPercent":0,"DEFBonusFlat":0,"DEFFinal":1150,"SPDBaseFinal":132,"SPDBonusPercent":0,"SPDBonusFlat":0,"SPDFinal":132,"SPDActionValue":75.75757575757575,"CritRateFinal":0,"CritDamageFinal":0}},{"image":null,"entry":null,"name":"Glorp-ard","lvl":95,"hpBars":1,"toughnessBars":1,"stats":[0,95,400000000,0,0,0,718,0,0,0,1150,0,0,158,0,0,0,0,0,0,0,0,0.4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,140,0,0,0,0,0,0,0,0,0,0.2,0,0.2,0,0,0,0,0,0.2,0,0,0,0.2,0,0,0,1,1,0,0,1,0,0],"enemyTypeAttack":"AoE","enemyType":"boss","weaknessOverrides":{"Fire":true,"Lightning":true,"Wind":true},"resistantTo":{"Fire":0,"Lightning":0,"Wind":0},"finalStats":{"ATKBaseFinal":718,"ATKBonusPercent":0,"ATKBonusFlat":0,"ATKFinal":718,"HPBaseFinal":400000000,"HPBonusPercent":0,"HPBonusFlat":0,"HPFinal":400000000,"DEFBaseFinal":1150,"DEFBonusPercent":0,"DEFBonusFlat":0,"DEFFinal":1150,"SPDBaseFinal":158,"SPDBonusPercent":0,"SPDBonusFlat":0,"SPDFinal":158,"SPDActionValue":63.29113924050633,"CritRateFinal":0,"CritDamageFinal":0}},{"image":null,"entry":null,"name":"Glorp Elite","lvl":95,"hpBars":1,"toughnessBars":1,"stats":[0,95,395960000,0,0,0,718,0,0,0,1150,0,0,132,0,0,0,0,0,0,0,0,0.3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,100,0,0,0,0,0,0,0,0,0,0.2,0,0,0,0,0,0,0,0.2,0,0.2,0,0.2,0,0,0,1,0,1,0,1,0,0],"enemyTypeAttack":"Single Target","enemyType":"elite","weaknessOverrides":{"Lightning":true,"Wind":true,"Quantum":true},"resistantTo":{"Lightning":0,"Wind":0,"Quantum":0},"finalStats":{"ATKBaseFinal":718,"ATKBonusPercent":0,"ATKBonusFlat":0,"ATKFinal":718,"HPBaseFinal":395960000,"HPBonusPercent":0,"HPBonusFlat":0,"HPFinal":395960000,"DEFBaseFinal":1150,"DEFBonusPercent":0,"DEFBonusFlat":0,"DEFFinal":1150,"SPDBaseFinal":132,"SPDBonusPercent":0,"SPDBonusFlat":0,"SPDFinal":132,"SPDActionValue":75.75757575757575,"CritRateFinal":0,"CritDamageFinal":0}}]
    ],
    "quantumDoggo": [
        [
            {
                "image": null,
                "entry": null,
                "name": "Gunner Guy",
                "lvl": 66,
                "hpBars": 1,
                "toughnessBars": 1,
                "stats": [
                    0,
                    66,
                    395960,
                    0,
                    0,
                    0,
                    718,
                    0,
                    0,
                    0,
                    860,
                    0,
                    0,
                    91,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0.3,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    30,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0.2,
                    0,
                    0.2,
                    0,
                    0,
                    0,
                    0.2,
                    0,
                    0,
                    0,
                    0.2,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    0,
                    1,
                    1
                ],
                "enemyTypeAttack": "Bounce",
                "enemyType": "minion",
                "weaknessOverrides": {
                    "Physical": true,
                    "Ice": true,
                    "Wind": true
                },
                "resistantTo": {
                    "Physical": 0,
                    "Ice": 0,
                    "Wind": 0
                },
                "finalStats": {
                    "ATKBaseFinal": 718,
                    "ATKBonusPercent": 0,
                    "ATKBonusFlat": 0,
                    "ATKFinal": 718,
                    "HPBaseFinal": 395960,
                    "HPBonusPercent": 0,
                    "HPBonusFlat": 0,
                    "HPFinal": 395960,
                    "DEFBaseFinal": 860,
                    "DEFBonusPercent": 0,
                    "DEFBonusFlat": 0,
                    "DEFFinal": 860,
                    "SPDBaseFinal": 91,
                    "SPDBonusPercent": 0,
                    "SPDBonusFlat": 0,
                    "SPDFinal": 91,
                    "SPDActionValue": 109.89010989010988,
                    "CritRateFinal": 0,
                    "CritDamageFinal": 0
                }
            },
            {
                "image": null,
                "entry": null,
                "name": "Quantum Dog",
                "lvl": 66,
                "hpBars": 1,
                "toughnessBars": 1,
                "stats": [
                    0,
                    66,
                    406770,
                    0,
                    0,
                    0,
                    718,
                    0,
                    0,
                    0,
                    860,
                    0,
                    0,
                    130,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0.3,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    30,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0.2,
                    0,
                    0,
                    0,
                    0.2,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0.2,
                    0,
                    0.2,
                    0,
                    0,
                    1,
                    1,
                    0,
                    1,
                    0,
                    0,
                    0
                ],
                "enemyTypeAttack": "Single Target",
                "enemyType": "minion",
                "weaknessOverrides": {
                    "Ice": true,
                    "Lightning": true,
                    "Quantum": true
                },
                "resistantTo": {
                    "Ice": 0,
                    "Lightning": 0,
                    "Quantum": 0
                },
                "finalStats": {
                    "ATKBaseFinal": 718,
                    "ATKBonusPercent": 0,
                    "ATKBonusFlat": 0,
                    "ATKFinal": 718,
                    "HPBaseFinal": 406770,
                    "HPBonusPercent": 0,
                    "HPBonusFlat": 0,
                    "HPFinal": 406770,
                    "DEFBaseFinal": 860,
                    "DEFBonusPercent": 0,
                    "DEFBonusFlat": 0,
                    "DEFFinal": 860,
                    "SPDBaseFinal": 130,
                    "SPDBonusPercent": 0,
                    "SPDBonusFlat": 0,
                    "SPDFinal": 130,
                    "SPDActionValue": 76.92307692307692,
                    "CritRateFinal": 0,
                    "CritDamageFinal": 0
                }
            },
            {
                "image": null,
                "entry": null,
                "name": "Gunner Guy",
                "lvl": 66,
                "hpBars": 1,
                "toughnessBars": 1,
                "stats": [
                    0,
                    66,
                    395960,
                    0,
                    0,
                    0,
                    718,
                    0,
                    0,
                    0,
                    860,
                    0,
                    0,
                    91,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0.3,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    30,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0.2,
                    0,
                    0.2,
                    0,
                    0,
                    0,
                    0.2,
                    0,
                    0,
                    0,
                    0.2,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    0,
                    1,
                    1
                ],
                "enemyTypeAttack": "Bounce",
                "enemyType": "minion",
                "weaknessOverrides": {
                    "Physical": true,
                    "Ice": true,
                    "Wind": true
                },
                "resistantTo": {
                    "Physical": 0,
                    "Ice": 0,
                    "Wind": 0
                },
                "finalStats": {
                    "ATKBaseFinal": 718,
                    "ATKBonusPercent": 0,
                    "ATKBonusFlat": 0,
                    "ATKFinal": 718,
                    "HPBaseFinal": 395960,
                    "HPBonusPercent": 0,
                    "HPBonusFlat": 0,
                    "HPFinal": 395960,
                    "DEFBaseFinal": 860,
                    "DEFBonusPercent": 0,
                    "DEFBonusFlat": 0,
                    "DEFFinal": 860,
                    "SPDBaseFinal": 91,
                    "SPDBonusPercent": 0,
                    "SPDBonusFlat": 0,
                    "SPDFinal": 91,
                    "SPDActionValue": 109.89010989010988,
                    "CritRateFinal": 0,
                    "CritDamageFinal": 0
                }
            }
        ],
        [
            {
                "image": null,
                "entry": null,
                "name": "Gunner Guy",
                "lvl": 66,
                "hpBars": 1,
                "toughnessBars": 1,
                "stats": [
                    0,
                    66,
                    395960000,
                    0,
                    0,
                    0,
                    718,
                    0,
                    0,
                    0,
                    860,
                    0,
                    0,
                    91,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0.3,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    30,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0.2,
                    0,
                    0.2,
                    0,
                    0,
                    0,
                    0.2,
                    0,
                    0,
                    0,
                    0.2,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    0,
                    1,
                    1
                ],
                "enemyTypeAttack": "Bounce",
                "enemyType": "minion",
                "weaknessOverrides": {
                    "Physical": true,
                    "Ice": true,
                    "Wind": true
                },
                "resistantTo": {
                    "Physical": 0,
                    "Ice": 0,
                    "Wind": 0
                },
                "finalStats": {
                    "ATKBaseFinal": 718,
                    "ATKBonusPercent": 0,
                    "ATKBonusFlat": 0,
                    "ATKFinal": 718,
                    "HPBaseFinal": 395960000,
                    "HPBonusPercent": 0,
                    "HPBonusFlat": 0,
                    "HPFinal": 395960000,
                    "DEFBaseFinal": 860,
                    "DEFBonusPercent": 0,
                    "DEFBonusFlat": 0,
                    "DEFFinal": 860,
                    "SPDBaseFinal": 91,
                    "SPDBonusPercent": 0,
                    "SPDBonusFlat": 0,
                    "SPDFinal": 91,
                    "SPDActionValue": 109.89010989010988,
                    "CritRateFinal": 0,
                    "CritDamageFinal": 0
                }
            },
            {
                "image": null,
                "entry": null,
                "name": "Quantum Dog",
                "lvl": 66,
                "hpBars": 1,
                "toughnessBars": 1,
                "stats": [
                    0,
                    66,
                    406770000,
                    0,
                    0,
                    0,
                    718,
                    0,
                    0,
                    0,
                    860,
                    0,
                    0,
                    130,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0.3,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    30,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0.2,
                    0,
                    0,
                    0,
                    0.2,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0.2,
                    0,
                    0.2,
                    0,
                    0,
                    1,
                    1,
                    0,
                    1,
                    0,
                    0,
                    0
                ],
                "enemyTypeAttack": "Single Target",
                "enemyType": "minion",
                "weaknessOverrides": {
                    "Ice": true,
                    "Lightning": true,
                    "Quantum": true
                },
                "resistantTo": {
                    "Ice": 0,
                    "Lightning": 0,
                    "Quantum": 0
                },
                "finalStats": {
                    "ATKBaseFinal": 718,
                    "ATKBonusPercent": 0,
                    "ATKBonusFlat": 0,
                    "ATKFinal": 718,
                    "HPBaseFinal": 406770000,
                    "HPBonusPercent": 0,
                    "HPBonusFlat": 0,
                    "HPFinal": 406770000,
                    "DEFBaseFinal": 860,
                    "DEFBonusPercent": 0,
                    "DEFBonusFlat": 0,
                    "DEFFinal": 860,
                    "SPDBaseFinal": 130,
                    "SPDBonusPercent": 0,
                    "SPDBonusFlat": 0,
                    "SPDFinal": 130,
                    "SPDActionValue": 76.92307692307692,
                    "CritRateFinal": 0,
                    "CritDamageFinal": 0
                }
            },
            {
                "image": null,
                "entry": null,
                "name": "Gunner Guy",
                "lvl": 66,
                "hpBars": 1,
                "toughnessBars": 1,
                "stats": [
                    0,
                    66,
                    395960000,
                    0,
                    0,
                    0,
                    718,
                    0,
                    0,
                    0,
                    860,
                    0,
                    0,
                    91,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0.3,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    30,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0.2,
                    0,
                    0.2,
                    0,
                    0,
                    0,
                    0.2,
                    0,
                    0,
                    0,
                    0.2,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    0,
                    1,
                    1
                ],
                "enemyTypeAttack": "Bounce",
                "enemyType": "minion",
                "weaknessOverrides": {
                    "Physical": true,
                    "Ice": true,
                    "Wind": true
                },
                "resistantTo": {
                    "Physical": 0,
                    "Ice": 0,
                    "Wind": 0
                },
                "finalStats": {
                    "ATKBaseFinal": 718,
                    "ATKBonusPercent": 0,
                    "ATKBonusFlat": 0,
                    "ATKFinal": 718,
                    "HPBaseFinal": 395960000,
                    "HPBonusPercent": 0,
                    "HPBonusFlat": 0,
                    "HPFinal": 395960000,
                    "DEFBaseFinal": 860,
                    "DEFBonusPercent": 0,
                    "DEFBonusFlat": 0,
                    "DEFFinal": 860,
                    "SPDBaseFinal": 91,
                    "SPDBonusPercent": 0,
                    "SPDBonusFlat": 0,
                    "SPDFinal": 91,
                    "SPDActionValue": 109.89010989010988,
                    "CritRateFinal": 0,
                    "CritDamageFinal": 0
                }
            }
        ]
    ],
    "MoX6": []
}