const vashWavePresets = {
    "Glorp-ard": [
        [
          {
            "image": null,
            "entry": null,
            "name": "Glorp Elite",
            "lvl": 95,
            "hpBars": 1,
            "toughnessBars": 1,
            "stats": [
              0,
              95,
              395960000,
              0,
              0,
              0,
              718,
              0,
              0,
              0,
              1150,
              0,
              0,
              132,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0.3,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              100,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0.2,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0.2,
              0,
              0.2,
              0,
              0.2,
              0,
              0,
              0,
              1,
              0,
              1,
              0,
              1,
              0,
              0,
              0,
              0,
              0
            ],
            "enemyTypeAttack": "Single Target",
            "enemyType": "elite",
            "energyGain": 10,
            "weaknessOverrides": {
              "Lightning": true,
              "Wind": true,
              "Quantum": true
            },
            "resistantTo": {
              "Physical": 20,
              "Fire": 20,
              "Ice": 20,
              "Lightning": 0,
              "Wind": 0,
              "Quantum": 0,
              "Imaginary": 20
            },
            "finalStats": {
              "ATKBaseFinal": 718,
              "ATKBonusPercent": 0,
              "ATKBonusFlat": 0,
              "ATKFinal": 718,
              "HPBaseFinal": 395960000,
              "HPBonusPercent": 0,
              "HPBonusFlat": 0,
              "HPFinal": 395960000,
              "DEFBaseFinal": 1150,
              "DEFBonusPercent": 0,
              "DEFBonusFlat": 0,
              "DEFFinal": 1150,
              "SPDBaseFinal": 132,
              "SPDBonusPercent": 0,
              "SPDBonusFlat": 0,
              "SPDFinal": 132,
              "SPDActionValue": 75.75757575757575,
              "CritRateFinal": 0,
              "CritDamageFinal": 0
            }
          },
          {
            "image": null,
            "entry": null,
            "name": "Glorp-ard",
            "lvl": 95,
            "hpBars": 1,
            "toughnessBars": 1,
            "stats": [
              0,
              95,
              400000000,
              0,
              0,
              0,
              718,
              0,
              0,
              0,
              1150,
              0,
              0,
              158,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0.4,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              140,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0.2,
              0,
              0.2,
              0,
              0,
              0,
              0,
              0,
              0.2,
              0,
              0,
              0,
              0.2,
              0,
              0,
              0,
              1,
              1,
              0,
              0,
              1,
              0,
              0,
              0,
              0,
              0
            ],
            "enemyTypeAttack": "AoE",
            "enemyType": "boss",
            "energyGain": 10,
            "weaknessOverrides": {
              "Fire": true,
              "Lightning": true,
              "Wind": true
            },
            "resistantTo": {
              "Physical": 20,
              "Fire": 0,
              "Ice": 20,
              "Lightning": 0,
              "Wind": 0,
              "Quantum": 20,
              "Imaginary": 20
            },
            "finalStats": {
              "ATKBaseFinal": 718,
              "ATKBonusPercent": 0,
              "ATKBonusFlat": 0,
              "ATKFinal": 718,
              "HPBaseFinal": 400000000,
              "HPBonusPercent": 0,
              "HPBonusFlat": 0,
              "HPFinal": 400000000,
              "DEFBaseFinal": 1150,
              "DEFBonusPercent": 0,
              "DEFBonusFlat": 0,
              "DEFFinal": 1150,
              "SPDBaseFinal": 158,
              "SPDBonusPercent": 0,
              "SPDBonusFlat": 0,
              "SPDFinal": 158,
              "SPDActionValue": 63.29113924050633,
              "CritRateFinal": 0,
              "CritDamageFinal": 0
            }
          },
          {
            "image": null,
            "entry": null,
            "name": "Glorp Elite",
            "lvl": 95,
            "hpBars": 1,
            "toughnessBars": 1,
            "stats": [
              0,
              95,
              395960000,
              0,
              0,
              0,
              718,
              0,
              0,
              0,
              1150,
              0,
              0,
              132,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0.3,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              100,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0.2,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0.2,
              0,
              0.2,
              0,
              0.2,
              0,
              0,
              0,
              1,
              0,
              1,
              0,
              1,
              0,
              0,
              0,
              0,
              0
            ],
            "enemyTypeAttack": "Single Target",
            "enemyType": "elite",
            "energyGain": 10,
            "weaknessOverrides": {
              "Lightning": true,
              "Wind": true,
              "Quantum": true
            },
            "resistantTo": {
              "Physical": 20,
              "Fire": 20,
              "Ice": 20,
              "Lightning": 0,
              "Wind": 0,
              "Quantum": 0,
              "Imaginary": 20
            },
            "finalStats": {
              "ATKBaseFinal": 718,
              "ATKBonusPercent": 0,
              "ATKBonusFlat": 0,
              "ATKFinal": 718,
              "HPBaseFinal": 395960000,
              "HPBonusPercent": 0,
              "HPBonusFlat": 0,
              "HPFinal": 395960000,
              "DEFBaseFinal": 1150,
              "DEFBonusPercent": 0,
              "DEFBonusFlat": 0,
              "DEFFinal": 1150,
              "SPDBaseFinal": 132,
              "SPDBonusPercent": 0,
              "SPDBonusFlat": 0,
              "SPDFinal": 132,
              "SPDActionValue": 75.75757575757575,
              "CritRateFinal": 0,
              "CritDamageFinal": 0
            }
          }
        ]
    ],
    "quantumDoggo": [
        [
          {
            "image": null,
            "entry": null,
            "name": "Gunner Guy",
            "lvl": 66,
            "hpBars": 1,
            "toughnessBars": 1,
            "stats": [
              0,
              66,
              395960,
              0,
              0,
              0,
              718,
              0,
              0,
              0,
              860,
              0,
              0,
              91,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0.3,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              30,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0.2,
              0,
              0.2,
              0,
              0,
              0,
              0.2,
              0,
              0,
              0,
              0.2,
              0,
              0,
              0,
              0,
              1,
              0,
              0,
              0,
              0,
              1,
              1,
              0,
              0,
              0,
              0
            ],
            "enemyTypeAttack": "Single Target",
            "enemyType": "minion",
            "energyGain": 10,
            "weaknessOverrides": {
              "Physical": true,
              "Ice": true,
              "Wind": true
            },
            "resistantTo": {
              "Physical": 0,
              "Fire": 20,
              "Ice": 0,
              "Lightning": 20,
              "Wind": 0,
              "Quantum": 20,
              "Imaginary": 20
            },
            "finalStats": {
              "ATKBaseFinal": 718,
              "ATKBonusPercent": 0,
              "ATKBonusFlat": 0,
              "ATKFinal": 718,
              "HPBaseFinal": 395960,
              "HPBonusPercent": 0,
              "HPBonusFlat": 0,
              "HPFinal": 395960,
              "DEFBaseFinal": 860,
              "DEFBonusPercent": 0,
              "DEFBonusFlat": 0,
              "DEFFinal": 860,
              "SPDBaseFinal": 91,
              "SPDBonusPercent": 0,
              "SPDBonusFlat": 0,
              "SPDFinal": 91,
              "SPDActionValue": 109.89010989010988,
              "CritRateFinal": 0,
              "CritDamageFinal": 0
            }
          },
          {
            "image": null,
            "entry": null,
            "name": "Quantum Dog",
            "lvl": 66,
            "hpBars": 1,
            "toughnessBars": 1,
            "stats": [
              0,
              66,
              406770,
              0,
              0,
              0,
              718,
              0,
              0,
              0,
              860,
              0,
              0,
              130,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0.3,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              30,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0.2,
              0,
              0,
              0,
              0.2,
              0,
              0,
              0,
              0,
              0,
              0.2,
              0,
              0.2,
              0,
              0,
              1,
              1,
              0,
              1,
              0,
              0,
              0,
              0,
              0,
              0,
              0
            ],
            "enemyTypeAttack": "Single Target",
            "enemyType": "minion",
            "energyGain": 10,
            "weaknessOverrides": {
              "Ice": true,
              "Lightning": true,
              "Quantum": true
            },
            "resistantTo": {
              "Physical": 20,
              "Fire": 20,
              "Ice": 0,
              "Lightning": 0,
              "Wind": 20,
              "Quantum": 0,
              "Imaginary": 20
            },
            "finalStats": {
              "ATKBaseFinal": 718,
              "ATKBonusPercent": 0,
              "ATKBonusFlat": 0,
              "ATKFinal": 718,
              "HPBaseFinal": 406770,
              "HPBonusPercent": 0,
              "HPBonusFlat": 0,
              "HPFinal": 406770,
              "DEFBaseFinal": 860,
              "DEFBonusPercent": 0,
              "DEFBonusFlat": 0,
              "DEFFinal": 860,
              "SPDBaseFinal": 130,
              "SPDBonusPercent": 0,
              "SPDBonusFlat": 0,
              "SPDFinal": 130,
              "SPDActionValue": 76.92307692307692,
              "CritRateFinal": 0,
              "CritDamageFinal": 0
            }
          },
          {
            "image": null,
            "entry": null,
            "name": "Gunner Guy",
            "lvl": 66,
            "hpBars": 1,
            "toughnessBars": 1,
            "stats": [
              0,
              66,
              395960,
              0,
              0,
              0,
              718,
              0,
              0,
              0,
              860,
              0,
              0,
              91,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0.3,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              30,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0.2,
              0,
              0.2,
              0,
              0,
              0,
              0.2,
              0,
              0,
              0,
              0.2,
              0,
              0,
              0,
              0,
              1,
              0,
              0,
              0,
              0,
              1,
              1,
              0,
              0,
              0,
              0
            ],
            "enemyTypeAttack": "Single Target",
            "enemyType": "minion",
            "energyGain": 10,
            "weaknessOverrides": {
              "Physical": true,
              "Ice": true,
              "Wind": true
            },
            "resistantTo": {
              "Physical": 0,
              "Fire": 20,
              "Ice": 0,
              "Lightning": 20,
              "Wind": 0,
              "Quantum": 20,
              "Imaginary": 20
            },
            "finalStats": {
              "ATKBaseFinal": 718,
              "ATKBonusPercent": 0,
              "ATKBonusFlat": 0,
              "ATKFinal": 718,
              "HPBaseFinal": 395960,
              "HPBonusPercent": 0,
              "HPBonusFlat": 0,
              "HPFinal": 395960,
              "DEFBaseFinal": 860,
              "DEFBonusPercent": 0,
              "DEFBonusFlat": 0,
              "DEFFinal": 860,
              "SPDBaseFinal": 91,
              "SPDBonusPercent": 0,
              "SPDBonusFlat": 0,
              "SPDFinal": 91,
              "SPDActionValue": 109.89010989010988,
              "CritRateFinal": 0,
              "CritDamageFinal": 0
            }
          }
        ]
    ],
    "MoX6": [
      [
        {
          "image": null,
          "entry": null,
          "name": "Fish boll",
          "lvl": 90,
          "hpBars": 1,
          "toughnessBars": 1,
          "stats": [
            0,
            90,
            39595.91,
            0,
            0,
            0,
            662.785,
            0,
            0,
            0,
            1100,
            0,
            0,
            132,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0.2,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            20,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0.2,
            0,
            0.2,
            0,
            0,
            0,
            0.2,
            0,
            0.2,
            0,
            0,
            0,
            0,
            0,
            1,
            0,
            0,
            1,
            0,
            1,
            0,
            0,
            0,
            0,
            0
          ],
          "enemyTypeAttack": "Single Target",
          "enemyType": "minion",
          "energyGain": 10,
          "weaknessOverrides": {
            "Physical": true,
            "Lightning": true,
            "Imaginary": true
          },
          "resistantTo": {
            "Physical": 0,
            "Fire": 20,
            "Ice": 20,
            "Lightning": 0,
            "Wind": 20,
            "Quantum": 20,
            "Imaginary": 0
          },
          "finalStats": {
            "ATKBaseFinal": 662.785,
            "ATKBonusPercent": 0,
            "ATKBonusFlat": 0,
            "ATKFinal": 662.785,
            "HPBaseFinal": 39595.91,
            "HPBonusPercent": 0,
            "HPBonusFlat": 0,
            "HPFinal": 39595.91,
            "DEFBaseFinal": 1100,
            "DEFBonusPercent": 0,
            "DEFBonusFlat": 0,
            "DEFFinal": 1100,
            "SPDBaseFinal": 132,
            "SPDBonusPercent": 0,
            "SPDBonusFlat": 0,
            "SPDFinal": 132,
            "SPDActionValue": 75.75757575757575,
            "CritRateFinal": 0,
            "CritDamageFinal": 0
          }
        },
        {
          "image": null,
          "entry": null,
          "name": "Sword guy",
          "lvl": 90,
          "hpBars": 1,
          "toughnessBars": 1,
          "stats": [
            0,
            90,
            31676.728,
            0,
            0,
            0,
            662.785,
            0,
            0,
            0,
            1100,
            0,
            0,
            109.56,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0.2,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            20,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0.2,
            0,
            0,
            0,
            0.2,
            0,
            0.2,
            0,
            0,
            0,
            0,
            0,
            0.2,
            0,
            0,
            1,
            0,
            1,
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ],
          "enemyTypeAttack": "Single Target",
          "enemyType": "minion",
          "energyGain": 10,
          "weaknessOverrides": {
            "Fire": true,
            "Ice": true,
            "Quantum": true
          },
          "resistantTo": {
            "Physical": 20,
            "Fire": 0,
            "Ice": 0,
            "Lightning": 20,
            "Wind": 20,
            "Quantum": 0,
            "Imaginary": 20
          },
          "finalStats": {
            "ATKBaseFinal": 662.785,
            "ATKBonusPercent": 0,
            "ATKBonusFlat": 0,
            "ATKFinal": 662.785,
            "HPBaseFinal": 31676.728,
            "HPBonusPercent": 0,
            "HPBonusFlat": 0,
            "HPFinal": 31676.728,
            "DEFBaseFinal": 1100,
            "DEFBonusPercent": 0,
            "DEFBonusFlat": 0,
            "DEFFinal": 1100,
            "SPDBaseFinal": 109.56,
            "SPDBonusPercent": 0,
            "SPDBonusFlat": 0,
            "SPDFinal": 109.56,
            "SPDActionValue": 91.27418765972983,
            "CritRateFinal": 0,
            "CritDamageFinal": 0
          }
        },
        {
          "image": null,
          "entry": null,
          "name": "Fish boll",
          "lvl": 90,
          "hpBars": 1,
          "toughnessBars": 1,
          "stats": [
            0,
            90,
            39595.91,
            0,
            0,
            0,
            662.785,
            0,
            0,
            0,
            1100,
            0,
            0,
            132,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0.2,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            20,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0.2,
            0,
            0.2,
            0,
            0,
            0,
            0.2,
            0,
            0.2,
            0,
            0,
            0,
            0,
            0,
            1,
            0,
            0,
            1,
            0,
            1,
            0,
            0,
            0,
            0,
            0
          ],
          "enemyTypeAttack": "Single Target",
          "enemyType": "minion",
          "energyGain": 10,
          "weaknessOverrides": {
            "Physical": true,
            "Lightning": true,
            "Imaginary": true
          },
          "resistantTo": {
            "Physical": 0,
            "Fire": 20,
            "Ice": 20,
            "Lightning": 0,
            "Wind": 20,
            "Quantum": 20,
            "Imaginary": 0
          },
          "finalStats": {
            "ATKBaseFinal": 662.785,
            "ATKBonusPercent": 0,
            "ATKBonusFlat": 0,
            "ATKFinal": 662.785,
            "HPBaseFinal": 39595.91,
            "HPBonusPercent": 0,
            "HPBonusFlat": 0,
            "HPFinal": 39595.91,
            "DEFBaseFinal": 1100,
            "DEFBonusPercent": 0,
            "DEFBonusFlat": 0,
            "DEFFinal": 1100,
            "SPDBaseFinal": 132,
            "SPDBonusPercent": 0,
            "SPDBonusFlat": 0,
            "SPDFinal": 132,
            "SPDActionValue": 75.75757575757575,
            "CritRateFinal": 0,
            "CritDamageFinal": 0
          }
        },
        {
          "image": null,
          "entry": null,
          "name": "Sword guy",
          "lvl": 90,
          "hpBars": 1,
          "toughnessBars": 1,
          "stats": [
            0,
            90,
            31676.728,
            0,
            0,
            0,
            662.785,
            0,
            0,
            0,
            1100,
            0,
            0,
            109.56,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0.2,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            20,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0.2,
            0,
            0,
            0,
            0.2,
            0,
            0.2,
            0,
            0,
            0,
            0,
            0,
            0.2,
            0,
            0,
            1,
            0,
            1,
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ],
          "enemyTypeAttack": "Single Target",
          "enemyType": "minion",
          "energyGain": 10,
          "weaknessOverrides": {
            "Fire": true,
            "Ice": true,
            "Quantum": true
          },
          "resistantTo": {
            "Physical": 20,
            "Fire": 0,
            "Ice": 0,
            "Lightning": 20,
            "Wind": 20,
            "Quantum": 0,
            "Imaginary": 20
          },
          "finalStats": {
            "ATKBaseFinal": 662.785,
            "ATKBonusPercent": 0,
            "ATKBonusFlat": 0,
            "ATKFinal": 662.785,
            "HPBaseFinal": 31676.728,
            "HPBonusPercent": 0,
            "HPBonusFlat": 0,
            "HPFinal": 31676.728,
            "DEFBaseFinal": 1100,
            "DEFBonusPercent": 0,
            "DEFBonusFlat": 0,
            "DEFFinal": 1100,
            "SPDBaseFinal": 109.56,
            "SPDBonusPercent": 0,
            "SPDBonusFlat": 0,
            "SPDFinal": 109.56,
            "SPDActionValue": 91.27418765972983,
            "CritRateFinal": 0,
            "CritDamageFinal": 0
          }
        }
      ]
    ],
    "EchoCocolia": [
      [
        {
          "image": null,
          "entry": null,
          "name": "Echo Cocolia",
          "lvl": 82,
          "hpBars": 1,
          "toughnessBars": 1,
          "stats": [
            0,
            82,
            288445.893,
            0,
            0,
            0,
            574.414,
            0,
            0,
            0,
            1020,
            0,
            0,
            144,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0.1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            180,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0.2,
            0,
            0,
            0,
            0.4,
            0,
            0,
            0,
            0.6,
            0,
            0,
            0,
            0.4,
            0,
            0,
            0,
            1,
            1,
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ],
          "enemyTypeAttack": "Single Target",
          "enemyType": "boss",
          "energyGain": 10,
          "weaknessOverrides": {
            "Fire": true,
            "Lightning": true,
            "Quantum": true
          },
          "resistantTo": {
            "Physical": 40,
            "Fire": 0,
            "Ice": 60,
            "Lightning": 0,
            "Wind": 40,
            "Quantum": 0,
            "Imaginary": 20
          },
          "finalStats": {
            "ATKBaseFinal": 574.414,
            "ATKBonusPercent": 0,
            "ATKBonusFlat": 0,
            "ATKFinal": 574.414,
            "HPBaseFinal": 288445.893,
            "HPBonusPercent": 0,
            "HPBonusFlat": 0,
            "HPFinal": 288445.893,
            "DEFBaseFinal": 1020,
            "DEFBonusPercent": 0,
            "DEFBonusFlat": 0,
            "DEFFinal": 1020,
            "SPDBaseFinal": 144,
            "SPDBonusPercent": 0,
            "SPDBonusFlat": 0,
            "SPDFinal": 144,
            "SPDActionValue": 69.44444444444444,
            "CritRateFinal": 0,
            "CritDamageFinal": 0
          }
        }
      ]
    ]
}