const weaponSubstatList = {
    "": {
        "statName": "",
        "stats": {},
        "tags": [],
        "Sniper": [0,0],
        "Hand Cannon": [0,0],
        "Burst Rifle": [0,0],
        "Scout Rifle": [0,0],
        "Machine Gun": [0,0],
    },
    "Firearm ATK": {
        "statName": "FirearmATK%",
        "stats": {},
        "tags": ["FirearmATK%"],
        "Sniper": [0.10,0.122],
        "Hand Cannon": [0.10,0.122],
        "Burst Rifle": [0.10,0.122],
        "Scout Rifle": [0.10,0.122],
        "Machine Gun": [0.10,0.122],
    },
    "Fire ATK": {
        "statName": "FireATK",
        "stats": {},
        "tags": ["FireATK"],
        "Sniper": [8424,15196],
        "Hand Cannon": [3236,5838],
        "Burst Rifle": [960,1731],
        "Scout Rifle": [2631,4747],
        "Machine Gun": [944,1702],
    },
    "Chill ATK": {
        "statName": "ChillATK",
        "stats": {},
        "tags": ["ChillATK"],
        "Sniper": [8424,15196],
        "Hand Cannon": [3236,5838],
        "Burst Rifle": [960,1731],
        "Scout Rifle": [2631,4747],
        "Machine Gun": [944,1702],
    },
    "Electric ATK": {
        "statName": "ElectricATK",
        "stats": {},
        "tags": ["ElectricATK"],
        "Sniper": [8424,15196],
        "Hand Cannon": [3236,5838],
        "Burst Rifle": [960,1731],
        "Scout Rifle": [2631,4747],
        "Machine Gun": [944,1702],
    },
    "Toxic ATK": {
        "statName": "ToxicATK",
        "stats": {},
        "tags": ["ToxicATK"],
        "Sniper": [8424,15196],
        "Hand Cannon": [3236,5838],
        "Burst Rifle": [960,1731],
        "Scout Rifle": [2631,4747],
        "Machine Gun": [944,1702],
    },
    "Weak Point Damage": {
        "statName": "WeakPointDamage%",
        "stats": {},
        "tags": ["WeakPointDamage%"],
        "Sniper": [0.082,0.12],
        "Hand Cannon": [0.082,0.12],
        "Burst Rifle": [0.082,0.12],
        "Scout Rifle": [0.082,0.12],
        "Machine Gun": [0.082,0.12],
    },
    "Critical Hit Rate": {
        "statName": "FirearmCritRate",
        "stats": {},
        "tags": ["FirearmCritRate"],
        "Sniper": [0.093,0.108],
        "Hand Cannon": [0.099,0.114],
        "Burst Rifle": [0.108,0.122],
        "Scout Rifle": [0.119,0.133],
        "Machine Gun": [0.13,0.143],
    },
    "Critical Hit Damage": {
        "statName": "FirearmCritDamage",
        "stats": {},
        "tags": ["FirearmCritDamage"],
        "Sniper": [0.152,0.184],
        "Hand Cannon": [0.177,0.215],
        "Burst Rifle": [0.202,0.247],
        "Scout Rifle": [0.268,0.327],
        "Machine Gun": [0.338,0.411],
    },
    "Status Effect Rate": {
        "statName": "StatusTriggerRate",
        "stats": {},
        "tags": ["StatusTriggerRate"],
        "Sniper": [0.164,0.24],
        "Hand Cannon": [0.164,0.24],
        "Burst Rifle": [0.164,0.24],
        "Scout Rifle": [0.164,0.24],
        "Machine Gun": [0.164,0.24],
    },
    "Rounds per Magazine": {
        "statName": "MagazineSize",
        "stats": {},
        "tags": ["MagazineSize"],
        "Sniper": [0.082,0.12],
        "Hand Cannon": [0.082,0.12],
        "Burst Rifle": [0.082,0.12],
        "Scout Rifle": [0.082,0.12],
        "Machine Gun": [0.082,0.12],
    },
    "Bonus ATK (Colossus)": {
        "statName": "ColossusATK",
        "stats": {},
        "tags": ["ColossusATK"],
        "Sniper": [16848,30393],
        "Hand Cannon": [6472,11676],
        "Burst Rifle": [1919,3462],
        "Scout Rifle": [5263,9494],
        "Machine Gun": [1887,3404],
    },
    // "Recoil": {
    //     "statName": "Recoil",
    //     "Sniper": [-0.124,-0.102],
    //     "Hand Cannon": [-0.124,-0.102],
    // },
    // "Hip Fire Accuracy": {
    //     "statName": "FirearmATK",
    //     "Sniper": [0.102,0.124],
    //     "Hand Cannon": [0.102,0.124],
    // },
    // "Weapon Change Speed": {
    //     "statName": "",
    //     "Sniper": [0.114,0.165],
    //     "Hand Cannon": [0.114,0.165],
    // },
}

let weaponsInsertion = localCheck ? {} : weaponsLocal;
const sniperList = {
    "": {
        "name": "",
        "rarity": "Ultimate",
        "baseATK": 0,
        "baseCritRate": 0.00,
        "baseCritDamage": 1,
        "baseWeakPoint": 1,
        "physicalType": "Crush",
        "physicalTypeBonus": 0.10,
        "baseFireRate": 1,
        "baseReloadTime": 1,
        "magazine": 1,
        "ammoType": "HighPowered",
        "weaponType": "Sniper",
        "image": "/images/Remnant/clear.png",
        "customDPSBase": "",
        "customDPS": "",
        "desc": "",
        "stats": {},
        "tags": [],
        "weaponSettings": {},
        "displayStatsALT": {
            "BASIC": [],
        },
    },
    "Perforator": {
        "name": "Perforator",
        "rarity": "Ultimate",
        "baseATK": 67092,
        "baseCritRate": 0.20,
        "baseCritDamage": 2.0,
        "baseWeakPoint": 2.25,
        "physicalType": "Burst",
        "physicalTypeBonus": 0.10,

        "baseFireRate": 100,
        "baseReloadTime": 1.6,
        "magazine": 6,

        "ammoType": "Impact",
        "weaponType": "Hand Cannon",
        "image": "/TFD/TFDImages/Weapons/Icon_RW_HC_1008_A001.png",
        "customDPSBase": "",
        "customDPS": "",
        "desc": "",
        "stats": {},
        "tags": [],
        "weaponSettings": {},
        "displayStatsALT": {
            "BASIC": [],
        },
    },
    "Afterglow Sword": {
        "name": "Afterglow Sword",
        "rarity": "Ultimate",
        "baseATK": 114206,
        "baseCritRate": 0.50,
        "baseCritDamage": 2,
        "baseWeakPoint": 1.8,
        "physicalType": "Crush",
        "physicalTypeBonus": 0.10,

        "baseFireRate": 67,
        "baseReloadTime": 2.5,
        "magazine": 12,

        "ammoType": "HighPowered",
        "weaponType": "Sniper",
        "image": "/TFD/TFDImages/Weapons/Icon_RW_SR_1005_A001.png",
        "customDPSBase": "",
        "customDPS": "",
        "desc": "",
        "stats": {},
        "tags": [],
        "weaponSettings": {},
        "displayStatsALT": {
            "BASIC": [],
        },
    },
    "Piercing Light": {
        "name": "Piercing Light",
        "rarity": "Ultimate",
        "baseATK": 193437,
        "baseCritRate": 0.40,
        "baseCritDamage": 1.2,
        "baseWeakPoint": 2,
        "physicalType": "Crush",
        "physicalTypeBonus": 0.10,

        "baseFireRate": 48,
        "baseReloadTime": 2.6,
        "magazine": 11,

        "ammoType": "HighPowered",
        "weaponType": "Sniper",
        "image": "/TFD/TFDImages/Weapons/Icon_RW_SR_1006_A001.png",
        "customDPSBase": "",
        "customDPS": "",
        "desc": "",
        "stats": {},
        "tags": [],
        "weaponSettings": {},
        "displayStatsALT": {
            "BASIC": [],
        },
    },
    "Secret Garden": {
        "name": "Secret Garden",
        "rarity": "Ultimate",
        "baseATK": 10534,
        "baseCritRate": 0.50,
        "baseCritDamage": 2.25,
        "baseWeakPoint": 1.5,
        "physicalType": "Burst",
        "physicalTypeBonus": 0.10,

        "baseFireRate": 120,
        "baseReloadTime": 1.6,
        "magazine": 48,

        "ammoType": "Special",
        "weaponType": "Burst Rifle",
        "image": "/TFD/TFDImages/Weapons/Icon_RW_TR_1005_A001.png",
        "weaponSettings": {
            "gardenStackCount": 3,
        },
        "customDPSBase": "secretGardenCalcsTier0",
        "customDPS": "skipThisWeaponCalcs",
        "desc": "When using a Dimension skill, recovers Custom Resource with a set chance. When using a Tech Skill, grants the unique ability Pest Control with a set chance.",
        "displayStatsALT": {
            "BASIC": [
                {"statType": "","statName": "Skill Cost","value": 0,"limit": null,"isModified": false},
            ],
            "DIMENSION SKILL": [
                {"statType": "","statName": "Trigger Rate","value": 0.39,"limit": null,"isModified": false,"isUnlabeledPercent": true},
                {"statType": "","statName": "Resource Recovery","value": 0.10,"limit": null,"isModified": false,"isUnlabeledPercent": true},
            ],
            "PEST CONTROL": [
                {"statType": "","statName": "Trigger Rate","value": 0.50,"limit": null,"isModified": false,"isUnlabeledPercent": true},
                {"statType": "duration","statName": "Duration","value": 10,"limit": null,"isModified": false},
                {"statType": "","statName": "Max Stacks","value": 3,"limit": null,"isModified": false},
                {"statType": "","statName": "+Firearm ATK%","value": 0.05,"limit": null,"isModified": false,"isUnlabeledPercent": true},
                {"statType": "","statName": "+Skill Power (Opt.)","value": 0.05,"limit": null,"isModified": false,"isUnlabeledPercent": true},
                {"statType": "","statName": "+Firearm ATK%/Stack","value": 0.16,"limit": null,"isModified": false,"isUnlabeledPercent": true},
                {"statType": "","statName": "+Skill Power (Opt.)/Stack","value": 0.16,"limit": null,"isModified": false,"isUnlabeledPercent": true},
            ],
        },
        "stats": {},
        "tags": ["FirearmATK%","PowerOptimization"],
    },
    "Blue Beetle": {
        "name": "Blue Beetle",
        "rarity": "Ultimate",
        "baseATK": 29468,
        "baseCritRate": 0.25,
        "baseCritDamage": 1.80,
        "baseWeakPoint": 1.5,
        "physicalType": "Crush",
        "physicalTypeBonus": 0.10,

        "baseFireRate": 200,
        "baseReloadTime": 2,
        "magazine": 16,

        "ammoType": "Impact",
        "weaponType": "Scout Rifle",
        "image": "/TFD/TFDImages/Weapons/Icon_RW_SCR_1006_A001.png",
        "weaponSettings": {
            "arcaneWaveActive": true,
        },
        "customDPSBase": "blueBeetleCalcsTier0",
        "customDPS": "",
        "desc": "When using a Fusion skill, grants self the unique ability Arcane Energy with a set chance. When using a Singular skill, grants self the unique Ability Purification with a set chance.",
        "displayStatsALT": {
            "BASIC": [
                {"statType": "","statName": "Skill Cost","value": 0,"limit": null,"isModified": false},
            ],
            "ARCANE ENERGY": [
                {"statType": "","statName": "Trigger Rate","value": 1,"limit": null,"isModified": false,"isUnlabeledPercent": true},
                {"statType": "duration","statName": "Duration","value": 10,"limit": null,"isModified": false},
                {"statType": "","statName": "+Skill Crit Rate%","value": 0.30,"limit": null,"isModified": false,"isUnlabeledPercent": true},
            ],
            "PURIFICATION": [
                {"statType": "","statName": "Trigger Rate","value": 1,"limit": null,"isModified": false,"isUnlabeledPercent": true},
                {"statType": "duration","statName": "Duration","value": 1,"limit": null,"isModified": false},
                {"statType": "","statName": "Debuff Removal Chance","value": 1,"limit": null,"isModified": false,"isUnlabeledPercent": true},
            ],
        },
        "stats": {},
        "tags": ["SkillCritRate"],
    },
    "Peace Maker": {
        "name": "Peace Maker",
        "rarity": "Ultimate",
        "baseATK": 32471,
        "baseCritRate": 0.50,
        "baseCritDamage": 2.5,
        "baseWeakPoint": 1.20,
        "physicalType": "Burst",
        "physicalTypeBonus": 0.10,

        "baseFireRate": 133,
        "baseReloadTime": 1.35,
        "magazine": 8,

        "ammoType": "Impact",
        "weaponType": "Hand Cannon",
        "image": "/TFD/TFDImages/Weapons/Icon_RW_HC_1010_A001.png",
        "customDPSBase": "peacemakerCalcsTier0",
        "customDPS": "",
        "desc": "When using a Dimension or Fusion skill, grants the unique ability Single Reload for Peace. When Single Reload for Peace is at Max Stacks, shooting while aiming rapidly fires all loaded rounds.",
        "stats": {},
        "tags": ["PowerRatioNonAttribute"],
        "weaponSettings": {
            "peacemakerStackCount": 5,
        },
        "displayStatsALT": {
            "BASIC": [
                {"statType": "","statName": "Reload Time Modifier","value": 0,"limit": null,"isModified": false,"isUnlabeledPercent": true},
                {"statType": "","statName": "Recoil","value": 0,"limit": null,"isModified": false,"isUnlabeledPercent": true},
            ],
            "SINGLE RELOAD FOR PEACE": [
                {"statType": "","statName": "Trigger Rate","value": 1.00,"limit": null,"isModified": false,"isUnlabeledPercent": true},
                {"statType": "duration","statName": "Duration","value": 15,"limit": null,"isModified": false},
                {"statType": "","statName": "Max Stacks","value": 5,"limit": null,"isModified": false},
                {"statType": "","statName": "Skill Cost","value": 0.00,"limit": null,"isModified": false,"isUnlabeledPercent": true},
                {"statType": "","statName": "+Non-Attribute Power Ratio","value": 0.05,"limit": null,"isModified": false,"isUnlabeledPercent": true},
                {"statType": "","statName": "+Non-Attribute Power/Stack","value": 0.095,"limit": null,"isModified": false,"isUnlabeledPercent": true},
            ],
            "AIMING AT MAX STACKS": [
                {"statType": "","statName": "Fire Rate","value": 545,"limit": null,"isModified": false},
            ],
        },
    },
    "Nazeistra's Devotion": {
        "name": "Nazeistra's Devotion",
        "rarity": "Ultimate",
        "baseATK": 38461,
        "baseCritRate": 0.45,
        "baseCritDamage": 2.25,
        "baseWeakPoint": 1.7,
        "physicalType": "Burst",
        "physicalTypeBonus": 0.10,

        "baseFireRate": 150,
        "baseReloadTime": 1.5,
        "magazine": 8,

        "ammoType": "Impact",
        "weaponType": "Hand Cannon",
        "image": "/TFD/TFDImages/Weapons/Icon_RW_HC_1007_A001.png",
        "weaponSettings": {
            "defDebuffActive": false,//default to off, we don't want it skewing stuff like zenith math unless the user is content screwing themselves by enabling it
        },
        "customDPSBase": "nazDevotionCalcsTier0",
        "customDPS": "",
        "desc": "On hitting an enemy's Weak Point, inflicts the unique ability Devotion Mark on the target. On hitting an ally, that ally's shield is restored at the cost of your MP. If your current MP is less than the MP cost, this effect is not triggered.",
        "displayStatsALT": {
            "BASIC": [
                {"statType": "","statName": "Aim Recovery Speed","value": 0,"limit": null,"isModified": false,"isUnlabeledPercent": true},
            ],
            "DEVOTION MARK": [
                {"statType": "duration","statName": "Duration","value": 3,"limit": null,"isModified": false},
                {"statType": "","statName": "-DEF%","value": 0.30,"limit": null,"isModified": false,"isUnlabeledPercent": true},
            ],
            "ON ALLIED HIT": [
                {"statType": "","statName": "MP Cost","value": -65,"limit": null,"isModified": false},
                {"statType": "","statName": "Shield Recovery","value": 0.30,"limit": null,"isModified": false,"isUnlabeledPercent": true},
            ],
        },
        "stats": {},
        "tags": ["enemyDEFResistanceReduction"],
    },

    "Assassin's Edge": {
        "name": "Assassin's Edge",
        "rarity": "Rare",
        "baseATK": 40788,
        "baseCritRate": 0.40,
        "baseCritDamage": 2.0,
        "baseWeakPoint": 2.0,
        "physicalType": "Burst",
        "physicalTypeBonus": 0.10,

        "baseFireRate": 120,
        "baseReloadTime": 1.4,
        "magazine": 9,

        "ammoType": "Impact",
        "weaponType": "Hand Cannon",
        "image": "/TFD/TFDImages/Weapons/Icon_RW_HC_1001_A001.png",
        "customDPSBase": "",
        "customDPS": "",
        "desc": "",
        "stats": {},
        "tags": [],
        "weaponSettings": {},
        "displayStatsALT": {
            "BASIC": [],
        },
    },
    ...weaponsInsertion
}