let sniperData = {
  "Perforator": {
    "name": "Perforator",
    "ID": "211023002",
    "rarity": "Ultimate",
    "baseATK": 67092,
    "baseCritRate": 0.2,
    "baseCritDamage": 2,
    "baseWeakPoint": 2.25,
    "physicalType": "Burst",
    "physicalTypeBonus": 0.1,
    "baseFireRate": 100,
    "baseReloadTime": 1.6,
    "magazine": 6,
    "shellCount": 1,
    "coreArray": [
      "Rainbow",
      "Red",
      "Green",
      "Green",
      "Purple"
    ],
    "RangedInTime": 0.2,
    "ZoomInHoldDelayTime": 0.4,
    "ReloadType": "Magazine",
    "ammoType": "Impact",
    "weaponType": "Hand Cannon",
    "image": "/TFD/TFDImages/Weapons/Icon_RW_HC_1008_A001.png",
    "desc": "Critical Hits or hits on a Weak Point spawn Explosive Scanners.\nExplosive Scanners explode on contact with the terrain or enemies and inflict Detect on enemies within the explosion range.",
    "stats": {},
    "ChargeLevelData": []
  },
  "Afterglow Sword": {
    "name": "Afterglow Sword",
    "ID": "211093001",
    "rarity": "Ultimate",
    "baseATK": 114206,
    "baseCritRate": 0.5,
    "baseCritDamage": 2,
    "baseWeakPoint": 1.8,
    "physicalType": "Crush",
    "physicalTypeBonus": 0.1,
    "baseFireRate": 66.66666666666667,
    "baseReloadTime": 2.5,
    "magazine": 12,
    "shellCount": 1,
    "coreArray": [
      "Rainbow",
      "Red",
      "Yellow",
      "Yellow",
      "Purple"
    ],
    "RangedInTime": 0.3,
    "ZoomInHoldDelayTime": 0.3,
    "ReloadType": "Magazine",
    "ammoType": "HighPowered",
    "weaponType": "Sniper Rifle",
    "image": "/TFD/TFDImages/Weapons/Icon_RW_SR_1005_A001.png",
    "desc": "On hitting a Weak Point, inflicts the unique effect, Death Propagation. \nOn hitting an enemy Commander or Colossus, increases Firearm Critical Hit Rate and applies the effect to the attack.",
    "stats": {},
    "ChargeLevelData": []
  },
  "Piercing Light": {
    "name": "Piercing Light",
    "ID": "211093002",
    "rarity": "Ultimate",
    "baseATK": 193437,
    "baseCritRate": 0.4,
    "baseCritDamage": 1.2,
    "baseWeakPoint": 2,
    "physicalType": "Crush",
    "physicalTypeBonus": 0.1,
    "baseFireRate": 48,
    "baseReloadTime": 2.6,
    "magazine": 11,
    "shellCount": 1,
    "coreArray": [
      "Rainbow",
      "Blue",
      "Green",
      "Yellow",
      "Yellow"
    ],
    "RangedInTime": 0.3,
    "ZoomInHoldDelayTime": 0.45,
    "ReloadType": "Magazine",
    "ammoType": "HighPowered",
    "weaponType": "Sniper Rifle",
    "image": "/TFD/TFDImages/Weapons/Icon_RW_SR_1006_A001.png",
    "desc": "On hitting a Weak Point, inflicts Dispel on the enemy with a set chance.\nWhen two or more enemies are hit by a single shot, there is a high chance to land a Critical Hit on the enemies while also increasing Critical Hit Damage and applying this buff to the attack.",
    "stats": {
      "ChillATK": 81244
    },
    "ChargeLevelData": []
  },
  "Secret Garden": {
    "name": "Secret Garden",
    "ID": "211073001",
    "rarity": "Ultimate",
    "baseATK": 10534,
    "baseCritRate": 0.5,
    "baseCritDamage": 2.25,
    "baseWeakPoint": 1.5,
    "physicalType": "Burst",
    "physicalTypeBonus": 0.1,
    "baseFireRate": 120,
    "baseReloadTime": 1.6,
    "magazine": 48,
    "shellCount": 1,
    "coreArray": [
      "Rainbow",
      "Red",
      "Yellow",
      "Yellow",
      "Purple"
    ],
    "RangedInTime": 0.185,
    "ZoomInHoldDelayTime": 0.385,
    "ReloadType": "Magazine",
    "ammoType": "Special",
    "weaponType": "Tactical Rifle",
    "image": "/TFD/TFDImages/Weapons/Icon_RW_TR_1005_A001.png",
    "desc": "When using a Dimension skill, recovers Custom Resource with a set chance.\nWhen using a Tech skill, grants the unique ability Pest Control with a set chance.",
    "stats": {},
    "ChargeLevelData": []
  },
  "Blue Beetle": {
    "name": "Blue Beetle",
    "ID": "211083002",
    "rarity": "Ultimate",
    "baseATK": 29468,
    "baseCritRate": 0.25,
    "baseCritDamage": 1.8,
    "baseWeakPoint": 1.5,
    "physicalType": "Crush",
    "physicalTypeBonus": 0.1,
    "baseFireRate": 200,
    "baseReloadTime": 2,
    "magazine": 16,
    "shellCount": 1,
    "coreArray": [
      "Rainbow",
      "Orange",
      "Blue",
      "Green",
      "Yellow"
    ],
    "RangedInTime": 0.28,
    "ZoomInHoldDelayTime": 0.3,
    "ReloadType": "Magazine",
    "ammoType": "Impact",
    "weaponType": "Scout Rifle",
    "image": "/TFD/TFDImages/Weapons/Icon_RW_SCR_1006_A001.png",
    "desc": "When using a Fusion skill, grants self the unique ability Arcane Energy with a set chance.\nWhen using a Singular skill, grants self the unique ability Purification with a set chance.",
    "stats": {
      "ElectricATK": 15029
    },
    "ChargeLevelData": []
  },
  "Peace Maker": {
    "name": "Peace Maker",
    "ID": "211023003",
    "rarity": "Ultimate",
    "baseATK": 32471,
    "baseCritRate": 0.5,
    "baseCritDamage": 2.5,
    "baseWeakPoint": 1.2,
    "physicalType": "Burst",
    "physicalTypeBonus": 0.1,
    "baseFireRate": 133.33333333333334,
    "baseReloadTime": 1.35,
    "magazine": 8,
    "shellCount": 1,
    "coreArray": [
      "Rainbow",
      "Red",
      "Green",
      "Yellow",
      "Yellow"
    ],
    "RangedInTime": 0.23,
    "ZoomInHoldDelayTime": 0.4,
    "ReloadType": "Magazine",
    "ammoType": "Impact",
    "weaponType": "Hand Cannon",
    "image": "/TFD/TFDImages/Weapons/Icon_RW_HC_1010_A001.png",
    "desc": "When using a Dimension or Fusion skill, grants the unique ability Single Reload for Peace.\nWhen Single Reload for Peace is at Max Stacks, shooting while aiming rapidly fires all loaded rounds.",
    "stats": {},
    "ChargeLevelData": []
  },
  "Nazeistra's Devotion": {
    "name": "Nazeistra's Devotion",
    "ID": "211023001",
    "rarity": "Ultimate",
    "baseATK": 38461,
    "baseCritRate": 0.45,
    "baseCritDamage": 2.25,
    "baseWeakPoint": 1.7,
    "physicalType": "Burst",
    "physicalTypeBonus": 0.1,
    "baseFireRate": 150,
    "baseReloadTime": 1.5,
    "magazine": 8,
    "shellCount": 1,
    "coreArray": [
      "Rainbow",
      "Green",
      "Yellow",
      "Yellow",
      "Purple"
    ],
    "RangedInTime": 0.22,
    "ZoomInHoldDelayTime": 0.4,
    "ReloadType": "Magazine",
    "ammoType": "Impact",
    "weaponType": "Hand Cannon",
    "image": "/TFD/TFDImages/Weapons/Icon_RW_HC_1007_A001.png",
    "desc": "On hitting an enemy's Weak Point, inflicts the unique ability Devotion Mark on the target enemy.\nOn hitting an ally, that ally's shield is restored at the cost of your MP. If your current MP is less than the MP cost, this effect is not triggered.",
    "stats": {},
    "ChargeLevelData": []
  },
  "Assassin's Edge": {
    "name": "Assassin's Edge",
    "ID": "211022001",
    "rarity": "Rare",
    "baseATK": 44604,
    "baseCritRate": 0.4,
    "baseCritDamage": 2,
    "baseWeakPoint": 2,
    "physicalType": "Burst",
    "physicalTypeBonus": 0.1,
    "baseFireRate": 120,
    "baseReloadTime": 1.4,
    "magazine": 9,
    "shellCount": 1,
    "coreArray": null,
    "RangedInTime": 0.2,
    "ZoomInHoldDelayTime": 0.4,
    "ReloadType": "Magazine",
    "ammoType": "Impact",
    "weaponType": "Hand Cannon",
    "image": "/TFD/TFDImages/Weapons/Icon_RW_HC_1001_A001.png",
    "desc": "",
    "stats": {},
    "ChargeLevelData": []
  },
  "Smithereens": {
    "name": "Smithereens",
    "ID": "211033001",
    "rarity": "Ultimate",
    "baseATK": 14562,
    "baseCritRate": 0.01,
    "baseCritDamage": 1.1,
    "baseWeakPoint": 1,
    "physicalType": "Burst",
    "physicalTypeBonus": 0.1,
    "baseFireRate": 150,
    "baseReloadTime": 1.6,
    "magazine": 15,
    "shellCount": 10,
    "coreArray": [
      "Rainbow",
      "Orange",
      "Yellow",
      "Yellow",
      "Purple"
    ],
    "RangedInTime": 0.16,
    "ZoomInHoldDelayTime": 0.368,
    "ReloadType": "Magazine",
    "ammoType": "HighPowered",
    "weaponType": "Shotgun",
    "image": "/TFD/TFDImages/Weapons/Icon_RW_SG_1005_A001.png",
    "desc": "On hitting the enemy with all fired bullets, increases the Firearm Critical Hit Rate and Firearm Critical Hit Damage of the attack.\nUpon landing a Critical Hit on an enemy, grants the Firearm's unique ability Amplification.",
    "stats": {},
    "ChargeLevelData": []
  },
  "Hero's Scar": {
    "name": "Hero's Scar",
    "ID": "211082001",
    "rarity": "Rare",
    "baseATK": 33071,
    "baseCritRate": 0.1,
    "baseCritDamage": 1.5,
    "baseWeakPoint": 1.5,
    "physicalType": "Crush",
    "physicalTypeBonus": 0.1,
    "baseFireRate": 240,
    "baseReloadTime": 2.0999999999999996,
    "magazine": 20,
    "shellCount": 1,
    "coreArray": null,
    "RangedInTime": 0.17,
    "ZoomInHoldDelayTime": 0.3,
    "ReloadType": "Magazine",
    "ammoType": "Impact",
    "weaponType": "Scout Rifle",
    "image": "/TFD/TFDImages/Weapons/Icon_RW_SCR_1001_A001.png",
    "desc": "",
    "stats": {},
    "ChargeLevelData": []
  },
  "Silly Weeper": {
    "name": "Silly Weeper",
    "ID": "211082002",
    "rarity": "Rare",
    "baseATK": 97131,
    "baseCritRate": 0.2,
    "baseCritDamage": 1.5,
    "baseWeakPoint": 1.5,
    "physicalType": "Crush",
    "physicalTypeBonus": 0.1,
    "baseFireRate": 78.02340702210662,
    "baseReloadTime": 2.0999999999999996,
    "magazine": 8,
    "shellCount": 1,
    "coreArray": null,
    "RangedInTime": 0.17,
    "ZoomInHoldDelayTime": 0.3,
    "ReloadType": "Magazine",
    "ammoType": "Impact",
    "weaponType": "Scout Rifle",
    "image": "/TFD/TFDImages/Weapons/Icon_RW_SCR_1002_A001.png",
    "desc": "",
    "stats": {},
    "ChargeLevelData": []
  },
  "Nightmare Hound": {
    "name": "Nightmare Hound",
    "ID": "211081001",
    "rarity": "Common",
    "baseATK": 39963,
    "baseCritRate": 0.05,
    "baseCritDamage": 1.2,
    "baseWeakPoint": 1.5,
    "physicalType": "Crush",
    "physicalTypeBonus": 0.1,
    "baseFireRate": 180.18018018018017,
    "baseReloadTime": 2.2399999999999998,
    "magazine": 18,
    "shellCount": 1,
    "coreArray": null,
    "RangedInTime": 0.17,
    "ZoomInHoldDelayTime": 0.3,
    "ReloadType": "Magazine",
    "ammoType": "Impact",
    "weaponType": "Scout Rifle",
    "image": "/TFD/TFDImages/Weapons/Icon_RW_SCR_1003_A001.png",
    "desc": "",
    "stats": {},
    "ChargeLevelData": []
  },
  "The Age Of Innovation": {
    "name": "The Age Of Innovation",
    "ID": "211082003",
    "rarity": "Rare",
    "baseATK": 33103,
    "baseCritRate": 0.07,
    "baseCritDamage": 1.5,
    "baseWeakPoint": 1.5,
    "physicalType": "Crush",
    "physicalTypeBonus": 0.1,
    "baseFireRate": 250,
    "baseReloadTime": 2.0999999999999996,
    "magazine": 15,
    "shellCount": 1,
    "coreArray": null,
    "RangedInTime": 0.17,
    "ZoomInHoldDelayTime": 0.3,
    "ReloadType": "Magazine",
    "ammoType": "Impact",
    "weaponType": "Scout Rifle",
    "image": "/TFD/TFDImages/Weapons/Icon_RW_SCR_1004_A001.png",
    "desc": "",
    "stats": {},
    "ChargeLevelData": []
  },
  "Sonic Co-op": {
    "name": "Sonic Co-op",
    "ID": "211082004",
    "rarity": "Rare",
    "baseATK": 24917,
    "baseCritRate": 0.2,
    "baseCritDamage": 1.5,
    "baseWeakPoint": 1.5,
    "physicalType": "Crush",
    "physicalTypeBonus": 0.1,
    "baseFireRate": 300,
    "baseReloadTime": 2,
    "magazine": 25,
    "shellCount": 1,
    "coreArray": null,
    "RangedInTime": 0.28,
    "ZoomInHoldDelayTime": 0.3,
    "ReloadType": "Magazine",
    "ammoType": "Impact",
    "weaponType": "Scout Rifle",
    "image": "/TFD/TFDImages/Weapons/Icon_RW_SCR_1008_A001.png",
    "desc": "",
    "stats": {},
    "ChargeLevelData": []
  },
  "Explorer's Path": {
    "name": "Explorer's Path",
    "ID": "211022002",
    "rarity": "Rare",
    "baseATK": 63596,
    "baseCritRate": 0.27,
    "baseCritDamage": 1.3,
    "baseWeakPoint": 2,
    "physicalType": "Burst",
    "physicalTypeBonus": 0.1,
    "baseFireRate": 109.09090909090908,
    "baseReloadTime": 1.4,
    "magazine": 9,
    "shellCount": 1,
    "coreArray": null,
    "RangedInTime": 0.23,
    "ZoomInHoldDelayTime": 0.43,
    "ReloadType": "Magazine",
    "ammoType": "Impact",
    "weaponType": "Hand Cannon",
    "image": "/TFD/TFDImages/Weapons/Icon_RW_HC_1002_A001.png",
    "desc": "",
    "stats": {},
    "ChargeLevelData": []
  },
  "Burning Hound": {
    "name": "Burning Hound",
    "ID": "211021001",
    "rarity": "Common",
    "baseATK": 41726,
    "baseCritRate": 0.32,
    "baseCritDamage": 1.5,
    "baseWeakPoint": 1.7,
    "physicalType": "Burst",
    "physicalTypeBonus": 0.1,
    "baseFireRate": 139.86013986013987,
    "baseReloadTime": 1.75,
    "magazine": 12,
    "shellCount": 1,
    "coreArray": null,
    "RangedInTime": 0.2,
    "ZoomInHoldDelayTime": 0.4,
    "ReloadType": "Magazine",
    "ammoType": "Impact",
    "weaponType": "Hand Cannon",
    "image": "/TFD/TFDImages/Weapons/Icon_RW_HC_1006_A001.png",
    "desc": "",
    "stats": {},
    "ChargeLevelData": []
  },
  "Immediate Execution": {
    "name": "Immediate Execution",
    "ID": "211022006",
    "rarity": "Rare",
    "baseATK": 39206,
    "baseCritRate": 0.32,
    "baseCritDamage": 1.5,
    "baseWeakPoint": 2,
    "physicalType": "Burst",
    "physicalTypeBonus": 0.1,
    "baseFireRate": 171.42857142857144,
    "baseReloadTime": 1.7,
    "magazine": 12,
    "shellCount": 1,
    "coreArray": null,
    "RangedInTime": 0.2,
    "ZoomInHoldDelayTime": 0.4,
    "ReloadType": "Magazine",
    "ammoType": "Impact",
    "weaponType": "Hand Cannon",
    "image": "/TFD/TFDImages/Weapons/Icon_RW_HC_1009_A001.png",
    "desc": "",
    "stats": {},
    "ChargeLevelData": []
  },
  "Different Dream": {
    "name": "Different Dream",
    "ID": "211092004",
    "rarity": "Rare",
    "baseATK": 110259,
    "baseCritRate": 0.55,
    "baseCritDamage": 1.8,
    "baseWeakPoint": 1.5,
    "physicalType": "Crush",
    "physicalTypeBonus": 0.1,
    "baseFireRate": 63.15789473684211,
    "baseReloadTime": 2.15,
    "magazine": 12,
    "shellCount": 1,
    "coreArray": null,
    "RangedInTime": 0.35,
    "ZoomInHoldDelayTime": 0.48,
    "ReloadType": "Magazine",
    "ammoType": "HighPowered",
    "weaponType": "Sniper Rifle",
    "image": "/TFD/TFDImages/Weapons/Icon_RW_SR_1007_A001.png",
    "desc": "",
    "stats": {},
    "ChargeLevelData": []
  },
  "Forest Gaze": {
    "name": "Forest Gaze",
    "ID": "211092001",
    "rarity": "Rare",
    "baseATK": 133703,
    "baseCritRate": 0.5,
    "baseCritDamage": 2,
    "baseWeakPoint": 1.5,
    "physicalType": "Crush",
    "physicalTypeBonus": 0.1,
    "baseFireRate": 50,
    "baseReloadTime": 2.52,
    "magazine": 7,
    "shellCount": 1,
    "coreArray": null,
    "RangedInTime": 0.3,
    "ZoomInHoldDelayTime": 0.35,
    "ReloadType": "Magazine",
    "ammoType": "HighPowered",
    "weaponType": "Sniper Rifle",
    "image": "/TFD/TFDImages/Weapons/Icon_RW_SR_1001_A001.png",
    "desc": "",
    "stats": {},
    "ChargeLevelData": []
  },
  "Supermoon Z-15": {
    "name": "Supermoon Z-15",
    "ID": "211092002",
    "rarity": "Rare",
    "baseATK": 101392,
    "baseCritRate": 0.5,
    "baseCritDamage": 2,
    "baseWeakPoint": 1.5,
    "physicalType": "Crush",
    "physicalTypeBonus": 0.1,
    "baseFireRate": 65.93406593406593,
    "baseReloadTime": 2.2399999999999998,
    "magazine": 9,
    "shellCount": 1,
    "coreArray": null,
    "RangedInTime": 0.25,
    "ZoomInHoldDelayTime": 0.34,
    "ReloadType": "Magazine",
    "ammoType": "HighPowered",
    "weaponType": "Sniper Rifle",
    "image": "/TFD/TFDImages/Weapons/Icon_RW_SR_1002_A001.png",
    "desc": "",
    "stats": {},
    "ChargeLevelData": []
  },
  "Recipient Unknown": {
    "name": "Recipient Unknown",
    "ID": "211091001",
    "rarity": "Common",
    "baseATK": 132590,
    "baseCritRate": 0.45,
    "baseCritDamage": 1.8,
    "baseWeakPoint": 1.5,
    "physicalType": "Crush",
    "physicalTypeBonus": 0.1,
    "baseFireRate": 72.02881152460985,
    "baseReloadTime": 2.0999999999999996,
    "magazine": 6,
    "shellCount": 1,
    "coreArray": null,
    "RangedInTime": 0.25,
    "ZoomInHoldDelayTime": 0.33,
    "ReloadType": "Magazine",
    "ammoType": "HighPowered",
    "weaponType": "Sniper Rifle",
    "image": "/TFD/TFDImages/Weapons/Icon_RW_SR_1003_A001.png",
    "desc": "",
    "stats": {},
    "ChargeLevelData": []
  },
  "Belief": {
    "name": "Belief",
    "ID": "211092003",
    "rarity": "Rare",
    "baseATK": 92167,
    "baseCritRate": 0.45,
    "baseCritDamage": 1.8,
    "baseWeakPoint": 1.7,
    "physicalType": "Crush",
    "physicalTypeBonus": 0.1,
    "baseFireRate": 80,
    "baseReloadTime": 2.3099999999999996,
    "magazine": 9,
    "shellCount": 1,
    "coreArray": null,
    "RangedInTime": 0.2,
    "ZoomInHoldDelayTime": 0.3,
    "ReloadType": "Magazine",
    "ammoType": "HighPowered",
    "weaponType": "Sniper Rifle",
    "image": "/TFD/TFDImages/Weapons/Icon_RW_SR_1004_A001.png",
    "desc": "",
    "stats": {},
    "ChargeLevelData": []
  },
  "Blue Blood Bloomer": {
    "name": "Blue Blood Bloomer",
    "ID": "211042002",
    "rarity": "Rare",
    "baseATK": 11408,
    "baseCritRate": 0.12,
    "baseCritDamage": 1.5,
    "baseWeakPoint": 1,
    "physicalType": "Burst",
    "physicalTypeBonus": 0.1,
    "baseFireRate": 1000,
    "baseReloadTime": 1.32,
    "magazine": 27,
    "shellCount": 1,
    "coreArray": null,
    "RangedInTime": 0.148,
    "ZoomInHoldDelayTime": 0.348,
    "ReloadType": "Magazine",
    "ammoType": "General",
    "weaponType": "Submachine Gun",
    "image": "/TFD/TFDImages/Weapons/Icon_RW_SMG_1002_A001.png",
    "desc": "",
    "stats": {},
    "ChargeLevelData": []
  },
  "Python": {
    "name": "Python",
    "ID": "211043002",
    "rarity": "Ultimate",
    "baseATK": 11908,
    "baseCritRate": 0.05,
    "baseCritDamage": 1.3,
    "baseWeakPoint": 2,
    "physicalType": "Burst",
    "physicalTypeBonus": 0.1,
    "baseFireRate": 923.0769230769231,
    "baseReloadTime": 1.5,
    "magazine": 30,
    "shellCount": 1,
    "coreArray": [
      "Rainbow",
      "Orange",
      "Green",
      "Yellow",
      "Yellow"
    ],
    "RangedInTime": 0.148,
    "ZoomInHoldDelayTime": 0.348,
    "ReloadType": "Magazine",
    "ammoType": "General",
    "weaponType": "Submachine Gun",
    "image": "/TFD/TFDImages/Weapons/Icon_RW_SMG_1006_A001.png",
    "desc": "On hitting a Weak Point, inflicts the unique ability Prey on the target enemy.",
    "stats": {
      "ToxicATK": 6669
    },
    "ChargeLevelData": []
  },
  "Firefly": {
    "name": "Firefly",
    "ID": "211042004",
    "rarity": "Rare",
    "baseATK": 10879,
    "baseCritRate": 0.2,
    "baseCritDamage": 1.2,
    "baseWeakPoint": 1,
    "physicalType": "Burst",
    "physicalTypeBonus": 0.1,
    "baseFireRate": 857.1428571428571,
    "baseReloadTime": 1.35,
    "magazine": 35,
    "shellCount": 1,
    "coreArray": null,
    "RangedInTime": 0.148,
    "ZoomInHoldDelayTime": 0.348,
    "ReloadType": "Magazine",
    "ammoType": "General",
    "weaponType": "Submachine Gun",
    "image": "/TFD/TFDImages/Weapons/Icon_RW_SMG_1007_A001.png",
    "desc": "",
    "stats": {},
    "ChargeLevelData": []
  },
  "The Last Dagger": {
    "name": "The Last Dagger",
    "ID": "211013001",
    "rarity": "Ultimate",
    "baseATK": 14095,
    "baseCritRate": 0.12,
    "baseCritDamage": 2,
    "baseWeakPoint": 1.6,
    "physicalType": "Pierce",
    "physicalTypeBonus": 0.1,
    "baseFireRate": 600,
    "baseReloadTime": 1.2,
    "magazine": 12,
    "shellCount": 1,
    "coreArray": [
      "Rainbow",
      "Orange",
      "Orange",
      "Green",
      "Green"
    ],
    "RangedInTime": 0.25,
    "ZoomInHoldDelayTime": 0.45,
    "ReloadType": "Magazine",
    "ammoType": "General",
    "weaponType": "Handgun",
    "image": "/TFD/TFDImages/Weapons/Icon_RW_HG_1005_A001.png",
    "desc": "When hitting an enemy, grants the Unique Abilities Patience and Lethal Dagger.\nPatience is reset on reload at max stacks, and grants Strike.\nStrike consumes all rounds, and fires Enhanced Rounds.\nWhen Strike is removed, grants Steps.",
    "stats": {},
    "ChargeLevelData": []
  },
  "Clairvoyance": {
    "name": "Clairvoyance",
    "ID": "211123002",
    "rarity": "Ultimate",
    "baseATK": 13362,
    "baseCritRate": 0.2,
    "baseCritDamage": 2,
    "baseWeakPoint": 1,
    "physicalType": "Pierce",
    "physicalTypeBonus": 0.1,
    "baseFireRate": 400,
    "baseReloadTime": 2.2,
    "magazine": 40,
    "shellCount": 1,
    "coreArray": [
      "Rainbow",
      "Blue",
      "Green",
      "Yellow",
      "Yellow"
    ],
    "RangedInTime": 0.25,
    "ZoomInHoldDelayTime": 0.45,
    "ReloadType": "Magazine",
    "ammoType": "Special",
    "weaponType": "Beam Rifle",
    "image": "/TFD/TFDImages/Weapons/Icon_RW_BR_1006_A001.png",
    "desc": "Hitting an enemy with a Stage 2 Beam inflicts Void Gaze on the target.\nHitting an enemy with a Stage 3 Beam inflicts Appalled Calling on the target. This effect is considered to be the same effect as Frostbite in some modes.",
    "stats": {
      "ChillATK": 2539
    },
    "ChargeLevelData": [
      {
        "ChargeAmount": 0,
        "ChargeRate": 0,
        "DischargeRate": 0,
        "SteadyDuration": 0,
        "DamageMultiplier": 0
      },
      {
        "ChargeAmount": 1.5,
        "ChargeRate": 1,
        "DischargeRate": 0.7,
        "SteadyDuration": 0,
        "DamageMultiplier": 1
      },
      {
        "ChargeAmount": 1.5,
        "ChargeRate": 1,
        "DischargeRate": 0.9,
        "SteadyDuration": 0,
        "DamageMultiplier": 1.15
      },
      {
        "ChargeAmount": 0,
        "ChargeRate": 0,
        "DischargeRate": 0,
        "SteadyDuration": 0.5,
        "DamageMultiplier": 1.6
      }
    ]
  },
  "Dimensional Bridge": {
    "name": "Dimensional Bridge",
    "ID": "211122004",
    "rarity": "Rare",
    "baseATK": 14839,
    "baseCritRate": 0.01,
    "baseCritDamage": 1.2,
    "baseWeakPoint": 1,
    "physicalType": "Pierce",
    "physicalTypeBonus": 0.1,
    "baseFireRate": 500,
    "baseReloadTime": 1.95,
    "magazine": 30,
    "shellCount": 1,
    "coreArray": null,
    "RangedInTime": 0.25,
    "ZoomInHoldDelayTime": 0.45,
    "ReloadType": "Magazine",
    "ammoType": "Special",
    "weaponType": "Beam Rifle",
    "image": "/TFD/TFDImages/Weapons/Icon_RW_BR_1007_A001.png",
    "desc": "",
    "stats": {},
    "ChargeLevelData": [
      {
        "ChargeAmount": 0,
        "ChargeRate": 0,
        "DischargeRate": 0,
        "SteadyDuration": 0,
        "DamageMultiplier": 0
      },
      {
        "ChargeAmount": 1.2,
        "ChargeRate": 1,
        "DischargeRate": 0.8,
        "SteadyDuration": 0,
        "DamageMultiplier": 1
      },
      {
        "ChargeAmount": 1.2,
        "ChargeRate": 1,
        "DischargeRate": 1,
        "SteadyDuration": 0,
        "DamageMultiplier": 1.75
      },
      {
        "ChargeAmount": 0,
        "ChargeRate": 0,
        "DischargeRate": 0,
        "SteadyDuration": 0.3,
        "DamageMultiplier": 2.5
      }
    ]
  },
  "Burning 44": {
    "name": "Burning 44",
    "ID": "211122003",
    "rarity": "Rare",
    "baseATK": 16204,
    "baseCritRate": 0.1,
    "baseCritDamage": 1.5,
    "baseWeakPoint": 1,
    "physicalType": "Pierce",
    "physicalTypeBonus": 0.1,
    "baseFireRate": 500,
    "baseReloadTime": 2.0999999999999996,
    "magazine": 50,
    "shellCount": 1,
    "coreArray": null,
    "RangedInTime": 0.25,
    "ZoomInHoldDelayTime": 0.45,
    "ReloadType": "Magazine",
    "ammoType": "Special",
    "weaponType": "Beam Rifle",
    "image": "/TFD/TFDImages/Weapons/Icon_RW_BR_1004_A001.png",
    "desc": "",
    "stats": {},
    "ChargeLevelData": [
      {
        "ChargeAmount": 0,
        "ChargeRate": 0,
        "DischargeRate": 0,
        "SteadyDuration": 0,
        "DamageMultiplier": 0
      },
      {
        "ChargeAmount": 1,
        "ChargeRate": 1,
        "DischargeRate": 0.8,
        "SteadyDuration": 0,
        "DamageMultiplier": 1
      },
      {
        "ChargeAmount": 1,
        "ChargeRate": 1,
        "DischargeRate": 1,
        "SteadyDuration": 0,
        "DamageMultiplier": 1.15
      },
      {
        "ChargeAmount": 0,
        "ChargeRate": 0,
        "DischargeRate": 0,
        "SteadyDuration": 0.3,
        "DamageMultiplier": 1.3
      }
    ]
  },
  "Dogma 21": {
    "name": "Dogma 21",
    "ID": "211891001",
    "rarity": "Common",
    "baseATK": 270080,
    "baseCritRate": 0,
    "baseCritDamage": 1.1,
    "baseWeakPoint": 1,
    "physicalType": "Crush",
    "physicalTypeBonus": 0.1,
    "baseFireRate": 75,
    "baseReloadTime": 0,
    "magazine": 8,
    "shellCount": 1,
    "coreArray": null,
    "RangedInTime": 0.35,
    "ZoomInHoldDelayTime": 0.48,
    "ReloadType": "Magazine",
    "weaponType": "Key_UI_ItemInfo_None",
    "image": "/TFD/TFDImages/Weapons/Icon_Radar_EquipDroppedItem_Tier_00.png",
    "desc": "",
    "stats": {},
    "ChargeLevelData": [
      {
        "ChargeAmount": 0.8,
        "ChargeRate": 1,
        "DischargeRate": 3,
        "SteadyDuration": 0,
        "DamageMultiplier": 0
      },
      {
        "ChargeAmount": 0,
        "ChargeRate": 0,
        "DischargeRate": 0,
        "SteadyDuration": 0,
        "DamageMultiplier": 1
      }
    ]
  },
  "Moon Fragment": {
    "name": "Moon Fragment",
    "ID": "211121003",
    "rarity": "Common",
    "baseATK": 10589,
    "baseCritRate": 0.05,
    "baseCritDamage": 1.2,
    "baseWeakPoint": 1,
    "physicalType": "Pierce",
    "physicalTypeBonus": 0.1,
    "baseFireRate": 600,
    "baseReloadTime": 1.8199999999999998,
    "magazine": 27,
    "shellCount": 1,
    "coreArray": null,
    "RangedInTime": 0.29,
    "ZoomInHoldDelayTime": 0.49,
    "ReloadType": "Magazine",
    "ammoType": "Special",
    "weaponType": "Beam Rifle",
    "image": "/TFD/TFDImages/Weapons/Icon_RW_BR_1003_A001.png",
    "desc": "",
    "stats": {},
    "ChargeLevelData": [
      {
        "ChargeAmount": 0,
        "ChargeRate": 0,
        "DischargeRate": 0,
        "SteadyDuration": 0,
        "DamageMultiplier": 0
      },
      {
        "ChargeAmount": 0.4,
        "ChargeRate": 1,
        "DischargeRate": 0.9,
        "SteadyDuration": 0,
        "DamageMultiplier": 1
      },
      {
        "ChargeAmount": 0.4,
        "ChargeRate": 1,
        "DischargeRate": 1.1,
        "SteadyDuration": 0,
        "DamageMultiplier": 1.2
      },
      {
        "ChargeAmount": 0,
        "ChargeRate": 0,
        "DischargeRate": 0,
        "SteadyDuration": 0.2,
        "DamageMultiplier": 1.4
      }
    ]
  },
  "EXCAVA": {
    "name": "EXCAVA",
    "ID": "211063003",
    "rarity": "Ultimate",
    "baseATK": 14937,
    "baseCritRate": 0.03,
    "baseCritDamage": 1.2,
    "baseWeakPoint": 1.4,
    "physicalType": "Pierce",
    "physicalTypeBonus": 0.1,
    "baseFireRate": 588.2352941176471,
    "baseReloadTime": 2,
    "magazine": 36,
    "shellCount": 1,
    "coreArray": [
      "Rainbow",
      "Rainbow",
      "Blue",
      "Green",
      "Green"
    ],
    "RangedInTime": 0.2,
    "ZoomInHoldDelayTime": 0.4,
    "ReloadType": "Magazine",
    "ammoType": "General",
    "weaponType": "Assault Rifle",
    "image": "/TFD/TFDImages/Weapons/Icon_RW_AR_1008_A001.png",
    "desc": "Hitting an enemy grants the unique effect Voltage Charge.\nWhen Voltage Charge reaches max stacks, it changes to the unique effect Energy Grenade.\nWhile Energy Grenade is active, fires an Energy Grenade when shooting while aiming, which deals increased damage based on the number of stacks. Hitting an enemy with the Energy Grenade inflicts Voltage Accumulation.",
    "stats": {
      "ElectricATK": 9560
    },
    "ChargeLevelData": []
  },
  "Wave of Light": {
    "name": "Wave of Light",
    "ID": "211083001",
    "rarity": "Ultimate",
    "baseATK": 36141,
    "baseCritRate": 0.1,
    "baseCritDamage": 1.8,
    "baseWeakPoint": 1.8,
    "physicalType": "Crush",
    "physicalTypeBonus": 0.1,
    "baseFireRate": 250,
    "baseReloadTime": 2.2,
    "magazine": 12,
    "shellCount": 1,
    "coreArray": [
      "Rainbow",
      "Orange",
      "Green",
      "Yellow",
      "Purple"
    ],
    "RangedInTime": 0.28,
    "ZoomInHoldDelayTime": 0.3,
    "ReloadType": "Magazine",
    "ammoType": "Impact",
    "weaponType": "Scout Rifle",
    "image": "/TFD/TFDImages/Weapons/Icon_RW_SCR_1005_A001.png",
    "desc": "After reloading, grants the unique ability Solar Halo.\n While Solar Halo is active, hitting an enemy spawns Dusk at the spot. Inflicts Lunar Halo on the enemies hit by Dusk.",
    "stats": {
      "FireATK": 24215
    },
    "ChargeLevelData": []
  },
  "Vestigial Organ": {
    "name": "Vestigial Organ",
    "ID": "211102004",
    "rarity": "Rare",
    "baseATK": 128353,
    "baseCritRate": 0.01,
    "baseCritDamage": 1.1,
    "baseWeakPoint": 1,
    "physicalType": "Pierce",
    "physicalTypeBonus": 0.1,
    "baseFireRate": 200,
    "baseReloadTime": 4.2,
    "magazine": 4,
    "shellCount": 1,
    "coreArray": null,
    "RangedInTime": 0.3,
    "ZoomInHoldDelayTime": 0.5,
    "ReloadType": "Magazine",
    "ammoType": "HighPowered",
    "weaponType": "Launcher",
    "image": "/TFD/TFDImages/Weapons/Icon_RW_LNC_1008_A001.png",
    "desc": "",
    "stats": {},
    "ChargeLevelData": []
  },
  "Death Roar": {
    "name": "Death Roar",
    "ID": "211102001",
    "rarity": "Rare",
    "baseATK": 124966,
    "baseCritRate": 0.35,
    "baseCritDamage": 1.5,
    "baseWeakPoint": 1,
    "physicalType": "Pierce",
    "physicalTypeBonus": 0.1,
    "baseFireRate": 60,
    "baseReloadTime": 2.8,
    "magazine": 7,
    "shellCount": 1,
    "coreArray": null,
    "RangedInTime": 0.3,
    "ZoomInHoldDelayTime": 0.5,
    "ReloadType": "Magazine",
    "ammoType": "HighPowered",
    "weaponType": "Launcher",
    "image": "/TFD/TFDImages/Weapons/Icon_RW_LNC_1001_A001.png",
    "desc": "",
    "stats": {},
    "ChargeLevelData": []
  },
  "Tamer": {
    "name": "Tamer",
    "ID": "211052004",
    "rarity": "Rare",
    "baseATK": 17631,
    "baseCritRate": 0.1,
    "baseCritDamage": 1.6,
    "baseWeakPoint": 1,
    "physicalType": "Crush",
    "physicalTypeBonus": 0.1,
    "baseFireRate": 625,
    "baseReloadTime": 2.6,
    "magazine": 100,
    "shellCount": 1,
    "coreArray": null,
    "RangedInTime": 0.3,
    "ZoomInHoldDelayTime": 0.385,
    "ReloadType": "Magazine",
    "ammoType": "General",
    "weaponType": "Machine Gun",
    "image": "/TFD/TFDImages/Weapons/Icon_RW_MG_1007_A001.png",
    "desc": "",
    "stats": {},
    "ChargeLevelData": []
  },
  "Enduring Legacy": {
    "name": "Enduring Legacy",
    "ID": "211053001",
    "rarity": "Ultimate",
    "baseATK": 13155,
    "baseCritRate": 0.2,
    "baseCritDamage": 2.3,
    "baseWeakPoint": 1,
    "physicalType": "Crush",
    "physicalTypeBonus": 0.1,
    "baseFireRate": 571.4285714285714,
    "baseReloadTime": 2.7,
    "magazine": 115,
    "shellCount": 1,
    "coreArray": [
      "Rainbow",
      "Red",
      "Yellow",
      "Yellow",
      "Purple"
    ],
    "RangedInTime": 0.185,
    "ZoomInHoldDelayTime": 0.385,
    "ReloadType": "Magazine",
    "ammoType": "General",
    "weaponType": "Machine Gun",
    "image": "/TFD/TFDImages/Weapons/Icon_RW_MG_1005_A001.png",
    "desc": "On hitting an enemy, increase Status Effect Trigger Rate corresponding to the element (Fire/Chill/Electric/Toxic) and inflicts the unique ability Quenching to the target enemy. \nOn hitting a Burned enemy, increase Firearm ATK and apply this buff to the attack.",
    "stats": {},
    "ChargeLevelData": []
  },
  "Hungry Hound": {
    "name": "Hungry Hound",
    "ID": "211011001",
    "rarity": "Common",
    "baseATK": 12712,
    "baseCritRate": 0.1,
    "baseCritDamage": 1.7,
    "baseWeakPoint": 1.5,
    "physicalType": "Pierce",
    "physicalTypeBonus": 0.1,
    "baseFireRate": 451.12781954887214,
    "baseReloadTime": 1.19,
    "magazine": 15,
    "shellCount": 1,
    "coreArray": null,
    "RangedInTime": 0.2,
    "ZoomInHoldDelayTime": 0.4,
    "ReloadType": "Magazine",
    "ammoType": "General",
    "weaponType": "Handgun",
    "image": "/TFD/TFDImages/Weapons/Icon_RW_HG_1003_A001.png",
    "desc": "",
    "stats": {},
    "ChargeLevelData": []
  },
  "Eternal Willpower": {
    "name": "Eternal Willpower",
    "ID": "211062004",
    "rarity": "Rare",
    "baseATK": 21370,
    "baseCritRate": 0.2,
    "baseCritDamage": 1.5,
    "baseWeakPoint": 1,
    "physicalType": "Pierce",
    "physicalTypeBonus": 0.1,
    "baseFireRate": 500,
    "baseReloadTime": 1.9,
    "magazine": 25,
    "shellCount": 1,
    "coreArray": null,
    "RangedInTime": 0.185,
    "ZoomInHoldDelayTime": 0.385,
    "ReloadType": "Magazine",
    "ammoType": "General",
    "weaponType": "Assault Rifle",
    "image": "/TFD/TFDImages/Weapons/Icon_RW_AR_1007_A001.png",
    "desc": "",
    "stats": {},
    "ChargeLevelData": []
  },
  "Phantom Pain": {
    "name": "Phantom Pain",
    "ID": "211062003",
    "rarity": "Rare",
    "baseATK": 12200,
    "baseCritRate": 0.09,
    "baseCritDamage": 1.5,
    "baseWeakPoint": 1,
    "physicalType": "Pierce",
    "physicalTypeBonus": 0.1,
    "baseFireRate": 722.8915662650602,
    "baseReloadTime": 1.6099999999999999,
    "magazine": 33,
    "shellCount": 1,
    "coreArray": null,
    "RangedInTime": 0.185,
    "ZoomInHoldDelayTime": 0.385,
    "ReloadType": "Magazine",
    "ammoType": "General",
    "weaponType": "Assault Rifle",
    "image": "/TFD/TFDImages/Weapons/Icon_RW_AR_1004_A001.png",
    "desc": "",
    "stats": {},
    "ChargeLevelData": []
  },
  "Caligo's Horn": {
    "name": "Caligo's Horn",
    "ID": "211062002",
    "rarity": "Rare",
    "baseATK": 14851,
    "baseCritRate": 0.09,
    "baseCritDamage": 1.5,
    "baseWeakPoint": 1,
    "physicalType": "Pierce",
    "physicalTypeBonus": 0.1,
    "baseFireRate": 631.578947368421,
    "baseReloadTime": 1.68,
    "magazine": 30,
    "shellCount": 1,
    "coreArray": null,
    "RangedInTime": 0.185,
    "ZoomInHoldDelayTime": 0.385,
    "ReloadType": "Magazine",
    "ammoType": "General",
    "weaponType": "Assault Rifle",
    "image": "/TFD/TFDImages/Weapons/Icon_RW_AR_1002_A001.png",
    "desc": "",
    "stats": {},
    "ChargeLevelData": []
  },
  "Magnus AA": {
    "name": "Magnus AA",
    "ID": "211062001",
    "rarity": "Rare",
    "baseATK": 15755,
    "baseCritRate": 0.09,
    "baseCritDamage": 1.5,
    "baseWeakPoint": 1,
    "physicalType": "Pierce",
    "physicalTypeBonus": 0.1,
    "baseFireRate": 571.4285714285714,
    "baseReloadTime": 1.68,
    "magazine": 30,
    "shellCount": 1,
    "coreArray": null,
    "RangedInTime": 0.185,
    "ZoomInHoldDelayTime": 0.385,
    "ReloadType": "Magazine",
    "ammoType": "General",
    "weaponType": "Assault Rifle",
    "image": "/TFD/TFDImages/Weapons/Icon_RW_AR_1001_A001.png",
    "desc": "",
    "stats": {},
    "ChargeLevelData": []
  },
  "Lion of Blue Mane": {
    "name": "Lion of Blue Mane",
    "ID": "211052003",
    "rarity": "Rare",
    "baseATK": 18413,
    "baseCritRate": 0.1,
    "baseCritDamage": 1.5,
    "baseWeakPoint": 1,
    "physicalType": "Crush",
    "physicalTypeBonus": 0.1,
    "baseFireRate": 428.57142857142856,
    "baseReloadTime": 3.29,
    "magazine": 110,
    "shellCount": 1,
    "coreArray": null,
    "RangedInTime": 0.185,
    "ZoomInHoldDelayTime": 0.385,
    "ReloadType": "Magazine",
    "ammoType": "General",
    "weaponType": "Machine Gun",
    "image": "/TFD/TFDImages/Weapons/Icon_RW_MG_1004_A001.png",
    "desc": "",
    "stats": {},
    "ChargeLevelData": []
  },
  "Unfinished Study": {
    "name": "Unfinished Study",
    "ID": "211052002",
    "rarity": "Rare",
    "baseATK": 13612,
    "baseCritRate": 0.03,
    "baseCritDamage": 1.5,
    "baseWeakPoint": 1,
    "physicalType": "Crush",
    "physicalTypeBonus": 0.1,
    "baseFireRate": 545.4545454545455,
    "baseReloadTime": 3.01,
    "magazine": 125,
    "shellCount": 1,
    "coreArray": null,
    "RangedInTime": 0.3,
    "ZoomInHoldDelayTime": 0.5,
    "ReloadType": "Magazine",
    "ammoType": "General",
    "weaponType": "Machine Gun",
    "image": "/TFD/TFDImages/Weapons/Icon_RW_MG_1002_A001.png",
    "desc": "",
    "stats": {},
    "ChargeLevelData": []
  },
  "Rascal V-51": {
    "name": "Rascal V-51",
    "ID": "211052001",
    "rarity": "Rare",
    "baseATK": 12929,
    "baseCritRate": 0.04,
    "baseCritDamage": 1.5,
    "baseWeakPoint": 1,
    "physicalType": "Crush",
    "physicalTypeBonus": 0.1,
    "baseFireRate": 571.4285714285714,
    "baseReloadTime": 2.4499999999999997,
    "magazine": 105,
    "shellCount": 1,
    "coreArray": null,
    "RangedInTime": 0.185,
    "ZoomInHoldDelayTime": 0.385,
    "ReloadType": "Magazine",
    "ammoType": "General",
    "weaponType": "Machine Gun",
    "image": "/TFD/TFDImages/Weapons/Icon_RW_MG_1001_A001.png",
    "desc": "",
    "stats": {},
    "ChargeLevelData": []
  },
  "Alter Ego": {
    "name": "Alter Ego",
    "ID": "211042003",
    "rarity": "Rare",
    "baseATK": 13284,
    "baseCritRate": 0.08,
    "baseCritDamage": 1.5,
    "baseWeakPoint": 1,
    "physicalType": "Burst",
    "physicalTypeBonus": 0.1,
    "baseFireRate": 800,
    "baseReloadTime": 1.74,
    "magazine": 35,
    "shellCount": 1,
    "coreArray": null,
    "RangedInTime": 0.148,
    "ZoomInHoldDelayTime": 0.348,
    "ReloadType": "Magazine",
    "ammoType": "General",
    "weaponType": "Submachine Gun",
    "image": "/TFD/TFDImages/Weapons/Icon_RW_SMG_1004_A001.png",
    "desc": "",
    "stats": {},
    "ChargeLevelData": []
  },
  "Devil's Call": {
    "name": "Devil's Call",
    "ID": "211042001",
    "rarity": "Rare",
    "baseATK": 12732,
    "baseCritRate": 0.07,
    "baseCritDamage": 1.5,
    "baseWeakPoint": 1,
    "physicalType": "Burst",
    "physicalTypeBonus": 0.1,
    "baseFireRate": 779.2207792207793,
    "baseReloadTime": 1.32,
    "magazine": 26,
    "shellCount": 1,
    "coreArray": null,
    "RangedInTime": 0.148,
    "ZoomInHoldDelayTime": 0.348,
    "ReloadType": "Magazine",
    "ammoType": "General",
    "weaponType": "Submachine Gun",
    "image": "/TFD/TFDImages/Weapons/Icon_RW_SMG_1001_A001.png",
    "desc": "",
    "stats": {},
    "ChargeLevelData": []
  },
  "New Beginning": {
    "name": "New Beginning",
    "ID": "211012004",
    "rarity": "Rare",
    "baseATK": 11164,
    "baseCritRate": 0.1,
    "baseCritDamage": 1.8,
    "baseWeakPoint": 1.5,
    "physicalType": "Pierce",
    "physicalTypeBonus": 0.1,
    "baseFireRate": 750,
    "baseReloadTime": 1.15,
    "magazine": 15,
    "shellCount": 1,
    "coreArray": null,
    "RangedInTime": 0.25,
    "ZoomInHoldDelayTime": 0.45,
    "ReloadType": "Magazine",
    "ammoType": "General",
    "weaponType": "Handgun",
    "image": "/TFD/TFDImages/Weapons/Icon_RW_HG_1007_A001.png",
    "desc": "",
    "stats": {},
    "ChargeLevelData": []
  },
  "Rose of Aisha": {
    "name": "Rose of Aisha",
    "ID": "211012003",
    "rarity": "Rare",
    "baseATK": 11453,
    "baseCritRate": 0.2,
    "baseCritDamage": 1.8,
    "baseWeakPoint": 1.7,
    "physicalType": "Pierce",
    "physicalTypeBonus": 0.1,
    "baseFireRate": 666.6666666666667,
    "baseReloadTime": 1.1199999999999999,
    "magazine": 14,
    "shellCount": 1,
    "coreArray": null,
    "RangedInTime": 0.25,
    "ZoomInHoldDelayTime": 0.45,
    "ReloadType": "Magazine",
    "ammoType": "General",
    "weaponType": "Handgun",
    "image": "/TFD/TFDImages/Weapons/Icon_RW_HG_1004_A001.png",
    "desc": "",
    "stats": {},
    "ChargeLevelData": []
  },
  "Millennium Frost": {
    "name": "Millennium Frost",
    "ID": "211012002",
    "rarity": "Rare",
    "baseATK": 13596,
    "baseCritRate": 0.01,
    "baseCritDamage": 1.8,
    "baseWeakPoint": 1.5,
    "physicalType": "Pierce",
    "physicalTypeBonus": 0.1,
    "baseFireRate": 600,
    "baseReloadTime": 1.26,
    "magazine": 15,
    "shellCount": 1,
    "coreArray": null,
    "RangedInTime": 0.2,
    "ZoomInHoldDelayTime": 0.4,
    "ReloadType": "Magazine",
    "ammoType": "General",
    "weaponType": "Handgun",
    "image": "/TFD/TFDImages/Weapons/Icon_RW_HG_1002_A001.png",
    "desc": "",
    "stats": {},
    "ChargeLevelData": []
  },
  "Red Wolf": {
    "name": "Red Wolf",
    "ID": "211012001",
    "rarity": "Rare",
    "baseATK": 14105,
    "baseCritRate": 0.12,
    "baseCritDamage": 1.8,
    "baseWeakPoint": 1.5,
    "physicalType": "Pierce",
    "physicalTypeBonus": 0.1,
    "baseFireRate": 545.4545454545455,
    "baseReloadTime": 1.0499999999999998,
    "magazine": 12,
    "shellCount": 1,
    "coreArray": null,
    "RangedInTime": 0.2,
    "ZoomInHoldDelayTime": 0.4,
    "ReloadType": "Magazine",
    "ammoType": "General",
    "weaponType": "Handgun",
    "image": "/TFD/TFDImages/Weapons/Icon_RW_HG_1001_A001.png",
    "desc": "",
    "stats": {},
    "ChargeLevelData": []
  },
  "Ominous Hound": {
    "name": "Ominous Hound",
    "ID": "211061001",
    "rarity": "Common",
    "baseATK": 13930,
    "baseCritRate": 0.05,
    "baseCritDamage": 1.2,
    "baseWeakPoint": 1,
    "physicalType": "Pierce",
    "physicalTypeBonus": 0.1,
    "baseFireRate": 600,
    "baseReloadTime": 1.75,
    "magazine": 31,
    "shellCount": 1,
    "coreArray": null,
    "RangedInTime": 0.2,
    "ZoomInHoldDelayTime": 0.4,
    "ReloadType": "Magazine",
    "ammoType": "General",
    "weaponType": "Assault Rifle",
    "image": "/TFD/TFDImages/Weapons/Icon_RW_AR_1003_A001.png",
    "desc": "",
    "stats": {},
    "ChargeLevelData": []
  },
  "Cygnus": {
    "name": "Cygnus",
    "ID": "211051001",
    "rarity": "Common",
    "baseATK": 11934,
    "baseCritRate": 0.01,
    "baseCritDamage": 1.1,
    "baseWeakPoint": 1,
    "physicalType": "Crush",
    "physicalTypeBonus": 0.1,
    "baseFireRate": 521.7391304347826,
    "baseReloadTime": 2.59,
    "magazine": 107,
    "shellCount": 1,
    "coreArray": null,
    "RangedInTime": 0.185,
    "ZoomInHoldDelayTime": 0.385,
    "ReloadType": "Magazine",
    "ammoType": "General",
    "weaponType": "Machine Gun",
    "image": "/TFD/TFDImages/Weapons/Icon_RW_MG_1003_A001.png",
    "desc": "",
    "stats": {},
    "ChargeLevelData": []
  },
  "Albinism": {
    "name": "Albinism",
    "ID": "211041001",
    "rarity": "Common",
    "baseATK": 11568,
    "baseCritRate": 0.15,
    "baseCritDamage": 1.3,
    "baseWeakPoint": 1,
    "physicalType": "Burst",
    "physicalTypeBonus": 0.1,
    "baseFireRate": 750,
    "baseReloadTime": 1.46,
    "magazine": 26,
    "shellCount": 1,
    "coreArray": null,
    "RangedInTime": 0.25,
    "ZoomInHoldDelayTime": 0.45,
    "ReloadType": "Magazine",
    "ammoType": "General",
    "weaponType": "Submachine Gun",
    "image": "/TFD/TFDImages/Weapons/Icon_RW_SMG_1003_A001.png",
    "desc": "",
    "stats": {},
    "ChargeLevelData": []
  },
  "Tamed Beast": {
    "name": "Tamed Beast",
    "ID": "211101001",
    "rarity": "Common",
    "baseATK": 72897,
    "baseCritRate": 0.35,
    "baseCritDamage": 1.5,
    "baseWeakPoint": 1,
    "physicalType": "Pierce",
    "physicalTypeBonus": 0.1,
    "baseFireRate": 80,
    "baseReloadTime": 2.8,
    "magazine": 12,
    "shellCount": 1,
    "coreArray": null,
    "RangedInTime": 0.3,
    "ZoomInHoldDelayTime": 0.5,
    "ReloadType": "Magazine",
    "ammoType": "HighPowered",
    "weaponType": "Launcher",
    "image": "/TFD/TFDImages/Weapons/Icon_RW_LNC_1004_A001.png",
    "desc": "",
    "stats": {},
    "ChargeLevelData": []
  },
  "Guardian R4": {
    "name": "Guardian R4",
    "ID": "211102002",
    "rarity": "Rare",
    "baseATK": 228410,
    "baseCritRate": 0.5,
    "baseCritDamage": 2,
    "baseWeakPoint": 1,
    "physicalType": "Pierce",
    "physicalTypeBonus": 0.1,
    "baseFireRate": 50,
    "baseReloadTime": 1.47,
    "magazine": 1,
    "shellCount": 1,
    "coreArray": null,
    "RangedInTime": 0.3,
    "ZoomInHoldDelayTime": 0.5,
    "ReloadType": "Magazine",
    "ammoType": "HighPowered",
    "weaponType": "Launcher",
    "image": "/TFD/TFDImages/Weapons/Icon_RW_LNC_1002_A001.png",
    "desc": "",
    "stats": {},
    "ChargeLevelData": []
  },
  "Lightspeed Barrel": {
    "name": "Lightspeed Barrel",
    "ID": "211102003",
    "rarity": "Rare",
    "baseATK": 99654,
    "baseCritRate": 0.35,
    "baseCritDamage": 1.5,
    "baseWeakPoint": 1,
    "physicalType": "Pierce",
    "physicalTypeBonus": 0.1,
    "baseFireRate": 66.66666666666667,
    "baseReloadTime": 2.8,
    "magazine": 9,
    "shellCount": 1,
    "coreArray": null,
    "RangedInTime": 0.3,
    "ZoomInHoldDelayTime": 0.5,
    "ReloadType": "Magazine",
    "ammoType": "HighPowered",
    "weaponType": "Launcher",
    "image": "/TFD/TFDImages/Weapons/Icon_RW_LNC_1003_A001.png",
    "desc": "",
    "stats": {},
    "ChargeLevelData": []
  },
  "Fireworks": {
    "name": "Fireworks",
    "ID": "211032003",
    "rarity": "Rare",
    "baseATK": 22570,
    "baseCritRate": 0.01,
    "baseCritDamage": 1.15,
    "baseWeakPoint": 1,
    "physicalType": "Burst",
    "physicalTypeBonus": 0.1,
    "baseFireRate": 67.56756756756756,
    "baseReloadTime": 1.6099999999999999,
    "magazine": 12,
    "shellCount": 6,
    "coreArray": null,
    "RangedInTime": 0.168,
    "ZoomInHoldDelayTime": 0.368,
    "ReloadType": "Magazine",
    "ammoType": "HighPowered",
    "weaponType": "Shotgun",
    "image": "/TFD/TFDImages/Weapons/Icon_RW_SG_1004_A001.png",
    "desc": "",
    "stats": {},
    "ChargeLevelData": []
  },
  "The Last Knight": {
    "name": "The Last Knight",
    "ID": "211032001",
    "rarity": "Rare",
    "baseATK": 10320,
    "baseCritRate": 0.03,
    "baseCritDamage": 1.2,
    "baseWeakPoint": 1,
    "physicalType": "Burst",
    "physicalTypeBonus": 0.1,
    "baseFireRate": 120,
    "baseReloadTime": 1.89,
    "magazine": 11,
    "shellCount": 9,
    "coreArray": null,
    "RangedInTime": 0.168,
    "ZoomInHoldDelayTime": 0.368,
    "ReloadType": "Magazine",
    "ammoType": "HighPowered",
    "weaponType": "Shotgun",
    "image": "/TFD/TFDImages/Weapons/Icon_RW_SG_1001_A001.png",
    "desc": "",
    "stats": {},
    "ChargeLevelData": []
  },
  "Gangster": {
    "name": "Gangster",
    "ID": "211031001",
    "rarity": "Common",
    "baseATK": 19888,
    "baseCritRate": 0.01,
    "baseCritDamage": 1.1,
    "baseWeakPoint": 1,
    "physicalType": "Burst",
    "physicalTypeBonus": 0.1,
    "baseFireRate": 55.04587155963302,
    "baseReloadTime": 1.68,
    "magazine": 9,
    "shellCount": 12,
    "coreArray": null,
    "RangedInTime": 0.16,
    "ZoomInHoldDelayTime": 0.36,
    "ReloadType": "Rounds",
    "ammoType": "HighPowered",
    "weaponType": "Shotgun",
    "image": "/TFD/TFDImages/Weapons/Icon_RW_SG_1003_A001.png",
    "desc": "",
    "stats": {},
    "ChargeLevelData": []
  },
  "Subconsciousness": {
    "name": "Subconsciousness",
    "ID": "211032004",
    "rarity": "Rare",
    "baseATK": 17063,
    "baseCritRate": 0.02,
    "baseCritDamage": 1.2,
    "baseWeakPoint": 1,
    "physicalType": "Burst",
    "physicalTypeBonus": 0.1,
    "baseFireRate": 120,
    "baseReloadTime": 1.45,
    "magazine": 10,
    "shellCount": 8,
    "coreArray": null,
    "RangedInTime": 0.168,
    "ZoomInHoldDelayTime": 0.368,
    "ReloadType": "Rounds",
    "ammoType": "HighPowered",
    "weaponType": "Shotgun",
    "image": "/TFD/TFDImages/Weapons/Icon_RW_SG_1007_A001.png",
    "desc": "",
    "stats": {},
    "ChargeLevelData": []
  },
  "In a Blink": {
    "name": "In a Blink",
    "ID": "211032002",
    "rarity": "Rare",
    "baseATK": 20475,
    "baseCritRate": 0.02,
    "baseCritDamage": 1.2,
    "baseWeakPoint": 1,
    "physicalType": "Burst",
    "physicalTypeBonus": 0.1,
    "baseFireRate": 75,
    "baseReloadTime": 1.54,
    "magazine": 8,
    "shellCount": 10,
    "coreArray": null,
    "RangedInTime": 0.16,
    "ZoomInHoldDelayTime": 0.36,
    "ReloadType": "Rounds",
    "ammoType": "HighPowered",
    "weaponType": "Shotgun",
    "image": "/TFD/TFDImages/Weapons/Icon_RW_SG_1002_A001.png",
    "desc": "",
    "stats": {},
    "ChargeLevelData": []
  },
  "FrostWatcher": {
    "name": "FrostWatcher",
    "ID": "211083004",
    "rarity": "Ultimate",
    "baseATK": 45777,
    "baseCritRate": 0.06,
    "baseCritDamage": 1.8,
    "baseWeakPoint": 1.35,
    "physicalType": "Crush",
    "physicalTypeBonus": 0.1,
    "baseFireRate": 150,
    "baseReloadTime": 2.15,
    "magazine": 21,
    "shellCount": 1,
    "coreArray": [
      "Rainbow",
      "Orange",
      "Blue",
      "Green",
      "Purple"
    ],
    "RangedInTime": 0.35,
    "ZoomInHoldDelayTime": 0.4,
    "ReloadType": "Magazine",
    "ammoType": "Impact",
    "weaponType": "Scout Rifle",
    "image": "/TFD/TFDImages/Weapons/Icon_RW_SCR_1009_A001.png",
    "desc": "On landing a Critical Hit on an enemy at a certain distance, the unique ability Cold Surveillance is applied to the target.\nHitting the Weak Point of an enemy at a certain distance grants self the unique effect Subzero Sensation.\nDefeating an enemy grants self the unique effect Chill Synchronization.\nWhile Chill Synchronization is active, ignores the Movement Speed reduction by Hailey's Cold Fury.",
    "stats": {
      "ChillATK": 16480,

      // "enemyChillResistanceReductionCORE": -0.40 - 0.20 - 0.20,
    },
    "ChargeLevelData": []
  }
}