let bosses = {
    // {
    //     "name":"attackName",
    //     "description": "attackDescription",
    //     "damage": 0,
    //     "hpBased": false,
    //     "hpPercent": 0,
    //     "drBypass": false,
    //     "canBeLethal": false,
    //     "lethalCondition": "",
    //     "isBuffed": false,
    //     "attackType": "Hit",
    //     "frequency": 0,
    // },
    "Annihilation": {
        "image": "/brotherLibrary/bossImages/Annihilation.jpg",
        "bossType": "worldBoss",
        "buffs": {},
        "attacks": [
            {
                "name":"Basic - Flying Overhead",
                "description": "Used to initiate many combos, but can only be launched while Annihilation is flying. A flying overhead sword swing that brings him down to the ground as well.",
                "damage": 197.955,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Basic 1",
                "description": "First basic attack: left sword swing.",
                "damage": 197.955,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Basic 2",
                "description": "Second basic attack: Right dragging sword swing.",
                "damage": 197.955,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Forward Sword Drag",
                "description": "Annihilation drags his sword on the ground, moving straight forward before launching himself into the air in prep for a ground slam. This attack is only for the damage of the sword drag.",
                "damage": 197.955,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Slam AOE Wave",
                "description": "After dragging his sword and launching into the sky, Annihilation will charge for a moment before slamming back to the ground sending out a red AOE shockwave.",
                "damage": 217.751,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Root Snare",
                "description": "After doing slam attacks, Annihilation will sometimes pierce the ground with his sword and send out root snares to catch you. This attack is only for the damage of the root snare if it catches you.",
                "damage": 19.796,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Orbital Strikes",
                "description": "Throughout the duration of the fight, little red beacons will strike the ground, leaving a red trail into the sky where they came from. After long enough, the beacons will detonate, dealing damage within the red circle around them.",
                "damage": 110.855,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Orb Detonations",
                "description": "In both phase 1 and phase 2, Annihilation can summon floating spheres that when left alive long enough, will home in on the player and detonate. This is per orb.",
                "damage": 89.303,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": true,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Dive Slam 1",
                "description": "Annihilation will raise into the sky while spinning before returning to the ground to do a piercing dive slam AOE. This is part of a 2-3 hit combo.",
                "damage": 138.569,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": true,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Dive Slam 2",
                "description": "Annihilation will raise into the sky while spinning before returning to the ground to do a piercing dive slam AOE. This is part of a 2-3 hit combo.",
                "damage": 138.569,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": true,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            }, 
            {
                "name":"Dive Slam 3",
                "description": "Annihilation will raise into the sky while spinning before returning to the ground to do a piercing dive slam AOE. This is the third and final strike of the combo, and it is not guaranteed to happen. Rather, this attack is incredibly rare.",
                "damage": 138.569,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": true,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            }, 
            {
                "name":"P2: Basic - Overhead",
                "description": "Annihilation's Split form will do an overhead strike with their sword.",
                "damage": 158.364,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            }, 
            {
                "name":"P2: Halves Swipe",
                "description": "Annihilation's Split form will drag the sword from the center point of the arena, to the end of whichever half the player is standing in.",
                "damage": 158.364,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"P2: Full Swipe",
                "description": "Annihilation's Split form will drag the sword from one end of the arena, to the other end.",
                "damage": 158.364,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            }, 
            {
                "name":"P2: Cloud Slam",
                "description": "Annihilation's Split form will slam sending an instantaneous shockwave to the entire arena. At the same time, it will spawn a pestilent cloud on the player that will afflict them with Data Corruption if stood in for too long.",
                "damage": 59.387,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            }, 
            {
                "name":"P2: Grid Lines",
                "description": "Annihilation's Split form will create a set of grid lines in front of him before launching the grid towards the back of arena. This is per grid line, multiple can hit at once.",
                "damage": 168.262,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            }, 
            {
                "name":"P2: Orb Spawn Shockwave",
                "description": "Annihilation's Split form will blast the arena, pushing everyone away from him. He'll do it once more before spawning orbs. This is attack is per shockwave he emits before spawning orbs.",
                "damage": 19.796,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            }, 
            {
                "name":"P2: Roots Slap",
                "description": "Annihilation's Split will sometimes spawn roots in a grid within the arena floor. After some time, the roots will indicate which direction they will fall towards (always towards another root) before doing the attack.",
                "damage": 22.5,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            }, 
        ]
    },



    "Lydusa": {
        "image": "/brotherLibrary/bossImages/Lydusa.jpg",
        "bossType": "worldBoss",
        "buffs": 0,
        "attacks": [
            {
                "name":"Amber Orb Projectiles",
                "description": "Lydusa shoots amber colored, spikey orb projectiles.",
                "damage": 89.303,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Amber Spears",
                "description": "Lydusa quickly launches an amber spear from one of the tips of her... hair?",
                "damage": 178.606,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Pool Detonations",
                "description": "Rocky-pools left on the ground detonate within a small range. The pools do not do DoT damage, only the detonation can hurt you.",
                "damage": 142.885,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Tear Orb Projectiles",
                "description": `Projectiles launched by "Tear" Orbs that spawn when Lydusa cries.`,
                "damage": 71.443,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,

            },
            {
                "name":"Wrecking Ball AOE",
                "description": "The slam + AOE damage from Lydusa's transformed state(blue face), wrecking ball slam.",
                "damage": 178.606,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Saw",
                "description": "The saw spinning damage from Lydusa's transformed state(blue face).",
                "damage": 196.467,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"World's Edge Slash",
                "description": "In the latter half of the fight, Lydusa can sometimes launch amber-colored World's Edge type slash projectiles instead of the Amber Spearss",
                "damage": 178.606,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Sandstorm Damage",
                "description": `During Lydusa's "Final Stand" phase, when the walls raise there is a sandstorm at the back of the hallway to punish you for getting pushed back. This is the damage of the sandstorm.`,
                "damage": 5,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "DOT",
                "frequency": 0.5,
            },
            {
                "name":"Wall Hits",
                "description": `During Lydusa's "Final Stand" phase, walls slide towards you pushing you back to the end of the hall. This is the damage walls do you to you if they hit you.`,
                "damage": 178.606,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Wall Clap",
                "description": `During Lydusa's "Final Stand" phase, after the wall dodge is over, if you fail to kill Lydusa before the walls converge, they'll expand for a brief moment before clapping together causing instant death.`,
                "damage": 999999,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": true,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
        ]
    },

    "Ravager": {
        "image": "/brotherLibrary/bossImages/Ravager.jpg",
        "bossType": "worldBoss",
        "buffs": 0.10,
        "attacks": [
            {
                "name":"Bleed",
                "description": "Ravager can apply Bleed to you. This is the damage it deals per tick. Not buffed by Ravager's Mist-Roar buff.",
                "damage": 1.203,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "DOT",
                "frequency": 0.5,
            },
            {
                "name":"Basic 1",
                "description": "Basic attack combo: swing 1.",
                "damage": 186.644,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": true,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Basic 2",
                "description": "Basic attack combo: swing 2.",
                "damage": 186.644,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": true,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Basic Bite 1",
                "description": "Basic attack combo: bite 1.",
                "damage": 186.644,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": true,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Basic Bite 2",
                "description": "Basic attack combo: bite 2.",
                "damage": 186.644,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": true,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Kick-Leap",
                "description": "Ravager will jump to the player, kicking off of them to leap far away.",
                "damage": 186.644,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": true,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Sprint Bite",
                "description": "Ravager will sprint towards the player, biting when he arrives.",
                "damage": 186.644,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": true,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Sprint Follow-Up",
                "description": "Ravager will sometimes do a follow-up swipe after the Sprint Bite attack.",
                "damage": 149.315,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": true,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Stagger Wave",
                "description": "Ravager will grab the ground and raise part of it, shooting out a red wave projectile that travels along the ground towards the player.",
                "damage": 186.644,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": true,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Spin - Primary Hits",
                "description": "Ravager will create a vortex that pulls the player into him while spinning. The spin has 2 separate instances of damage while active, this accounts for the first or primary instances of damage.",
                "damage": 111.986,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": true,
                "attackType": "DOT",
                "frequency": 0.82,
                "duration": 10,
            },
            {
                "name":"Spin - Secondary Hits",
                "description": "Ravager will create a vortex that pulls the player into him while spinning. The spin has 2 separate instances of damage while active, this accounts for the secondary instances of damage.",
                "damage": 47.509,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": true,
                "attackType": "DOT",
                "frequency": 0.82,
                "duration": 10,
            },
            {
                "name":"Spin - TOTAL (readme)",
                "description": "This is a composite total of the damage Ravager deals during his spin from BOTH primary and secondary attacks. THIS IS NOT A REAL ATTACK, this is a fake attack just to give you an easier time trying to see how much damage the spin does.",
                "damage": 159.495,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": true,
                "attackType": "DOT",
                "frequency": 0.82,
                "duration": 10,
            },
            {
                "name":"Scream AOE",
                "description": "Ravager will charge up without moving before emitting a scream AOE. Not buffed by Ravager's Mist-Roar buff.",
                "damage": 74.657,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "DOT",
                "frequency": 0.4,
                "duration": 2,
            },
            {
                "name":"Roller Summon Swing",
                "description": `Ravager will shake and shed his "fleas" which are Root Hollow minions. These minions have two attacks, a swing and a spin, this is the swing. Not buffed by Ravager's Mist-Roar buff.`,
                "damage": 71.443,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Roller Summon Spin",
                "description": `Ravager will shake and shed his "fleas" which are Root Hollow minions. These minions have two attacks, a swing and a spin, this is the Spin. Not buffed by Ravager's Mist-Roar buff.`,
                "damage": 130.978,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
        ]
    },


    "Tal'Ratha (Meta)": {
        "image": "/brotherLibrary/bossImages/TalMeta.jpg",
        "bossType": "worldBoss",
        "buffs": 0,
        "attacks": [
            {
                "name":"Basic 1",
                "description": "Basic attack 1: left swing.",
                "damage": 254.514,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Basic 2",
                "description": "Basic attack 2: right swing",
                "damage": 254.514,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Basic 3",
                "description": "Basic attack 3: a joined-hands overhead swing.",
                "damage": 254.514,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Teleporting Stampede",
                "description": `Tal'Ratha leaves his mouth open while teleporting to different sections of the arena, charging towards the player before teleporting to repeat the attack.`,
                "damage": 169.676,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,

            },
            {
                "name":"Wide Swipe Follow-up",
                "description": "Whenever the player is to either side of Tal'Ratha, he'll spin around with a wide arm swing. This attack can also be seen as a follow-up attack to some other combos.",
                "damage": 254.514,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": true,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Skadoosh",
                "description": "Tal'Ratha rapidly inflates his belly, booping the player if nearby.",
                "damage": 339.352,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Orb Toss",
                "description": "Tal'Ratha will throw a yellow energy orb, sometimes following up with a second orb at random.",
                "damage": 135.741,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Shockwave Ripple",
                "description": `Whenever Tal'Ratha enters or exits from a teleport, he'll typically send out a shockwave that rippled to the edges of the entire arena. This is the damage for that ripple.`,
                "damage": 186.644,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Star Spiral",
                "description": `While preparing for the star fall attack, Tal'Ratha will shoot out several barrages of stars that move away from him in a spiral shape. This is the damage for a single star if it hits.`,
                "damage": 152.708,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Star Fall",
                "description": `After shooting several volleys of spiral stars, Tal'Ratha will charge up and slam all elevated stars to the ground.`,
                "damage": 212.095,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Acid Puke",
                "description": `Tal'Ratha will shoot a gust that pushes players towards the edge of the arena, while also launching numerous acid puke projectiles. This is the damage for each projectile.`,
                "damage": 169.676,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
        ]
    },
    "Tal'Ratha (Phys)": {
        "image": "/brotherLibrary/bossImages/TalPhys.jpg",
        "bossType": "worldBoss",
        "buffs": 0,
        "attacks": [
            {
                "name":"Pod Toss",
                "description": "Tal'Ratha throws a cryo-pod. This is for the damage of the pod impact, not the Drzyr that comes out of it.",
                "damage": 113.117,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Rubble Toss",
                "description": "Sometimes instead of a cryo-pod, Tal'Ratha will throw broken down rubble instead for slightly less damage.",
                "damage": 90.494,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Basic 1",
                "description": "Basic attack 1: left swing.",
                "damage": 169.676,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Basic 2",
                "description": "Basic attack 2: right swing",
                "damage": 169.676,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Basic 3",
                "description": "Basic attack 3: a joined-hands overhead swing.",
                "damage": 169.676,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Leap Slam AOE",
                "description": `Tal'Ratha leaps towards the player, dealing damage in an AOE on impact.`,
                "damage": 124.429,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,

            },
            {
                "name":"Skadoosh",
                "description": "Tal'Ratha rapidly inflates his belly, booping the player if nearby.",
                "damage": 226.235,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Charge Bite 1",
                "description": "Tal'Ratha charges towards the player doing 2 bite attacks in rapid succuession: the first attack.",
                "damage": 113.117,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": true,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Charge Bite 2",
                "description": "Tal'Ratha charges towards the player doing 2 bite attacks in rapid succuession: the second attack.",
                "damage": 113.117,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Roll",
                "description": "Tal'Ratha rolls on his side in either direction.",
                "damage": 180.988,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": true,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Kick",
                "description": "If Tal'Ratha detects the player hiding behind him, he'll kick them.",
                "damage": 169.676,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Wide Swipe Follow-up",
                "description": "Whenever the player is to either side of Tal'Ratha, he'll spin around with a wide arm swing. This attack can also be seen as a follow-up attack to some other combos.",
                "damage": 169.676,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": true,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Acid Puke",
                "description": `Tal'Ratha will launch numerous acid puke projectiles. This is the damage for each projectile.`,
                "damage": 56.559,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Eating Chomp 1",
                "description": `Tal'Ratha suck the player towards him. If he catches you, he'll initiate a combo of attacks where he eats you. This damage is for the first chomp in that combo.`,
                "damage": 152.708,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": true,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Eating Chomp 2",
                "description": `After the first chomp in the eating-combo, Tal'Ratha will flip the player like a pancake in the air and then bite again.`,
                "damage": 22.623,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": true,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Eating Chomp Shake",
                "description": `After the second chomp in the eating-combo, Tal'Ratha shake the player like a dog with a chew toy. This attack hits 7 times over 1 second.`,
                "damage": 3.394,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": true,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "DOT",
                "frequency": 0.14285714285714285714285714285714,
                "duration": 1,
            },
            {
                "name":"Eating Spit-Out",
                "description": `To wrap up the eating combo, Tal'Ratha will spit out the player bouncing them off the ground.`,
                "damage": 22.623,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": true,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Psionic Bolts",
                "description": `Tal'Ratha will bring his hands to his head, and with eyes glowing he'll launch several energy projectiles at you.`,
                "damage": 113.117,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Drzyr Zombie Swing",
                "description": `After throwing pods at you, Drzyr citizens will be release and can start attacking you. This is the damage for any given attack of theirs that hits you.`,
                "damage": 148.839,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
        ]
    },


    "Venom": {
        "image": "/brotherLibrary/bossImages/Venom.jpg",
        "bossType": "miniBoss",
        "buffs": 0,
        "attacks": [
            {
                "name":"Basic 1",
                "description": "Basic attack chain, spear swing 1",
                "damage": 148.839,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Basic 2",
                "description": "Basic attack chain, spear swing 2",
                "damage": 148.839,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Arc Slash 1 Overhead",
                "description": "Charged attacks that shoot out a red arcing projectile wave, swing 1: an overhead slash.",
                "damage": 148.839,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Arc Slash 2 AOE",
                "description": "Charged attacks that shoot out a red arcing projectile wave, swing 2: a horizontal 360 AOE slash.",
                "damage": 178.606,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,

            },
            {
                "name":"Puddle Spawn Slam (Strike)",
                "description": "An attack that can spawn several DOT puddles. This is the physical swing of that attack before it hits the ground.",
                "damage": 74.419,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Puddle Spawn Slam (AOE)",
                "description": "An attack that can spawn several DOT puddles. This is the resulting AOE explosion that results once the strike hits the ground.",
                "damage": 253.026,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": false,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Triple Orb Throw",
                "description": "Venom throws out 3 glowing projectiles, but this version neither attaches to you nor explodes. This damage is per orb that touches you, but it is extremely hard to get hit by more than one.",
                "damage": 104.187,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": true,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Triple Orb Throw (Sticky)",
                "description": "Venom throws out 3 glowing projectiles, but this version leaves an attached orb. The damage here is only for the orb attaching, not exploding.",
                "damage": 74.419,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": true,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Triple Orb Explosions",
                "description": "Venom throws out 3 glowing projectiles that can attach and explode. This damage is only for the resulting explosion of a single orb, whether it attached to you or was simply close by.",
                "damage": 119.071,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": true,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Puddle DOT",
                "description": "Red pools spawned by Venom via various attacks. Does %HP true damage when you stand in them.",
                "damage": 0,
                "hpBased": true,
                "hpPercent": 39.591,
                "drBypass": true,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "%HP",
                "frequency": 0.5,
            },
            {
                "name":"Spear Throw",
                "description": "Venom throws his spear at you while he is in a flying state.",
                "damage": 223.258,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": true,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Spear Dive Slam",
                "description": "Venom grabs his spear after throwing it, goes up into the air, and then returns to the ground with a piercing slam AOE.",
                "damage": 223.258,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": true,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Spear Rush",
                "description": "Venom leans forward just slightly, bringing the spear closer to his chest before dashing forward.",
                "damage": 223.258,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": true,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Plant Projectile",
                "description": "Venom summons Root Plant minions, this damage is for the projectile they can shoot out that would otherwise create an AOE damage instance if it touched the ground.",
                "damage": 89.303,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": true,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Plant AOE",
                "description": "Venom summons Root Plant minions, this damage is for the AOE damage if the summon's projectile hits the ground.",
                "damage": 89.303,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": true,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Pillar Strikes",
                "description": "Venom holds still and pierces the ground with his spear repeatedly. Every time he does, red pillars that reach into the sky will appear around the map with a slight delay before doing massive damage. Pillars can overlap each other, stacking more than one instance of damage.",
                "damage": 178.606,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": true,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
            {
                "name":"Flight Descent Slam",
                "description": "Venom will sometimes raise himself into the air during the fight. If he does not come down via an attack like a spear throw/slam, then he will simply descend to the ground after a fixed amount of time. This attack is only for the damage when he returns to the ground after timing out in the sky.",
                "damage": 148.839,
                "hpBased": false,
                "hpPercent": 0,
                "drBypass": true,
                "canBeLethal": false,
                "lethalCondition": "",
                "isBuffed": false,
                "attackType": "Hit",
                "frequency": 0,
            },
        ]
    },
}